
-- ===========================================================================================================
-- Author:		<Golam Rabbi>
-- Create date: <14-Sep-15 2:09:40 PM>
-- Description:	<> EXEC [SPJobCardEdit]  '0835','2017-06-26', '2017-07-25'
-- ===========================================================================================================

CREATE PROCEDURE [dbo].[SPJobCardEdit]
						

					  @jobCardName			NVARCHAR(50)
				     ,@employeeCardId		NVARCHAR(10)		
					 ,@fromDate				DATETIME
					 ,@toDate				DATETIME						
								
AS

BEGIN
	
	SET NOCOUNT ON;
			 

					IF(@JobCardName = 'EmployeeJobCardModel')
					BEGIN

							SELECT [Id]
								  ,[EmployeeId]
								  ,[Year]
								  ,[Month]
								  ,[MonthName]
								  ,[FromDate]
								  ,[ToDate]
								  ,[CompanyId]
								  ,[CompanyName]
								  ,[CompanyNameInBengali]
								  ,[CompanyAddress]
								  ,[CompanyAddressInBengali]
								  ,[BranchId]
								  ,[BranchName]
								  ,[BranchNameInBengali]
								  ,[BranchUnitId]
								  ,[UnitName]
								  ,[UnitNameInBengali]
								  ,[BranchUnitDepartmentId]
								  ,[DepartmentName]
								  ,[DepartmentNameInBengali]
								  ,[DepartmentSectionId]
								  ,[SectionName]
								  ,[SectionNameInBengali]
								  ,[DepartmentLineId]
								  ,[LineName]
								  ,[LineNameInBengali]
								  ,[EmployeeCardId]
								  ,[EmployeeName]
								  ,[EmployeeNameInBengali]
								  ,[MobileNo]
								  ,[EmployeeTypeId]
								  ,[EmployeeType]
								  ,[EmployeeTypeInBengali]
								  ,[EmployeeGradeId]
								  ,[EmployeeGrade]
								  ,[EmployeeGradeInBengali]
								  ,[EmployeeDesignationId]
								  ,[EmployeeDesignation]
								  ,[EmployeeDesignationInBengali]
								  ,[EmployeeActiveStatusId]
								  ,[EmployeeCategoryId]
								  ,[JoiningDate]
								  ,[QuitDate]
								  ,[TotalDays]
								  ,[WorkingDays]
								  ,[PresentDays]
								  ,[LateDays]
								  ,[OSDDays]
								  ,[AbsentDays]
								  ,[LeaveDays]
								  ,[LWPDays]
								  ,[Holidays]
								  ,[WeekendDays]
								  ,[PayDays]
								  ,[CasualLeave]
								  ,[SickLeave]
								  ,[MaternityLeave]
								  ,[EarnLeave]
								  ,[GrossSalary]
								  ,[BasicSalary]
								  ,[HouseRent]
								  ,[MedicalAllowance]
								  ,[Conveyance]
								  ,[FoodAllowance]
								  ,[EntertainmentAllowance]
								  ,[PerDayBasicSalary]
								  ,[LWPFee]
								  ,[AbsentFee]
								  ,[AttendanceBonus]
								  ,[ShiftingBonus]
								  ,[TotalOTHours]
								  ,[OTRate]
								  ,[EmployeeOTRate]
								  ,[TotalOTAmount]
								  ,[CreatedDate]
								  ,[CreatedBy]
								  ,[IsActive]
							  FROM [dbo].[EmployeeJobCardModel]
							  WHERE EmployeeCardId = @employeeCardId 
							  AND CAST(FromDate AS DATE) = @fromDate
							  AND CAST(ToDate AS DATE) = @toDate
							  AND IsActive = 1
					END


					IF(@JobCardName = 'EmployeeJobCard_10PM')
					BEGIN
							SELECT [Id]
								  ,[EmployeeId]
								  ,[Year]
								  ,[Month]
								  ,[MonthName]
								  ,[FromDate]
								  ,[ToDate]
								  ,[CompanyId]
								  ,[CompanyName]
								  ,[CompanyNameInBengali]
								  ,[CompanyAddress]
								  ,[CompanyAddressInBengali]
								  ,[BranchId]
								  ,[BranchName]
								  ,[BranchNameInBengali]
								  ,[BranchUnitId]
								  ,[UnitName]
								  ,[UnitNameInBengali]
								  ,[BranchUnitDepartmentId]
								  ,[DepartmentName]
								  ,[DepartmentNameInBengali]
								  ,[DepartmentSectionId]
								  ,[SectionName]
								  ,[SectionNameInBengali]
								  ,[DepartmentLineId]
								  ,[LineName]
								  ,[LineNameInBengali]
								  ,[EmployeeCardId]
								  ,[EmployeeName]
								  ,[EmployeeNameInBengali]
								  ,[MobileNo]
								  ,[EmployeeTypeId]
								  ,[EmployeeType]
								  ,[EmployeeTypeInBengali]
								  ,[EmployeeGradeId]
								  ,[EmployeeGrade]
								  ,[EmployeeGradeInBengali]
								  ,[EmployeeDesignationId]
								  ,[EmployeeDesignation]
								  ,[EmployeeDesignationInBengali]
								  ,[EmployeeActiveStatusId]
								  ,[EmployeeCategoryId]
								  ,[JoiningDate]
								  ,[QuitDate]
								  ,[TotalDays]
								  ,[WorkingDays]
								  ,[PresentDays]
								  ,[LateDays]
								  ,[OSDDays]
								  ,[AbsentDays]
								  ,[LeaveDays]
								  ,[LWPDays]
								  ,[Holidays]
								  ,[WeekendDays]
								  ,[PayDays]
								  ,[CasualLeave]
								  ,[SickLeave]
								  ,[MaternityLeave]
								  ,[EarnLeave]
								  ,[GrossSalary]
								  ,[BasicSalary]
								  ,[HouseRent]
								  ,[MedicalAllowance]
								  ,[Conveyance]
								  ,[FoodAllowance]
								  ,[EntertainmentAllowance]
								  ,[PerDayBasicSalary]
								  ,[LWPFee]
								  ,[AbsentFee]
								  ,[AttendanceBonus]
								  ,[ShiftingBonus]
								  ,[TotalOTHours]
								  ,[TotalExtraOTHours]
								  ,[TotalWeekendOTHours]
								  ,[TotalHolidayOTHours]
								  ,[OTRate]
								  ,[EmployeeOTRate]
								  ,[TotalOTAmount]
								  ,[TotalExtraOTAmount]
								  ,[TotalWeekendOTAmount]
								  ,[TotalHolidayOTAmount]
								  ,[TotalPenaltyOTHours]
								  ,[TotalPenaltyOTAmount]
								  ,[TotalPenaltyAttendanceDays]
								  ,[TotalPenaltyAbsentFee]
								  ,[TotalPenaltyLeaveDays]
								  ,[TotalPenaltyFinancialAmount]
								  ,[CreatedDate]
								  ,[CreatedBy]
								  ,[IsActive]
							  FROM [dbo].[EmployeeJobCard_10PM]
							  WHERE EmployeeCardId = @employeeCardId 
							  AND CAST(FromDate AS DATE) = @fromDate
							  AND CAST(ToDate AS DATE) = @toDate
							  AND IsActive = 1
					  END


					IF(@JobCardName = 'EmployeeJobCard_10PM_NoWeekend')
					BEGIN
							SELECT [Id]
								  ,[EmployeeId]
								  ,[Year]
								  ,[Month]
								  ,[MonthName]
								  ,[FromDate]
								  ,[ToDate]
								  ,[CompanyId]
								  ,[CompanyName]
								  ,[CompanyNameInBengali]
								  ,[CompanyAddress]
								  ,[CompanyAddressInBengali]
								  ,[BranchId]
								  ,[BranchName]
								  ,[BranchNameInBengali]
								  ,[BranchUnitId]
								  ,[UnitName]
								  ,[UnitNameInBengali]
								  ,[BranchUnitDepartmentId]
								  ,[DepartmentName]
								  ,[DepartmentNameInBengali]
								  ,[DepartmentSectionId]
								  ,[SectionName]
								  ,[SectionNameInBengali]
								  ,[DepartmentLineId]
								  ,[LineName]
								  ,[LineNameInBengali]
								  ,[EmployeeCardId]
								  ,[EmployeeName]
								  ,[EmployeeNameInBengali]
								  ,[MobileNo]
								  ,[EmployeeTypeId]
								  ,[EmployeeType]
								  ,[EmployeeTypeInBengali]
								  ,[EmployeeGradeId]
								  ,[EmployeeGrade]
								  ,[EmployeeGradeInBengali]
								  ,[EmployeeDesignationId]
								  ,[EmployeeDesignation]
								  ,[EmployeeDesignationInBengali]
								  ,[EmployeeActiveStatusId]
								  ,[EmployeeCategoryId]
								  ,[JoiningDate]
								  ,[QuitDate]
								  ,[TotalDays]
								  ,[WorkingDays]
								  ,[PresentDays]
								  ,[LateDays]
								  ,[OSDDays]
								  ,[AbsentDays]
								  ,[LeaveDays]
								  ,[LWPDays]
								  ,[Holidays]
								  ,[WeekendDays]
								  ,[PayDays]
								  ,[CasualLeave]
								  ,[SickLeave]
								  ,[MaternityLeave]
								  ,[EarnLeave]
								  ,[GrossSalary]
								  ,[BasicSalary]
								  ,[HouseRent]
								  ,[MedicalAllowance]
								  ,[Conveyance]
								  ,[FoodAllowance]
								  ,[EntertainmentAllowance]
								  ,[PerDayBasicSalary]
								  ,[LWPFee]
								  ,[AbsentFee]
								  ,[AttendanceBonus]
								  ,[ShiftingBonus]
								  ,[TotalOTHours]
								  ,[TotalExtraOTHours]
								  ,[TotalWeekendOTHours]
								  ,[TotalHolidayOTHours]
								  ,[OTRate]
								  ,[EmployeeOTRate]
								  ,[TotalOTAmount]
								  ,[TotalExtraOTAmount]
								  ,[TotalWeekendOTAmount]
								  ,[TotalHolidayOTAmount]
								  ,[TotalPenaltyOTHours]
								  ,[TotalPenaltyOTAmount]
								  ,[TotalPenaltyAttendanceDays]
								  ,[TotalPenaltyAbsentFee]
								  ,[TotalPenaltyLeaveDays]
								  ,[TotalPenaltyFinancialAmount]
								  ,[CreatedDate]
								  ,[CreatedBy]
								  ,[IsActive]
							  FROM [dbo].[EmployeeJobCard_10PM_NoWeekend]
							  WHERE EmployeeCardId = @employeeCardId 
							  AND CAST(FromDate AS DATE) = @fromDate
							  AND CAST(ToDate AS DATE) = @toDate
							  AND IsActive = 1
					END

					IF(@JobCardName = 'EmployeeJobCard_Original_NoPenalty')
					BEGIN
							SELECT [Id]
								  ,[EmployeeId]
								  ,[Year]
								  ,[Month]
								  ,[MonthName]
								  ,[FromDate]
								  ,[ToDate]
								  ,[CompanyId]
								  ,[CompanyName]
								  ,[CompanyNameInBengali]
								  ,[CompanyAddress]
								  ,[CompanyAddressInBengali]
								  ,[BranchId]
								  ,[BranchName]
								  ,[BranchNameInBengali]
								  ,[BranchUnitId]
								  ,[UnitName]
								  ,[UnitNameInBengali]
								  ,[BranchUnitDepartmentId]
								  ,[DepartmentName]
								  ,[DepartmentNameInBengali]
								  ,[DepartmentSectionId]
								  ,[SectionName]
								  ,[SectionNameInBengali]
								  ,[DepartmentLineId]
								  ,[LineName]
								  ,[LineNameInBengali]
								  ,[EmployeeCardId]
								  ,[EmployeeName]
								  ,[EmployeeNameInBengali]
								  ,[MobileNo]
								  ,[EmployeeTypeId]
								  ,[EmployeeType]
								  ,[EmployeeTypeInBengali]
								  ,[EmployeeGradeId]
								  ,[EmployeeGrade]
								  ,[EmployeeGradeInBengali]
								  ,[EmployeeDesignationId]
								  ,[EmployeeDesignation]
								  ,[EmployeeDesignationInBengali]
								  ,[EmployeeActiveStatusId]
								  ,[EmployeeCategoryId]
								  ,[JoiningDate]
								  ,[QuitDate]
								  ,[TotalDays]
								  ,[WorkingDays]
								  ,[PresentDays]
								  ,[LateDays]
								  ,[OSDDays]
								  ,[AbsentDays]
								  ,[LeaveDays]
								  ,[LWPDays]
								  ,[Holidays]
								  ,[WeekendDays]
								  ,[PayDays]
								  ,[CasualLeave]
								  ,[SickLeave]
								  ,[MaternityLeave]
								  ,[EarnLeave]
								  ,[GrossSalary]
								  ,[BasicSalary]
								  ,[HouseRent]
								  ,[MedicalAllowance]
								  ,[Conveyance]
								  ,[FoodAllowance]
								  ,[EntertainmentAllowance]
								  ,[PerDayBasicSalary]
								  ,[LWPFee]
								  ,[AbsentFee]
								  ,[AttendanceBonus]
								  ,[ShiftingBonus]
								  ,[TotalOTHours]
								  ,[TotalExtraOTHours]
								  ,[TotalWeekendOTHours]
								  ,[TotalHolidayOTHours]
								  ,[OTRate]
								  ,[EmployeeOTRate]
								  ,[TotalOTAmount]
								  ,[TotalExtraOTAmount]
								  ,[TotalWeekendOTAmount]
								  ,[TotalHolidayOTAmount]
								  ,[TotalPenaltyOTHours]
								  ,[TotalPenaltyOTAmount]
								  ,[TotalPenaltyAttendanceDays]
								  ,[TotalPenaltyAbsentFee]
								  ,[TotalPenaltyLeaveDays]
								  ,[TotalPenaltyFinancialAmount]
								  ,[CreatedDate]
								  ,[CreatedBy]
								  ,[IsActive]
							  FROM [dbo].[EmployeeJobCard_NoPenalty]
							  WHERE EmployeeCardId = @employeeCardId 
							  AND CAST(FromDate AS DATE) = @fromDate
							  AND CAST(ToDate AS DATE) = @toDate
							  AND IsActive = 1
					END

					IF(@JobCardName = 'EmployeeJobCard_Original_NoWeekend')
					BEGIN
							SELECT [Id]
								  ,[EmployeeId]
								  ,[Year]
								  ,[Month]
								  ,[MonthName]
								  ,[FromDate]
								  ,[ToDate]
								  ,[CompanyId]
								  ,[CompanyName]
								  ,[CompanyNameInBengali]
								  ,[CompanyAddress]
								  ,[CompanyAddressInBengali]
								  ,[BranchId]
								  ,[BranchName]
								  ,[BranchNameInBengali]
								  ,[BranchUnitId]
								  ,[UnitName]
								  ,[UnitNameInBengali]
								  ,[BranchUnitDepartmentId]
								  ,[DepartmentName]
								  ,[DepartmentNameInBengali]
								  ,[DepartmentSectionId]
								  ,[SectionName]
								  ,[SectionNameInBengali]
								  ,[DepartmentLineId]
								  ,[LineName]
								  ,[LineNameInBengali]
								  ,[EmployeeCardId]
								  ,[EmployeeName]
								  ,[EmployeeNameInBengali]
								  ,[MobileNo]
								  ,[EmployeeTypeId]
								  ,[EmployeeType]
								  ,[EmployeeTypeInBengali]
								  ,[EmployeeGradeId]
								  ,[EmployeeGrade]
								  ,[EmployeeGradeInBengali]
								  ,[EmployeeDesignationId]
								  ,[EmployeeDesignation]
								  ,[EmployeeDesignationInBengali]
								  ,[EmployeeActiveStatusId]
								  ,[EmployeeCategoryId]
								  ,[JoiningDate]
								  ,[QuitDate]
								  ,[TotalDays]
								  ,[WorkingDays]
								  ,[PresentDays]
								  ,[LateDays]
								  ,[OSDDays]
								  ,[AbsentDays]
								  ,[LeaveDays]
								  ,[LWPDays]
								  ,[Holidays]
								  ,[WeekendDays]
								  ,[PayDays]
								  ,[CasualLeave]
								  ,[SickLeave]
								  ,[MaternityLeave]
								  ,[EarnLeave]
								  ,[GrossSalary]
								  ,[BasicSalary]
								  ,[HouseRent]
								  ,[MedicalAllowance]
								  ,[Conveyance]
								  ,[FoodAllowance]
								  ,[EntertainmentAllowance]
								  ,[PerDayBasicSalary]
								  ,[LWPFee]
								  ,[AbsentFee]
								  ,[AttendanceBonus]
								  ,[ShiftingBonus]
								  ,[TotalOTHours]
								  ,[TotalExtraOTHours]
								  ,[TotalWeekendOTHours]
								  ,[TotalHolidayOTHours]
								  ,[OTRate]
								  ,[EmployeeOTRate]
								  ,[TotalOTAmount]
								  ,[TotalExtraOTAmount]
								  ,[TotalWeekendOTAmount]
								  ,[TotalHolidayOTAmount]
								  ,[TotalPenaltyOTHours]
								  ,[TotalPenaltyOTAmount]
								  ,[TotalPenaltyAttendanceDays]
								  ,[TotalPenaltyAbsentFee]
								  ,[TotalPenaltyLeaveDays]
								  ,[TotalPenaltyFinancialAmount]
								  ,[CreatedDate]
								  ,[CreatedBy]
								  ,[IsActive]
							  FROM [dbo].[EmployeeJobCard_Original_NoWeekend]
							  WHERE EmployeeCardId = @employeeCardId 
							  AND CAST(FromDate AS DATE) = @fromDate
							  AND CAST(ToDate AS DATE) = @toDate
							  AND IsActive = 1
					END

END