//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_StorePurchaseRequisitionHistory
    {
        public int StorePurchaseRequisitionHistoryId { get; set; }
        public int StorePurchaseRequisitionId { get; set; }
        public System.Guid SubmittedTo { get; set; }
        public Nullable<System.Guid> SubmittedBy { get; set; }
        public System.Guid PreparedBy { get; set; }
        public int ApprovalStatusId { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Inventory_ApprovalStatus Inventory_ApprovalStatus { get; set; }
        public virtual Inventory_StorePurchaseRequisition Inventory_StorePurchaseRequisition { get; set; }
    }
}
