//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_MaterialIssueRequisition
    {
        public Inventory_MaterialIssueRequisition()
        {
            this.Inventory_MaterialIssue = new HashSet<Inventory_MaterialIssue>();
            this.Inventory_MaterialIssueRequisitionDetail = new HashSet<Inventory_MaterialIssueRequisitionDetail>();
        }
        public int MaterialIssueRequisitionId { get; set; }
        public string IssueReceiveNoteNo { get; set; }
        public Nullable<System.DateTime> IssueReceiveNoteDate { get; set; }
        public int BranchUnitDepartmentId { get; set; }
        public Nullable<int> DepartmentSectionId { get; set; }
        public Nullable<int> DepartmentLineId { get; set; }
        public DateTime? SendingDate { get; set; }
        public System.Guid PreparedBy { get; set; }
        public System.Guid SubmittedTo { get; set; }
        public bool IsSentToStore { get; set; }
        public bool IsModifiedByStore { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Inventory_MaterialIssue> Inventory_MaterialIssue { get; set; }
        public virtual ICollection<Inventory_MaterialIssueRequisitionDetail> Inventory_MaterialIssueRequisitionDetail { get; set; }
    }
}
