//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using SCERP.Model.CommonModel;

namespace SCERP.Model.InventoryModel
{
   
    public partial class Inventory_ReDyeingFabricReceive
    {
        public Inventory_ReDyeingFabricReceive()
        {
            this.Inventory_ReDyeingFabricReceiveDetail = new HashSet<Inventory_ReDyeingFabricReceiveDetail>();
        }
        public string RefNo { get; set; }
        [Required]
        public string CompId { get; set; }

        public long ReDyeingFabricReceiveId { get; set; }
        [Required]
        public long PartyId { get; set; }
        [Required]
        public System.DateTime? ChallanDate { get; set; }
        [Required]
        public System.DateTime ReceiveDate { get; set; }
        public string GatEntryNo { get; set; }
        [Required]
        public string ChallanNo { get; set; }
        public string Remarks { get; set; }
    
        public virtual Party Party { get; set; }
        public virtual ICollection<Inventory_ReDyeingFabricReceiveDetail> Inventory_ReDyeingFabricReceiveDetail { get; set; }
    }
}
