//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    public partial class Inventory_StorePurchaseRequisitionDetail
    {
        public int StorePurchaseRequisitionDetailId { get; set; }
        public int StorePurchaseRequisitionId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int ItemId { get; set; }
        public string Description { get; set; }
        public Nullable<int> SizeId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> OriginId { get; set; }
       [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public decimal Quantity { get; set; }
         public bool IsReceived { get; set; }
   
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DesiredDate { get; set; }
          [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string FunctionalArea { get; set; }
          [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string SuppliedUptoDate { get; set; }
          [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string StockInHand { get; set; }
          [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Nullable<decimal> LastUnitPrice { get; set; }
        public string EstimatedYearlyRequirement { get; set; }
        public Nullable<decimal> ModifiedRequiredQuantity { get; set; }
        public Nullable<decimal> ApprovedQuantity { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public int ApprovalStatusId { get; set; }
        public string RemarksOfRequisitionApprovalPerson { get; set; }
        public string Quotation { get; set; }
        public decimal PresentRate { get; set; }
        public string ApprovedPurchase { get; set; }
        public string RemarksOfPurchaseApprovalPerson { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Inventory_ApprovalStatus Inventory_ApprovalStatus { get; set; }
        public virtual Inventory_Brand Inventory_Brand { get; set; }
        public virtual Country Country { get; set; }
       // public virtual MeasurementUnit MeasurementUnit { get; set; }
        public Inventory_Item Inventory_Item { get; set; }
        public virtual Inventory_Size Inventory_Size { get; set; }
        public virtual Inventory_StorePurchaseRequisition Inventory_StorePurchaseRequisition { get; set; }
    }
}
