//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Model.CommonModel;

namespace SCERP.Model.InventoryModel
{
    using System;
    using System.Collections.Generic;

    public partial class Inventory_GreyIssue
    {
        public Inventory_GreyIssue()
        {
            this.Inventory_GreyIssueDetail = new HashSet<Inventory_GreyIssueDetail>();
        }

        public long GreyIssueId { get; set; }
        public string RefId { get; set; }
        [Required]
        public long PartyId { get; set; }
        [Required]
        public string ChallanNo { get; set; }
        [Required]
        public Nullable<System.DateTime> ChallanDate { get; set; }
        [Required]
        public string Through { get; set; }

        public string VheicalNo { get; set; }
        public string Mobile { get; set; }

        public string Remarks { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public string CompId { get; set; }
        public bool IsApproved { get; set; }
        public string Posted { get; set; }
        public long? VoucherMasterId { get; set; }
        public Nullable<System.Guid> ApprovedBy { get; set; }
        public Nullable<System.Guid> AuditeBy { get; set; }
        public Nullable<bool> IsAudited { get; set; }

        public virtual ICollection<Inventory_GreyIssueDetail> Inventory_GreyIssueDetail { get; set; }
        public virtual Party Party { get; set; }
    }
}
