//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_StoreLedger
    {
        public int StoreLedgerId { get; set; }
        public int ItemId { get; set; }
        public Nullable<int> SizeId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> OriginId { get; set; }
        public Nullable<int> GoodsReceivingNoteId { get; set; }
        public Nullable<int> MaterialIssueId { get; set; }
        public string TransactionType { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public decimal Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Amount { get; set; }
        public int CurrencyId { get; set; }

        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
        public virtual Inventory_Brand Inventory_Brand { get; set; }
        public virtual Inventory_Size Inventory_Size { get; set; }
        public virtual Inventory_Item Inventory_Item { get; set; }
        public virtual Inventory_GoodsReceivingNote Inventory_GoodsReceivingNote { get; set; }
        public virtual Inventory_MaterialIssue Inventory_MaterialIssue { get; set; }
        public virtual Currency Currency { get; set; }
   
        public virtual Country Country { get; set; }

    }
}
