//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using SCERP.Model.CommonModel;

namespace SCERP.Model.InventoryModel
{
   
    
    public partial class Inventory_RedyeingFabricIssue
    {
        public Inventory_RedyeingFabricIssue()
        {
            this.Inventory_RedyeingFabricIssueDetail = new HashSet<Inventory_RedyeingFabricIssueDetail>();
        }
    
        public long RedyeingFabricIssueId { get; set; }
        [Required]
        public string RefNo { get; set; }
        [Required]
        public string CompId { get; set; }
        public long PartyId { get; set; }
        [Required]
        public string ChallanNo { get; set; }
        [Required]
        public System.DateTime ChallanDate { get; set; }
        public string DriverName { get; set; }
        public string DriverPhone { get; set; }
        public string VehicleType { get; set; }
        public string Remarks { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<System.Guid> ApprovedBy { get; set; }
    
        public virtual Party Party { get; set; }
        public virtual ICollection<Inventory_RedyeingFabricIssueDetail> Inventory_RedyeingFabricIssueDetail { get; set; }
    }
}
