//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_MaterialRequisitionDetail
    {
        public int MaterialRequisitionDetailId { get; set; }
        public int MaterialRequisitionId { get; set; }
        [Required(ErrorMessage =CustomErrorMessage.RequiredErrorMessage)]
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public string Size { get; set; }
        public string Brand { get; set; }
        public string Origin { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [Range(0, Double.MaxValue, ErrorMessage = "Enter a value between 1 and 1000")]
        public decimal RequiredQuantity { get; set; }
        public string MeasurementUnit { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Nullable<System.DateTime> DesiredDate { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string FunctionalArea { get; set; }
        public Nullable<decimal> ApprovedQuantity { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
        public virtual Inventory_MaterialRequisition Inventory_MaterialRequisition { get; set; }
    }
}
