//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Inventory_ApprovalStatus : SearchModel<Inventory_ApprovalStatus>
    {
        public Inventory_ApprovalStatus()
        {
            this.Inventory_StorePurchaseRequisition = new HashSet<Inventory_StorePurchaseRequisition>();
            this.Inventory_StorePurchaseRequisitionDetail = new HashSet<Inventory_StorePurchaseRequisitionDetail>();
            this.Inventory_StorePurchaseRequisitionHistory = new HashSet<Inventory_StorePurchaseRequisitionHistory>();
        }
    
        public int ApprovalStatusId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [Remote("CheckApprovalStatus", "InventoryApprovalStatus", AdditionalFields = "ApprovalStatusId", ErrorMessage = "ApprovalStatus already exist")]
        public string StatusName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Inventory_StorePurchaseRequisition> Inventory_StorePurchaseRequisition { get; set; }
        public virtual ICollection<Inventory_StorePurchaseRequisitionDetail> Inventory_StorePurchaseRequisitionDetail { get; set; }
        public virtual ICollection<Inventory_StorePurchaseRequisitionHistory> Inventory_StorePurchaseRequisitionHistory { get; set; }
    }
}
