//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SCERP.Model.InventoryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_ReDyeingFabricReceiveDetail
    {
        public long ReDyeingFabricReceiveDetailId { get; set; }
        public long ReDyeingFabricReceiveId { get; set; }
        public long BatchId { get; set; }

        public long BatchDetailId { get; set; }
        public double RQty { get; set; }
    
        public virtual Inventory_ReDyeingFabricReceive Inventory_ReDyeingFabricReceive { get; set; }
    }
}
