//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_ItemStoreDetail
    {
        public long ItemStoreDetailId { get; set; }
        public long ItemStoreId { get; set; }
        public int ItemId { get; set; }
        public string Specification { get; set; }
        public decimal SuppliedQuantity { get; set; }
        public decimal ReceivedQuantity { get; set; }
       // public int UnitId { get; set; }
        public decimal UnitPrice { get; set; }
        public int? BrandId { get; set; }
        public int? OriginId { get; set; }
        public int? SizeId { get; set; }
        public int CurrencyId { get; set; }
              [DataType(DataType.Date)]
        public Nullable<System.DateTime> ManufacturingDate { get; set; }
              [DataType(DataType.Date)]
        public Nullable<System.DateTime> ExpirationDate { get; set; }
     
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
        public Inventory_Size Inventory_Size { get; set; }
        public Country Country { get; set; }
        public Inventory_Brand Inventory_Brand { get; set; }
        public virtual Inventory_Item Inventory_Item { get; set; }
        public virtual Inventory_ItemStore Inventory_ItemStore { get; set; }
      //  public virtual MeasurementUnit MeasurementUnit { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
