//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Size:SearchModel<Inventory_Size>
    {
        
        public Inventory_Size()
        {

            this.Inventory_ItemStoreDetail = new HashSet<Inventory_ItemStoreDetail>();
            this.Inventory_StoreLedger=new HashSet<Inventory_StoreLedger>();
            this.Inventory_MaterialIssueDetail = new HashSet<Inventory_MaterialIssueDetail>();
            Inventory_StorePurchaseRequisitionDetail = new HashSet<Inventory_StorePurchaseRequisitionDetail>();
        }
    
        public int SizeId { get; set; }
        [Remote("CheckSize", "Size", AdditionalFields = "SizeId", ErrorMessage = "Size already exist")]
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
        public virtual ICollection<Inventory_ItemStoreDetail> Inventory_ItemStoreDetail { get; set; }
        public virtual ICollection<Inventory_StoreLedger> Inventory_StoreLedger { get; set; }
        public virtual ICollection<Inventory_MaterialIssueDetail> Inventory_MaterialIssueDetail { get; set; }
        public virtual ICollection<Inventory_StorePurchaseRequisitionDetail> Inventory_StorePurchaseRequisitionDetail { get; set; }
    }
}
