//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using SCERP.Common;

namespace SCERP.Model
{
    public partial class Inventory_AuthorizedPerson : SearchModel<Inventory_AuthorizedPerson>
    {
        public int AuthorizedPersonId { get; set; }
        public int ProcessId { get; set; }

    
        public int ProcessTypeId { get; set; }
        public string ProcessName { get; set; }
        public string ProcessTypeName { get; set; }
        [Required(ErrorMessage =CustomErrorMessage.RequiredErrorMessage)]
    
        public string EmployeeCardId { get; set; }
        public Guid EmployeeId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
