//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Model.Production;

namespace SCERP.Model.InventoryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_FinishFabStore
    {
        public Inventory_FinishFabStore()
        {
            this.Inventory_FinishFabDetailStore = new HashSet<Inventory_FinishFabDetailStore>();
        }
    
        public long FinishFabStoreId { get; set; }
        public string FinishFabRefId { get; set; }
        [Required]
        public string InvoiceNo { get; set; }
        [Required]
        public Nullable<System.DateTime> InvoiceDate { get; set; }
         [Required]
        public string RcvRegNo { get; set; }
        public string GateEntryNo { get; set; }
        public Nullable<System.DateTime> GateEntryDate { get; set; }
        [Required]
        public long DyeingSpChallanId { get; set; }
        public string Remarks { get; set; }
        public string CompId { get; set; }
        public System.Guid CratedBy { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public virtual PROD_DyeingSpChallan PROD_DyeingSpChallan { get; set; }
        public virtual ICollection<Inventory_FinishFabDetailStore> Inventory_FinishFabDetailStore { get; set; }
    }
}
