//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_QualityCertificateDetail
    {
        public int QualityCertificateDetailId { get; set; }
        public int QualityCertificateId { get; set; }
        public int ItemId { get; set; }
        public decimal CorrectQuantity { get; set; }
        public decimal RejectedQuantity { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Inventory_Item Inventory_Item { get; set; }
        public virtual Inventory_QualityCertificate Inventory_QualityCertificate { get; set; }
    }
}
