//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model.InventoryModel
{
   
    
    public partial class Inventory_RedyeingFabricIssueDetail
    {
        public long RedyeingFabricIssueDetailId { get; set; }
        public long RedyeingFabricIssueId { get; set; }
        public long BatchId { get; set; }
        public long BatchDetailId { get; set; }
        public double ReprocessQty { get; set; }
        public double FinishQty { get; set; }
        public int NoRole { get; set; }
        public string Remarks { get; set; }
    
        public virtual Inventory_RedyeingFabricIssue Inventory_RedyeingFabricIssue { get; set; }
    }
}
