//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Inventory_PurchaseType : SearchModel<Inventory_PurchaseType>
    {
        public Inventory_PurchaseType()
        {
            this.Inventory_StorePurchaseRequisition = new HashSet<Inventory_StorePurchaseRequisition>();
        }
    
        public int PurchaseTypeId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
       [Remote("CheckPurchaseType", "PurchaseType", AdditionalFields = "PurchaseTypeId", ErrorMessage = "PurchaseType already exist")]
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Inventory_StorePurchaseRequisition> Inventory_StorePurchaseRequisition { get; set; }
    }
}
