//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Inventory_StorePurchaseRequisition
    {
        public Inventory_StorePurchaseRequisition()
        {
            this.Inventory_StorePurchaseRequisitionDetail = new HashSet<Inventory_StorePurchaseRequisitionDetail>();
            this.Inventory_StorePurchaseRequisitionHistory = new HashSet<Inventory_StorePurchaseRequisitionHistory>();
        }
    
        public int StorePurchaseRequisitionId { get; set; }
        public int MaterialRequisitionId { get; set; }
        public string RequisitionNo { get; set; }
        public System.DateTime RequisitionDate { get; set; }
        public int PurchaseTypeId { get; set; }
        public int RequisitionTypeId { get; set; }
        public Nullable<System.Guid> SubmittedTo { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public System.Guid PreparedBy { get; set; }
        public int ApprovalStatusId { get; set; }
        public int ProcessId { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Inventory_ApprovalStatus Inventory_ApprovalStatus { get; set; }
        public virtual Inventory_MaterialRequisition Inventory_MaterialRequisition { get; set; }
        public virtual Inventory_PurchaseType Inventory_PurchaseType { get; set; }
        public virtual Inventory_RequsitionType Inventory_RequsitionType { get; set; }
        public virtual ICollection<Inventory_StorePurchaseRequisitionDetail> Inventory_StorePurchaseRequisitionDetail { get; set; }
        public virtual ICollection<Inventory_StorePurchaseRequisitionHistory> Inventory_StorePurchaseRequisitionHistory { get; set; }
    }
}
