//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Inventory_QualityCertificate : SearchModel<Inventory_QualityCertificate>
    {
        public Inventory_QualityCertificate()
        {
            this.Inventory_QualityCertificateDetail = new HashSet<Inventory_QualityCertificateDetail>();
            this.Inventory_GoodsReceivingNote=new Collection<Inventory_GoodsReceivingNote>();
        }
        public int QualityCertificateId { get; set; }
        public long ItemStoreId { get; set; }
        public bool? IsGrnConverted { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string QCReferenceNo { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> SendingDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
        public virtual Inventory_ItemStore Inventory_ItemStore { get; set; }
        public virtual ICollection<Inventory_GoodsReceivingNote> Inventory_GoodsReceivingNote { get; set; }
        public virtual ICollection<Inventory_QualityCertificateDetail> Inventory_QualityCertificateDetail { get; set; }
    }
}
