//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model.InventoryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_GreyIssueDetail
    {
        public long GreyIssueDetailId { get; set; }
        public long GreyIssueId { get; set; }
        public string ProgramRegId { get; set; }
        public string ItemCode { get; set; }
        public string SizeRefId { get; set; }
        public string ColorRefId { get; set; }
        public string FinishSizeRefId { get; set; }
        public string StLength { get; set; }
        public string GSM { get; set; }
        public double Qty { get; set; }
        public int RollQty { get; set; }
        public virtual Inventory_GreyIssue Inventory_GreyIssue { get; set; }
    }
}
