//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Data.Entity.Core.Objects.DataClasses;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Inventory_Item : SearchModel<Inventory_Item>
    {
        public Inventory_Item()
        {
            this.Inventory_StoreLedger=new HashSet<Inventory_StoreLedger>();
            this.Inventory_ItemLedger = new HashSet<Inventory_ItemLedger>();
            this.Inventory_ItemStoreDetail = new HashSet<Inventory_ItemStoreDetail>();
            this.Inventory_QualityCertificateDetail = new HashSet<Inventory_QualityCertificateDetail>();
            this.Inventory_StorePurchaseRequisitionDetail=new HashSet<Inventory_StorePurchaseRequisitionDetail>();
            this.Inventory_MaterialIssueDetail = new HashSet<Inventory_MaterialIssueDetail>();
        }
    
        public int ItemId { get; set; }
        public string CompId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string ItemName { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string ItemCode { get; set; }

        public int SubGroupId { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int? MeasurementUinitId{ get; set; }
         [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public decimal? ReorderLevel  { get; set; }
        public int? GenericNameId { get; set; }
        public int? ItemType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
        public virtual ICollection<Inventory_StoreLedger> Inventory_StoreLedger { get; set; }
        public virtual ICollection<Inventory_MaterialIssueDetail> Inventory_MaterialIssueDetail { get; set; }
        public virtual Inventory_SubGroup Inventory_SubGroup { get; set; }
        public virtual ICollection<Inventory_ItemLedger> Inventory_ItemLedger { get; set; }
        public virtual ICollection<Inventory_ItemStoreDetail> Inventory_ItemStoreDetail { get; set; }
        public virtual ICollection<Inventory_QualityCertificateDetail> Inventory_QualityCertificateDetail { get; set; }
        public virtual ICollection<Inventory_StorePurchaseRequisitionDetail> Inventory_StorePurchaseRequisitionDetail { get; set; }
    }
}
