//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_MaterialIssue
    {
        public Inventory_MaterialIssue()
        {
            this.Inventory_StoreLedger = new HashSet<Inventory_StoreLedger>();
            this.Inventory_MaterialIssueDetail = new HashSet<Inventory_MaterialIssueDetail>();
        }
        public int MaterialIssueId { get; set; }
        public int MaterialIssueRequisitionId { get; set; }
        public string IssueReceiveNo { get; set; }
        public Nullable<System.DateTime> IssueReceiveDate { get; set; }
        public System.Guid PreparedByStore { get; set; }
        public string BtRefNo { get; set; }
        public int IType { get; set; }
        public string Note { get; set; }
        public int? SupplierId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public int? ToppingType { get; set; }
        public bool IsActive { get; set; }
        public int? MachineId { get; set; }
        public double? Quantity { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Inventory_StoreLedger> Inventory_StoreLedger { get; set; }
        public virtual Inventory_MaterialIssueRequisition Inventory_MaterialIssueRequisition { get; set; }
        public virtual ICollection<Inventory_MaterialIssueDetail> Inventory_MaterialIssueDetail { get; set; }
    }
}
