//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SCERP.Model.Production;

namespace SCERP.Model.InventoryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_FinishFabDetailStore
    {
        public long FinishFabDetailSotreId { get; set; }
        public long FinishFabStoreId { get; set; }
        public long BatchId { get; set; }
        public long BatchDetailId { get; set; }
        public double RcvQty { get; set; }
        public double RejQty { get; set; }
        public string Remarks { get; set; }
        public string CompId { get; set; }
        public double GreyWt { get; set; }
        public double? CcuffQty { get; set; }
        
        public virtual Inventory_FinishFabStore Inventory_FinishFabStore { get; set; }
        public virtual Pro_Batch Pro_Batch { get; set; }
        public virtual PROD_BatchDetail PROD_BatchDetail { get; set; }
    }
}
