//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_GoodsReceivingNote
    {
        public Inventory_GoodsReceivingNote()
        {
            this.Inventory_StoreLedger = new HashSet<Inventory_StoreLedger>();
        }
        public int GoodsReceivingNotesId { get; set; }
        public string GRNNumber { get; set; }
        public int QualityCertificateId { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public System.DateTime? GRNDate { get; set; }
        public string Description { get; set; }
        public bool IsSendToStoreLedger { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
        public decimal? DeductionAmt{ get; set; }
        public bool? IsApproved { get; set; }
        public Guid? AppBy { get; set; }
        public virtual ICollection<Inventory_StoreLedger> Inventory_StoreLedger { get; set; }
        public virtual Inventory_QualityCertificate Inventory_QualityCertificate { get; set; }
    }
}
