//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Inventory_ItemStore : ProSearchModel<Inventory_ItemStore>
    {
        public Inventory_ItemStore()
        {
            this.Inventory_ItemStoreDetail = new HashSet<Inventory_ItemStoreDetail>();
            this.Inventory_QualityCertificate = new HashSet<Inventory_QualityCertificate>();
        }

        public long ItemStoreId { get; set; }
        public bool IsProcessRequsition { get; set; }
        [Required]
        public int ReceiveType { get; set; }
        [DisplayName("Req.No")]
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string RequisitionNo { get; set; }
        [DisplayName("LC No")]
        public string LCNo { get; set; }
        [DisplayName("Invoice No")]
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string InvoiceNo { get; set; }
        [DisplayName("Gate entry")]
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string GateEntry { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [DisplayName("Gate entry date")]
        public DateTime? GateEntryDate { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [DisplayName("Invoice date")]
        public DateTime? InvoiceDate { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Nullable<int> SupplierId { get; set; }
        [DisplayName("Ref. Person")]
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Guid? PurchaseReferencePerson { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [DisplayName("Received date")]
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        [DisplayName("Received Reg. No")]
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string ReceivedRegisterNo { get; set; }
        public byte QCStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        [Required(ErrorMessage =@"Required")]
        public string SuppliedStatus { get; set; }
        public bool IsActive { get; set; }
        [Required(ErrorMessage = "Required")]
        public Guid? Requisitor { get; set; }
        public virtual ICollection<Inventory_ItemStoreDetail> Inventory_ItemStoreDetail { get; set; }
        public virtual ICollection<Inventory_QualityCertificate> Inventory_QualityCertificate { get; set; }
        public virtual Mrc_SupplierCompany Mrc_SupplierCompany { get; set; }

    }
}
