//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_MaterialIssueRequisitionDetail
    {
        public int MaterialIssueRequisitionDetailId { get; set; }
        public int MaterialIssueRequisitionId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public DateTime? DesiredDate { get; set; }

        public string Machine { get; set; }
        public string Size { get; set; }
        public string Brand { get; set; }
        public string Origin { get; set; }
         [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
         [Range(0,Double.MaxValue)]
        public decimal RequiredQuantity { get; set; }
          [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string FunctionalArea { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public virtual Inventory_MaterialIssueRequisition Inventory_MaterialIssueRequisition { get; set; }
        public bool IsActive { get; set; }
        public string MeasurementUnit { get; set; }
    }
}
