//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VInventoryItemStore
    {
 
        public long ItemStoreId { get; set; }
        public string RequisitionNo { get; set; }
        public string GateEntry { get; set; }
        public DateTime? GateEntryDate { get; set; }
        public string LCNo { get; set; }
        public string InvoiceNo { get; set; }
        public DateTime? InvoiceDate { get; set; }
        public int ReceiveType { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string ReceivedRegisterNo { get; set; }
        public byte QCStatus { get; set; }
   
        public string SupplierCompanyName { get; set; }
        public string SupplierCode { get; set; }
        public string PurchaseReferencePersonName { get; set; }
        public System.Guid EmployeeId { get; set; }
        public bool IsActive { get; set; }
    }
}
