//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class VMaterialIssue : ProSearchModel<VMaterialIssue>
    {
        public int MaterialIssueId { get; set; }
        public int MaterialIssueRequisitionId { get; set; }
        public string StoreEmployeeName { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string PreparedByEmployeeName { get; set; }
        public string IssueReceiveNo { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage =CustomErrorMessage.RequiredErrorMessage)]

        public Nullable<System.DateTime> IssueReceiveDate { get; set; }
        public System.Guid PreparedByStore { get; set; }
        public System.Guid PreparedBy { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string BtRefNo { get; set; }
        public string BatchNo { get; set; }
        public string PartyName { get; set; }
        public int IType { get; set; }
        public string Note { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string IssueReceiveNoteNo { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Nullable<System.DateTime> IssueReceiveNoteDate { get; set; }
        public int BranchUnitDepartmentId { get; set; }
        public Nullable<int> DepartmentSectionId { get; set; }
        public Nullable<int> DepartmentLineId { get; set; }
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public int BranchId { get; set; }
        public int BranchUnitId { get; set; }
        public string BranchName { get; set; }
        public string UnitName { get; set; }
        public string DepartmentName { get; set; }
        public string SectionName { get; set; }
        public string LineName { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int? ToppingType { get; set; }

        public double? Quantity { get; set; }
        public int? MachineId { get; set; }
        public string MachineName { get; set; }
    }
}
