//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class VMaterialIssueRequisition : SearchModel<VMaterialIssueRequisition>
    {
        public string SubmittedToEmployeeName { get; set; }
        public System.Guid SubmittedTo { get; set; }
        public string PreparedByEmployeeName { get; set; }
        public System.Guid PreparedBy { get; set; }
        public System.Guid? CreatedBy { get; set; }
        public bool IsModifiedByStore { get; set; }
        public bool IsSentToStore { get; set; }
        public int MaterialIssueRequisitionId { get; set; }
        public Nullable<System.DateTime> SendingDate { get; set; }
        public string Remarks { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string IssueReceiveNoteNo { get; set; }
  
        [DataType(DataType.Date)]
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]

        public Nullable<System.DateTime> IssueReceiveNoteDate { get; set; }
        public int BranchUnitDepartmentId { get; set; }
        public Nullable<int> DepartmentSectionId { get; set; }
        public Nullable<int> DepartmentLineId { get; set; }
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public int BranchId { get; set; }
        public int BranchUnitId { get; set; }
        public string BranchName { get; set; }
        public string UnitName { get; set; }
        public string DepartmentName { get; set; }
        public string SectionName { get; set; }
        public string LineName { get; set; }
    }
}
