//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    public partial class VMaterialIssueDetail
    {
        public int MaterialIssueDetailId { get; set; }
        public int MaterialIssueId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int ItemId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string ItemName { get; set; }
        public string SizeName { get; set; }
        public Nullable<int> SizeId { get; set; }
        public string BrandName { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string OriginName { get; set; }
        public Nullable<int> OriginId { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Nullable<System.DateTime> TransactionDate { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public decimal? RequiredQuantity { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public decimal? IssuedQuantity { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public decimal? IssuedItemRate { get; set; }
        public decimal? StockInHand { get; set; }
        public Nullable<int> MachineId { get; set; }
        public string MachineName { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int MeasurementUnitId { get; set; }
        public string MeasurementUnitName { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int CurrencyId { get; set; }
        public string CurrencyName { get; set; }
        public string Remarks { get; set; }
        
    }
}
