//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class VQualityCertificateDetail
    {
        public long ItemStoreId { get; set; }
        public int QualityCertificateId { get; set; }
        public int QualityCertificateDetailId { get; set; }
        public string ItemName { get; set; }
        public int ItemId { get; set; }
        public int CurrencyId { get; set; }
        public int MeasurementUnitId { get; set; }
        public long ItemStoreDetailId { get; set; }
        public string Remarks { get; set; }
        public string ItemCode { get; set; }
        public string Specification { get; set; }
        public decimal SuppliedQuantity { get; set; }
        public decimal ReceivedQuantity { get; set; }
        public decimal CorrectQuantity { get; set; }
        public decimal RejectedQuantity { get; set; }
        public decimal UnitPrice { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> OriginId { get; set; }
        public Nullable<int> SizeId { get; set; }
        public string SizeName { get; set; }
        public string BrandName { get; set; }
        public string CountryName { get; set; }
        public Nullable<System.DateTime> ManufacturingDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string CurrencyCode { get; set; }
        public string CureencyName { get; set; }
        public string UnitName { get; set; }
        public decimal Amount { get { return UnitPrice * CorrectQuantity; } }
    }
}
