//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    public partial class VQualityCertificate : ProSearchModel<VQualityCertificate>
    {
        public long ItemStoreId { get; set; }
         [DisplayName("G.E.No")]
        public string GateEntry { get; set; }
         public Nullable<int> ReceiveType { get; set; }
         public bool? IsGrnConverted { get; set; }
        public Nullable<System.DateTime> GateEntryDate { get; set; }
             [DisplayName("Req.No")]
        public string RequisitionNo { get; set; }
        public string LCNo { get; set; }
        [DisplayName("Invoice No")]
        public string InvoiceNo { get; set; }
     
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
         [DisplayName("Rec.Reg.No")]
        public string ReceivedRegisterNo { get; set; }
        public byte QCStatus { get; set; }
        public string SupplierCompanyName { get; set; }
        public string SupplierCode { get; set; }
        public string PurchaseReferencePersonName { get; set; }
        public System.Guid EmployeeId { get; set; }
        public bool IsActive { get; set; }
        [DisplayName("Qc.Ref.No")]
        public string QCReferenceNo { get; set; }
        [DataType(DataType.Date)]
        [DisplayName("Sending date")]
        public Nullable<System.DateTime> SendingDate { get; set; }
        public int QualityCertificateId { get; set; }
    }
}
