//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using SCERP.Common;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class VStorePurchaseRequisition : ProSearchModel<VStorePurchaseRequisition>
    {
        public int StorePurchaseRequisitionId { get; set; }
        public int MaterialRequisitionId { get; set; }
        public int ApprovalStatusId { get; set; }
        public int RequisitionTypeId { get; set; }
        public int ProcessId { get; set; }
        public int PurchaseTypeId { get; set; }
 
        public string RequisitionNo { get; set; }
       [DataType(DataType.Date)]
        public System.DateTime? RequisitionDate { get; set; }
        public string SubmittedToEmployeeName { get; set; }
        public Guid?SubmittedTo { get; set; }
        public string ModifiedByEmployeeName { get; set; }
        public Guid? ModifiedBy { get; set; }
        [Required(ErrorMessage =CustomErrorMessage.RequiredErrorMessage)]
        public string PreparedByEmployeeName { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public System.Guid PreparedBy { get; set; }
        public string RequsitionTypeTitle { get; set; }
        public string PurchaseTypeTitle { get; set; }
        [DataType(DataType.Date)]
    
        public DateTime? ApprovalDate { get; set; }
        public string ApprovalStausName { get; set; }
        public string Remarks { get; set; }
       [Remote("ExistReqNotNo", "StorePurchase")]
        public string RequisitionNoteNo { get; set; }
        [DataType(DataType.Date)]
       
        public System.DateTime? RequisitionNoteDate { get; set; }
        public int BranchUnitDepartmentId { get; set; }
        public int BranchUnitId{ get; set; }
        public int? DepartmentSectionId { get; set; }
        public int? DepartmentLineId { get; set; }
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public int BranchId { get; set; }
  
        public string BranchName { get; set; }
        public string UnitName { get; set; }
        public string DepartmentName { get; set; }
        public string SectionName { get; set; }
        public string LineName { get; set; }
    }
}
