CREATE TABLE [dbo].[Acc_CostCentre] (
    [Id]             INT              IDENTITY (1, 1) NOT NULL,
    [SectorId]       INT              NOT NULL,
    [CostCentreCode] NVARCHAR (50)    NULL,
    [CostCentreName] NVARCHAR (50)    NOT NULL,
    [SortOrder]      INT              NULL,
    [IsActive]       BIT              NULL,
    [CDT]            DATETIME         NULL,
    [CreatedBy]      UNIQUEIDENTIFIER NULL,
    [EDT]            DATETIME         NULL,
    [EditedBy]       UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_Acc_CostCentre] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Acc_CostCentre_Acc_CompanySector] FOREIGN KEY ([SectorId]) REFERENCES [dbo].[Acc_CompanySector] ([Id]),
    UNIQUE NONCLUSTERED ([CostCentreCode] ASC),
    UNIQUE NONCLUSTERED ([CostCentreCode] ASC),
    UNIQUE NONCLUSTERED ([CostCentreCode] ASC),
    UNIQUE NONCLUSTERED ([CostCentreCode] ASC),
    UNIQUE NONCLUSTERED ([CostCentreCode] ASC),
    UNIQUE NONCLUSTERED ([CostCentreCode] ASC),
    UNIQUE NONCLUSTERED ([CostCentreCode] ASC),
    UNIQUE NONCLUSTERED ([CostCentreCode] ASC),
    UNIQUE NONCLUSTERED ([CostCentreCode] ASC),
    UNIQUE NONCLUSTERED ([CostCentreName] ASC),
    UNIQUE NONCLUSTERED ([CostCentreName] ASC),
    UNIQUE NONCLUSTERED ([CostCentreName] ASC),
    UNIQUE NONCLUSTERED ([CostCentreName] ASC),
    UNIQUE NONCLUSTERED ([CostCentreName] ASC),
    UNIQUE NONCLUSTERED ([CostCentreName] ASC),
    UNIQUE NONCLUSTERED ([CostCentreName] ASC),
    UNIQUE NONCLUSTERED ([CostCentreName] ASC),
    UNIQUE NONCLUSTERED ([CostCentreName] ASC),
    CONSTRAINT [UQ__Acc_Cost__29707BE77208955D] UNIQUE NONCLUSTERED ([CostCentreCode] ASC),
    CONSTRAINT [UQ__Acc_Cost__29707BE7E32292B6] UNIQUE NONCLUSTERED ([CostCentreCode] ASC),
    CONSTRAINT [UQ__Acc_Cost__3D09EDA64AD762FD] UNIQUE NONCLUSTERED ([CostCentreName] ASC),
    CONSTRAINT [UQ__Acc_Cost__3D09EDA69BD30512] UNIQUE NONCLUSTERED ([CostCentreName] ASC)
);

