CREATE TABLE [dbo].[CommImportExportPerformance] (
    [Id]                       INT             IDENTITY (1, 1) NOT NULL,
    [SerialId]                 INT             NULL,
    [LcId]                     INT             NULL,
    [LcNo]                     NVARCHAR (50)   NULL,
    [LcDate]                   DATETIME        NULL,
    [BuyerId]                  BIGINT          NULL,
    [LcAmount]                 DECIMAL (18, 2) NULL,
    [LcQuantity]               DECIMAL (18, 2) NULL,
    [MatureDate]               DATETIME        NULL,
    [ExpiryDate]               DATETIME        NULL,
    [ExtensionDate]            DATETIME        NULL,
    [LcIssuingBank]            NVARCHAR (100)  NULL,
    [LcIssuingBankAddress]     NVARCHAR (500)  NULL,
    [ReceivingBank]            NVARCHAR (100)  NULL,
    [ReceivingBankAddress]     NVARCHAR (500)  NULL,
    [LcType]                   INT             NULL,
    [Beneficary]               NVARCHAR (50)   NULL,
    [PartialShipment]          INT             NULL,
    [Description]              NVARCHAR (MAX)  NULL,
    [BbLcNo]                   NVARCHAR (50)   NULL,
    [BbLcDate]                 DATETIME        NULL,
    [SupplierCompanyRefId]     INT             NULL,
    [BbLcAmount]               DECIMAL (18, 2) NULL,
    [BbLcQuantity]             DECIMAL (18, 2) NULL,
    [BbLcMatureDate]           DATETIME        NULL,
    [BBLcExpiryDate]           DATETIME        NULL,
    [BBLcExtensionDate]        DATETIME        NULL,
    [BbLcIssuingBank]          NVARCHAR (100)  NULL,
    [BbLcIssuingBankAddress]   NVARCHAR (500)  NULL,
    [BBLcReceivingBank]        NVARCHAR (100)  NULL,
    [BBLcReceivingBankAddress] NVARCHAR (500)  NULL,
    [BbLcType]                 INT             NULL,
    [Beneficiary]              NVARCHAR (50)   NULL,
    [BBLcPartialShipment]      INT             NULL,
    [BBLcDescription]          NVARCHAR (MAX)  NULL,
    [IfdbcNo]                  NVARCHAR (100)  NULL,
    [IfdbcDate]                DATETIME        NULL,
    [IfdbcValue]               DECIMAL (18, 2) NULL,
    [PcsSanctionAmount]        INT             NULL,
    [ExportNo]                 VARCHAR (25)    NULL,
    [ExportDate]               DATE            NULL,
    [InvoiceNo]                VARCHAR (25)    NULL,
    [InvoiceDate]              DATE            NULL,
    [InvoiceValue]             DECIMAL (18, 5) NULL,
    [BankRefNo]                VARCHAR (25)    NULL,
    [BankRefDate]              DATE            NULL,
    [RealizedValue]            DECIMAL (18, 5) NULL,
    [RealizedDate]             DATE            NULL,
    [BillOfLadingNo]           VARCHAR (25)    NULL,
    [BillOfLadingDate]         DATE            NULL,
    [SBNo]                     VARCHAR (25)    NULL,
    [SBNoDate]                 DATE            NULL,
    CONSTRAINT [PK_CommImportExportPerformance] PRIMARY KEY CLUSTERED ([Id] ASC)
);

