CREATE TABLE [dbo].[CommSalseContact] (
    [SalseContactId]       INT              IDENTITY (1, 1) NOT NULL,
    [LcId]                 INT              NOT NULL,
    [LcNo]                 NVARCHAR (50)    NOT NULL,
    [LcDate]               DATETIME         NOT NULL,
    [BuyerId]              BIGINT           NULL,
    [Amount]               FLOAT (53)       NOT NULL,
    [Quantity]             FLOAT (53)       NOT NULL,
    [MatureDate]           DATETIME         NULL,
    [ExpiryDate]           DATETIME         NULL,
    [ExtensionDate]        DATETIME         NULL,
    [ShipmentDate]         DATETIME         NULL,
    [LcIssuingBank]        NVARCHAR (100)   NULL,
    [LcIssuingBankAddress] NVARCHAR (500)   NULL,
    [ReceivingBankAddress] NVARCHAR (500)   NULL,
    [ReceivingBankId]      INT              NULL,
    [LcType]               INT              NULL,
    [Description]          NVARCHAR (MAX)   NULL,
    [CreatedDate]          DATETIME         NULL,
    [CreatedBy]            UNIQUEIDENTIFIER NULL,
    [EditedDate]           DATETIME         NULL,
    [EditedBy]             UNIQUEIDENTIFIER NULL,
    [IsActive]             BIT              NOT NULL,
    [CashIncentiveDate]    DATE             NULL,
    [CashIncentiveAmount]  FLOAT (53)       NULL,
    [AuditDate]            DATE             NULL,
    [AuditAmount]          FLOAT (53)       NULL,
    CONSTRAINT [PK_CommSalseContact] PRIMARY KEY CLUSTERED ([SalseContactId] ASC),
    CONSTRAINT [FK_CommSalseContact_COMMLcInfo] FOREIGN KEY ([LcId]) REFERENCES [dbo].[COMMLcInfo] ([LcId])
);

