CREATE TABLE [dbo].[CommCashBbLcInfo] (
    [BbLcId]                 INT              IDENTITY (1, 1) NOT NULL,
    [LcRefId]                INT              NOT NULL,
    [BbLcNo]                 NVARCHAR (50)    NULL,
    [BbLcDate]               DATETIME         NULL,
    [PI]                     NVARCHAR (20)    NULL,
    [PaymentMode]            INT              NULL,
    [LCType]                 NVARCHAR (50)    NULL,
    [SupplierCompanyRefId]   INT              NULL,
    [BbLcAmount]             DECIMAL (18, 2)  NULL,
    [BbLcQuantity]           DECIMAL (18, 2)  NULL,
    [MatureDate]             DATETIME         NULL,
    [ExpiryDate]             DATETIME         NULL,
    [ExtensionDate]          DATETIME         NULL,
    [BbLcIssuingBank]        NVARCHAR (100)   NULL,
    [BbLcIssuingBankAddress] NVARCHAR (500)   NULL,
    [IssuingBankId]          INT              NULL,
    [ReceivingBank]          NVARCHAR (100)   NULL,
    [ReceivingBankAddress]   NVARCHAR (500)   NULL,
    [BbLcType]               INT              NULL,
    [Beneficiary]            NVARCHAR (50)    NULL,
    [PartialShipment]        INT              NULL,
    [Description]            NVARCHAR (MAX)   NULL,
    [IfdbcNo]                NVARCHAR (100)   NULL,
    [IfdbcDate]              DATETIME         NULL,
    [IfdbcValue]             DECIMAL (18, 2)  NULL,
    [PcsSanctionAmount]      INT              NULL,
    [PaymentDate]            DATETIME         NULL,
    [BtmeaNo]                NVARCHAR (50)    NULL,
    [BtmeaDate]              DATETIME         NULL,
    [BeNo]                   NVARCHAR (50)    NULL,
    [BeDate]                 DATETIME         NULL,
    [Vat]                    DECIMAL (18, 4)  NULL,
    [CreatedDate]            DATETIME         NULL,
    [CreatedBy]              UNIQUEIDENTIFIER NULL,
    [EditedDate]             DATETIME         NULL,
    [EditedBy]               UNIQUEIDENTIFIER NULL,
    [IsActive]               BIT              NOT NULL,
    [CompId]                 VARCHAR (3)      NULL,
    CONSTRAINT [PK_CommCashBbLcInfo] PRIMARY KEY CLUSTERED ([BbLcId] ASC)
);

