CREATE TABLE [dbo].[CommImportDetails] (
    [ImportDetailId]      INT              IDENTITY (1, 1) NOT NULL,
    [ImportId]            INT              NOT NULL,
    [CompId]              NVARCHAR (3)     NULL,
    [LCNo]                NVARCHAR (100)   NULL,
    [LCDate]              DATE             NULL,
    [LcValue]             DECIMAL (18, 2)  NULL,
    [DocsValue]           DECIMAL (18, 2)  NULL,
    [InvoiceNo]           NVARCHAR (100)   NULL,
    [InvoiceDate]         DATE             NULL,
    [SupplierName]        NVARCHAR (50)    NULL,
    [SupplierCountry]     NVARCHAR (50)    NULL,
    [Item]                NVARCHAR (50)    NULL,
    [LCQty]               DECIMAL (18, 2)  NULL,
    [DocsQty]             DECIMAL (18, 2)  NULL,
    [DocsReceiveDate]     DATE             NULL,
    [IncomingPort]        NVARCHAR (50)    NULL,
    [DocsReceiverAgent]   NVARCHAR (50)    NULL,
    [DocsReceiverPerson]  NVARCHAR (50)    NULL,
    [DocsReceiveDateByCF] DATETIME         NULL,
    [GoodsInHouseDate]    DATE             NULL,
    [BillOfEntry]         NVARCHAR (100)   NULL,
    [Remarks]             NVARCHAR (200)   NULL,
    [CreatedBy]           UNIQUEIDENTIFIER NULL,
    [EditedBy]            UNIQUEIDENTIFIER NULL,
    [EditedDate]          DATETIME         NULL,
    [CreatedDate]         DATETIME         NULL,
    CONSTRAINT [PK_CommImportDetails] PRIMARY KEY CLUSTERED ([ImportDetailId] ASC),
    CONSTRAINT [FK_CommImportDetails_CommImport] FOREIGN KEY ([ImportId]) REFERENCES [dbo].[CommImport] ([ImportId])
);

