CREATE TABLE [dbo].[Company] (
    [Id]                       INT              IDENTITY (1, 1) NOT NULL,
    [CompanyRefId]             VARCHAR (3)      NULL,
    [Name]                     NVARCHAR (100)   NOT NULL,
    [NameInBengali]            NVARCHAR (100)   NOT NULL,
    [FullAddress]              NVARCHAR (MAX)   NOT NULL,
    [FullAddressInBengali]     NVARCHAR (MAX)   NOT NULL,
    [DistrictId]               INT              NULL,
    [PoliceStationId]          INT              NULL,
    [PostOffice]               NVARCHAR (100)   NULL,
    [PostOfficeInBengali]      NVARCHAR (100)   NULL,
    [PostCode]                 NVARCHAR (100)   NULL,
    [Phone]                    NVARCHAR (100)   NOT NULL,
    [Fax]                      NVARCHAR (100)   NULL,
    [Email]                    NVARCHAR (100)   NULL,
    [Website]                  NVARCHAR (100)   NULL,
    [TinNo]                    NVARCHAR (100)   NULL,
    [VatRegNo]                 NVARCHAR (100)   NULL,
    [NumberOfBranches]         INT              NULL,
    [ContactPerson]            NVARCHAR (100)   NOT NULL,
    [ContactPersonDesignation] NVARCHAR (100)   NULL,
    [ContactPersonMobile]      NVARCHAR (100)   NOT NULL,
    [ContactPersonEmail]       NVARCHAR (100)   NULL,
    [CreatedDate]              DATETIME         NULL,
    [CreatedBy]                UNIQUEIDENTIFIER NULL,
    [EditedDate]               DATETIME         NULL,
    [EditedBy]                 UNIQUEIDENTIFIER NULL,
    [IsActive]                 BIT              NOT NULL,
    [ImagePath]                VARCHAR (250)    NULL,
    [DomainName]               VARCHAR (10)     NULL,
    CONSTRAINT [PK_Company] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Company_District] FOREIGN KEY ([DistrictId]) REFERENCES [dbo].[District] ([Id]),
    CONSTRAINT [FK_Company_PoliceStation] FOREIGN KEY ([PoliceStationId]) REFERENCES [dbo].[PoliceStation] ([Id]) ON DELETE CASCADE
);

