CREATE TABLE [dbo].[EmployeeJobCard_10PM_NoWeekend] (
    [Id]                           INT              IDENTITY (1, 1) NOT NULL,
    [EmployeeId]                   UNIQUEIDENTIFIER NOT NULL,
    [Year]                         INT              NOT NULL,
    [Month]                        INT              NOT NULL,
    [MonthName]                    NVARCHAR (100)   NULL,
    [FromDate]                     DATETIME         NULL,
    [ToDate]                       DATETIME         NULL,
    [CompanyId]                    INT              NOT NULL,
    [CompanyName]                  NVARCHAR (100)   NOT NULL,
    [CompanyNameInBengali]         NVARCHAR (100)   NULL,
    [CompanyAddress]               NVARCHAR (MAX)   NOT NULL,
    [CompanyAddressInBengali]      NVARCHAR (MAX)   NULL,
    [BranchId]                     INT              NOT NULL,
    [BranchName]                   NVARCHAR (100)   NOT NULL,
    [BranchNameInBengali]          NVARCHAR (100)   NULL,
    [BranchUnitId]                 INT              NOT NULL,
    [UnitName]                     NVARCHAR (100)   NOT NULL,
    [UnitNameInBengali]            NVARCHAR (100)   NULL,
    [BranchUnitDepartmentId]       INT              NOT NULL,
    [DepartmentName]               NVARCHAR (100)   NOT NULL,
    [DepartmentNameInBengali]      NVARCHAR (100)   NULL,
    [DepartmentSectionId]          INT              NOT NULL,
    [SectionName]                  NVARCHAR (100)   NOT NULL,
    [SectionNameInBengali]         NVARCHAR (100)   NULL,
    [DepartmentLineId]             INT              NOT NULL,
    [LineName]                     NVARCHAR (100)   NOT NULL,
    [LineNameInBengali]            NVARCHAR (100)   NULL,
    [EmployeeCardId]               NVARCHAR (100)   NOT NULL,
    [EmployeeName]                 NVARCHAR (100)   NOT NULL,
    [EmployeeNameInBengali]        NVARCHAR (100)   NULL,
    [MobileNo]                     NVARCHAR (100)   NOT NULL,
    [EmployeeTypeId]               INT              NOT NULL,
    [EmployeeType]                 NVARCHAR (100)   NOT NULL,
    [EmployeeTypeInBengali]        NVARCHAR (100)   NULL,
    [EmployeeGradeId]              INT              NOT NULL,
    [EmployeeGrade]                NVARCHAR (100)   NOT NULL,
    [EmployeeGradeInBengali]       NVARCHAR (100)   NULL,
    [EmployeeDesignationId]        INT              NOT NULL,
    [EmployeeDesignation]          NVARCHAR (100)   NOT NULL,
    [EmployeeDesignationInBengali] NVARCHAR (100)   NULL,
    [EmployeeActiveStatusId]       INT              NULL,
    [EmployeeCategoryId]           INT              NULL,
    [JoiningDate]                  DATETIME         NOT NULL,
    [QuitDate]                     DATETIME         NULL,
    [TotalDays]                    INT              NOT NULL,
    [WorkingDays]                  INT              NOT NULL,
    [PresentDays]                  INT              NOT NULL,
    [LateDays]                     INT              NOT NULL,
    [OSDDays]                      INT              NULL,
    [AbsentDays]                   INT              NOT NULL,
    [LeaveDays]                    INT              NOT NULL,
    [LWPDays]                      INT              NOT NULL,
    [Holidays]                     INT              NOT NULL,
    [WeekendDays]                  INT              NOT NULL,
    [PayDays]                      INT              NOT NULL,
    [CasualLeave]                  INT              NULL,
    [SickLeave]                    INT              NULL,
    [MaternityLeave]               INT              NULL,
    [EarnLeave]                    INT              NULL,
    [GrossSalary]                  NUMERIC (18, 2)  NOT NULL,
    [BasicSalary]                  NUMERIC (18, 2)  NULL,
    [HouseRent]                    NUMERIC (18, 2)  NULL,
    [MedicalAllowance]             NUMERIC (18, 2)  NULL,
    [Conveyance]                   NUMERIC (18, 2)  NULL,
    [FoodAllowance]                NUMERIC (18, 2)  NULL,
    [EntertainmentAllowance]       NUMERIC (18, 2)  NULL,
    [PerDayBasicSalary]            NUMERIC (18, 2)  NULL,
    [LWPFee]                       NUMERIC (18, 2)  NULL,
    [AbsentFee]                    NUMERIC (18, 2)  NULL,
    [AttendanceBonus]              NUMERIC (18, 2)  NULL,
    [ShiftingBonus]                NUMERIC (18, 2)  NULL,
    [TotalOTHours]                 NUMERIC (18, 2)  NOT NULL,
    [TotalExtraOTHours]            NUMERIC (18, 2)  NOT NULL,
    [TotalWeekendOTHours]          NUMERIC (18, 2)  NULL,
    [TotalHolidayOTHours]          NUMERIC (18, 2)  NULL,
    [OTRate]                       NUMERIC (18, 2)  NULL,
    [EmployeeOTRate]               NUMERIC (18, 2)  NULL,
    [TotalOTAmount]                NUMERIC (18, 2)  NULL,
    [TotalExtraOTAmount]           NUMERIC (18, 2)  NULL,
    [TotalWeekendOTAmount]         NUMERIC (18, 2)  NULL,
    [TotalHolidayOTAmount]         NUMERIC (18, 2)  NULL,
    [TotalPenaltyOTHours]          NUMERIC (18, 2)  NULL,
    [TotalPenaltyOTAmount]         NUMERIC (18, 2)  NULL,
    [TotalPenaltyAttendanceDays]   INT              NULL,
    [TotalPenaltyAbsentFee]        NUMERIC (18, 2)  NULL,
    [TotalPenaltyLeaveDays]        INT              NULL,
    [TotalPenaltyFinancialAmount]  NUMERIC (18, 2)  NULL,
    [CreatedDate]                  DATETIME         NOT NULL,
    [CreatedBy]                    UNIQUEIDENTIFIER NOT NULL,
    [IsActive]                     BIT              NOT NULL,
    CONSTRAINT [PK_EmployeeJobCard10PM_After_1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

