CREATE TABLE [dbo].[EmployeeLeave] (
    [Id]                       INT              IDENTITY (1, 1) NOT NULL,
    [EmployeeId]               UNIQUEIDENTIFIER NOT NULL,
    [EmployeeCardId]           NVARCHAR (100)   NOT NULL,
    [LeaveTypeId]              INT              NOT NULL,
    [SubmitDate]               DATETIME         NOT NULL,
    [AppliedFromDate]          DATETIME         NOT NULL,
    [AppliedToDate]            DATETIME         NOT NULL,
    [AppliedTotalDays]         INT              NOT NULL,
    [LeavePurpose]             NVARCHAR (MAX)   NOT NULL,
    [EmergencyPhoneNo]         NVARCHAR (100)   NOT NULL,
    [AddressDuringLeave]       NVARCHAR (MAX)   NOT NULL,
    [RecommendedFromDate]      DATETIME         NULL,
    [RecommendedToDate]        DATETIME         NULL,
    [RecommendedTotalDays]     INT              NULL,
    [RecommendationStatus]     INT              NULL,
    [RecommendationStatusDate] DATETIME         NULL,
    [RecommendationPerson]     UNIQUEIDENTIFIER NULL,
    [RecommendationComment]    NVARCHAR (MAX)   NULL,
    [ApprovedFromDate]         DATETIME         NULL,
    [ApprovedToDate]           DATETIME         NULL,
    [ApprovedTotalDays]        INT              NULL,
    [ApprovalStatus]           INT              NULL,
    [ApprovalStatusDate]       DATETIME         NULL,
    [ApprovalPerson]           UNIQUEIDENTIFIER NULL,
    [ApprovalComment]          NVARCHAR (MAX)   NULL,
    [ConsumedFromDate]         DATETIME         NULL,
    [ConsumedToDate]           DATETIME         NULL,
    [ConsumedTotalDays]        INT              NULL,
    [JoinedBeforeDays]         INT              NULL,
    [ResumeDate]               DATETIME         NULL,
    [CreatedDate]              DATETIME         NULL,
    [CreatedBy]                UNIQUEIDENTIFIER NULL,
    [EditedDate]               DATETIME         NULL,
    [EditedBy]                 UNIQUEIDENTIFIER NULL,
    [IsActive]                 BIT              NOT NULL,
    CONSTRAINT [PK_EmployeeLeave] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_EmployeeLeave_Employee] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[Employee] ([EmployeeId]),
    CONSTRAINT [FK_EmployeeLeave_LeaveType] FOREIGN KEY ([LeaveTypeId]) REFERENCES [dbo].[LeaveType] ([Id])
);

