CREATE TABLE [dbo].[EmployeePresentAddress] (
    [Id]                              INT              IDENTITY (1, 1) NOT NULL,
    [EmployeeId]                      UNIQUEIDENTIFIER NOT NULL,
    [MailingAddress]                  NVARCHAR (MAX)   NOT NULL,
    [MailingAddressInBengali]         NVARCHAR (MAX)   NOT NULL,
    [CountryId]                       INT              NULL,
    [DistrictId]                      INT              NULL,
    [PoliceStationId]                 INT              NULL,
    [PostOffice]                      NVARCHAR (100)   NULL,
    [PostOfficeInBengali]             NVARCHAR (100)   NULL,
    [PostCode]                        NVARCHAR (100)   NULL,
    [HomePhone]                       NVARCHAR (100)   NULL,
    [MobilePhone]                     NVARCHAR (100)   NOT NULL,
    [EmailAddress]                    NVARCHAR (100)   NULL,
    [AlternateEmailAddress]           NVARCHAR (100)   NULL,
    [LandlordName]                    NVARCHAR (100)   NULL,
    [LandlordNameInBengali]           NVARCHAR (100)   NULL,
    [LandlordPhone]                   NVARCHAR (100)   NULL,
    [EmergencyContactPerson]          NVARCHAR (100)   NULL,
    [EmergencyContactPersonInBengali] NVARCHAR (100)   NULL,
    [ContactPersonRelation]           NVARCHAR (100)   NULL,
    [ContactPersonRelationInBengali]  NVARCHAR (100)   NULL,
    [ContactPersonPhone]              NVARCHAR (100)   NULL,
    [CreatedDate]                     DATETIME         NULL,
    [CreatedBy]                       UNIQUEIDENTIFIER NULL,
    [EditedDate]                      DATETIME         NULL,
    [EditedBy]                        UNIQUEIDENTIFIER NULL,
    [Status]                          INT              NOT NULL,
    [IsActive]                        BIT              NOT NULL,
    CONSTRAINT [PK_EmployeePresentAddress] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_EmployeePresentAddress_Country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_EmployeePresentAddress_District] FOREIGN KEY ([DistrictId]) REFERENCES [dbo].[District] ([Id]),
    CONSTRAINT [FK_EmployeePresentAddress_Employee] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[Employee] ([EmployeeId]) ON DELETE CASCADE,
    CONSTRAINT [FK_EmployeePresentAddress_PoliceStation] FOREIGN KEY ([PoliceStationId]) REFERENCES [dbo].[PoliceStation] ([Id])
);

