CREATE TABLE [dbo].[EmployeeLeave_Old] (
    [Id]                   INT              NOT NULL,
    [EmployeeId]           UNIQUEIDENTIFIER NOT NULL,
    [LeaveTypeId]          INT              NULL,
    [EmployeeTypeId]       INT              NULL,
    [SubmitDate]           DATETIME         NULL,
    [AuthorizedStatusDate] DATETIME         NULL,
    [ApprovalStatusDate]   DATETIME         NULL,
    [AppliedFromDate]      DATETIME         NULL,
    [AppliedToDate]        DATETIME         NULL,
    [AuthorizedFromDate]   DATETIME         NULL,
    [AuthorizedToDate]     DATETIME         NULL,
    [AppliedTotalDays]     INT              NULL,
    [AuthorizedTotalDays]  INT              NULL,
    [ResumeDate]           DATETIME         NULL,
    [JoinDate]             DATETIME         NULL,
    [JoinBefore]           INT              NULL,
    [AuthorizedStatus]     NVARCHAR (100)   NULL,
    [ApprovalStatus]       NVARCHAR (100)   NULL,
    [LeavePurpose]         NVARCHAR (MAX)   NULL,
    [ApprovalPerson]       UNIQUEIDENTIFIER NULL,
    [AuthorizedPerson]     UNIQUEIDENTIFIER NULL,
    [AddressDuringLeave]   NVARCHAR (MAX)   NULL,
    [EmergencyPhoneNo]     NVARCHAR (100)   NULL,
    [AuthorizedComment]    NVARCHAR (MAX)   NULL,
    [ApprovalComments]     NVARCHAR (MAX)   NULL,
    [CDT]                  DATETIME         NULL,
    [CreatedBy]            UNIQUEIDENTIFIER NULL,
    [EDT]                  DATETIME         NULL,
    [EditedBy]             UNIQUEIDENTIFIER NULL,
    [IsActive]             BIT              NOT NULL
);

