CREATE TABLE [dbo].[Employee] (
    [Id]                   INT              IDENTITY (1, 1) NOT NULL,
    [EmployeeId]           UNIQUEIDENTIFIER NOT NULL,
    [EmployeeCardId]       NVARCHAR (100)   NOT NULL,
    [Name]                 NVARCHAR (100)   NOT NULL,
    [NameInBengali]        NVARCHAR (100)   NOT NULL,
    [MothersName]          NVARCHAR (100)   NOT NULL,
    [MothersNameInBengali] NVARCHAR (100)   NOT NULL,
    [FathersName]          NVARCHAR (100)   NOT NULL,
    [FathersNameInBengali] NVARCHAR (100)   NOT NULL,
    [SpousesName]          NVARCHAR (100)   NULL,
    [SpousesNameInBengali] NVARCHAR (100)   NULL,
    [DateOfBirth]          DATETIME         NOT NULL,
    [GenderId]             TINYINT          NOT NULL,
    [MaritalStateId]       INT              NULL,
    [MariageAnniversary]   DATETIME         NULL,
    [Nationality]          NVARCHAR (100)   NULL,
    [NationalityInBengali] NVARCHAR (100)   NULL,
    [BirthRegistrationNo]  NVARCHAR (100)   NULL,
    [NationalIdNo]         NVARCHAR (100)   NULL,
    [ReligionId]           INT              NOT NULL,
    [TaxIdentificationNo]  NVARCHAR (100)   NULL,
    [DrivingLicenseNo]     NVARCHAR (100)   NULL,
    [PassportNo]           NVARCHAR (100)   NULL,
    [BloodGroupId]         INT              NULL,
    [PhotographPath]       NVARCHAR (200)   NOT NULL,
    [JoiningDate]          DATETIME         NOT NULL,
    [ConfirmationDate]     DATETIME         NOT NULL,
    [QuitDate]             DATETIME         NULL,
    [QuitTypeId]           INT              NULL,
    [CreatedDate]          DATETIME         NULL,
    [CreatedBy]            UNIQUEIDENTIFIER NULL,
    [EditedDate]           DATETIME         NULL,
    [EditedBy]             UNIQUEIDENTIFIER NULL,
    [Status]               INT              NOT NULL,
    [IsActive]             BIT              NOT NULL,
    CONSTRAINT [PK_Employee_1] PRIMARY KEY CLUSTERED ([EmployeeId] ASC),
    CONSTRAINT [FK_Employee_BloodGroup] FOREIGN KEY ([BloodGroupId]) REFERENCES [dbo].[BloodGroup] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_Employee_Gender] FOREIGN KEY ([GenderId]) REFERENCES [dbo].[Gender] ([GenderId]),
    CONSTRAINT [FK_Employee_MaritalStatus] FOREIGN KEY ([MaritalStateId]) REFERENCES [dbo].[MaritalState] ([MaritalStateId]),
    CONSTRAINT [FK_Employee_QuitType] FOREIGN KEY ([QuitTypeId]) REFERENCES [dbo].[QuitType] ([QuitTypeId]),
    CONSTRAINT [FK_Employee_Religion] FOREIGN KEY ([ReligionId]) REFERENCES [dbo].[Religion] ([ReligionId])
);

