CREATE TABLE [dbo].[EmployeeIncrement] (
    [IncrementId]            INT              IDENTITY (1, 1) NOT NULL,
    [CompanyName]            NVARCHAR (100)   NULL,
    [CompanyAddress]         NVARCHAR (200)   NULL,
    [BranchName]             NVARCHAR (100)   NULL,
    [UnitName]               NVARCHAR (100)   NULL,
    [DepartmentName]         NVARCHAR (100)   NULL,
    [SectionName]            NVARCHAR (100)   NULL,
    [LineName]               NVARCHAR (100)   NULL,
    [EmployeeId]             UNIQUEIDENTIFIER NULL,
    [EmployeeCardId]         NVARCHAR (10)    NULL,
    [EmployeeName]           NVARCHAR (100)   NULL,
    [EmployeeType]           NVARCHAR (100)   NULL,
    [GradeName]              NVARCHAR (100)   NULL,
    [DesignationName]        NVARCHAR (100)   NULL,
    [JoiningDate]            DATETIME         NULL,
    [QuitDate]               DATETIME         NULL,
    [MobilePhone]            NVARCHAR (100)   NULL,
    [Percent]                NVARCHAR (10)    NULL,
    [GrossSalary]            DECIMAL (18, 2)  NOT NULL,
    [BasicSalary]            DECIMAL (18, 2)  NOT NULL,
    [HouseRent]              DECIMAL (18, 2)  NOT NULL,
    [MedicalAllowance]       DECIMAL (18, 2)  NULL,
    [EntertainmentAllowance] DECIMAL (18, 2)  NULL,
    [FoodAllowance]          DECIMAL (18, 2)  NULL,
    [Conveyance]             DECIMAL (18, 2)  NULL,
    [LastIncrementDate]      DATETIME         NULL,
    [NewGross]               FLOAT (53)       NULL,
    [NewBasic]               FLOAT (53)       NULL,
    [NewHouseRent]           FLOAT (53)       NULL,
    [OtherBenefit]           DECIMAL (18, 2)  NULL,
    [OtherIncrement]         DECIMAL (18, 2)  NULL,
    [TotalIncrement]         FLOAT (53)       NULL,
    [ApprovedIncrement]      NVARCHAR (50)    NULL,
    [Remarks]                NVARCHAR (50)    NULL,
    [FromDate]               DATETIME         NULL,
    [ToDate]                 DATETIME         NULL,
    [CreatedDate]            DATETIME         NULL,
    [CreatedBy]              UNIQUEIDENTIFIER NULL,
    [EditedDate]             DATETIME         NULL,
    [EditedBy]               UNIQUEIDENTIFIER NULL,
    [IsActive]               BIT              NOT NULL,
    CONSTRAINT [PK_EmployeeIncrement] PRIMARY KEY CLUSTERED ([IncrementId] ASC)
);

