CREATE TABLE [dbo].[EmployeeSalary_Processed_Temp] (
    [Id]                     INT              IDENTITY (1, 1) NOT NULL,
    [EmployeeId]             UNIQUEIDENTIFIER NOT NULL,
    [FromDate]               DATETIME         NOT NULL,
    [ToDate]                 DATETIME         NOT NULL,
    [GrossSalary]            DECIMAL (18, 2)  NOT NULL,
    [BasicSalary]            DECIMAL (18, 2)  NOT NULL,
    [HouseRent]              DECIMAL (18, 2)  NOT NULL,
    [MedicalAllowance]       DECIMAL (18, 2)  NOT NULL,
    [Conveyance]             DECIMAL (18, 2)  NOT NULL,
    [FoodAllowance]          DECIMAL (18, 2)  NULL,
    [EntertainmentAllowance] DECIMAL (18, 2)  NULL,
    [LWP]                    DECIMAL (18, 2)  NULL,
    [Absent]                 DECIMAL (18, 2)  NULL,
    [Advance]                DECIMAL (18, 2)  NULL,
    [Stamp]                  DECIMAL (18, 2)  NULL,
    [TotalDeduction]         DECIMAL (18, 2)  NULL,
    [AttendanceBonus]        DECIMAL (18, 2)  NULL,
    [ShiftingAllowance]      DECIMAL (18, 2)  NULL,
    [PayableAmount]          DECIMAL (18, 2)  NULL,
    [OTHours]                FLOAT (53)       NULL,
    [OTRate]                 DECIMAL (18, 2)  NULL,
    [OTAmount]               DECIMAL (18, 2)  NULL,
    [NetSalaryPaid]          DECIMAL (18, 2)  NULL,
    [Comments]               NVARCHAR (MAX)   NULL,
    [Tax]                    DECIMAL (18, 2)  NULL,
    [ProvidentFund]          DECIMAL (18, 2)  NULL,
    [CreatedDate]            DATETIME         NULL,
    [CreatedBy]              UNIQUEIDENTIFIER NULL,
    [EditedDate]             DATETIME         NULL,
    [EditedBy]               UNIQUEIDENTIFIER NULL,
    [IsActive]               BIT              NOT NULL,
    CONSTRAINT [PK_EmployeeSalary_Processed_Temp] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_EmployeeSalary_Processed_Temp_Employee] FOREIGN KEY ([EmployeeId]) REFERENCES [dbo].[Employee] ([EmployeeId]) ON DELETE CASCADE
);

