CREATE TABLE [dbo].[EmployeeProcessedSalary_10PM_NoWeekend] (
    [Id]                      INT              IDENTITY (1, 1) NOT NULL,
    [EmployeeId]              UNIQUEIDENTIFIER NOT NULL,
    [EmployeeCardId]          NVARCHAR (50)    NULL,
    [Name]                    NVARCHAR (100)   NULL,
    [NameInBengali]           NVARCHAR (100)   NULL,
    [MobileNo]                NVARCHAR (100)   NULL,
    [Year]                    INT              NULL,
    [Month]                   INT              NULL,
    [MonthName]               NVARCHAR (100)   NULL,
    [FromDate]                DATETIME         NULL,
    [ToDate]                  DATETIME         NULL,
    [CompanyId]               INT              NULL,
    [CompanyName]             NVARCHAR (100)   NULL,
    [CompanyNameInBengali]    NVARCHAR (100)   NULL,
    [CompanyAddress]          NVARCHAR (MAX)   NULL,
    [CompanyAddressInBengali] NVARCHAR (MAX)   NULL,
    [BranchId]                INT              NULL,
    [Branch]                  NVARCHAR (100)   NULL,
    [BranchInBengali]         NVARCHAR (100)   NULL,
    [BranchUnitId]            INT              NULL,
    [Unit]                    NVARCHAR (100)   NULL,
    [UnitInBengali]           NVARCHAR (100)   NULL,
    [DepartmentId]            INT              NULL,
    [Department]              NVARCHAR (100)   NULL,
    [DepartmentInBengali]     NVARCHAR (100)   NULL,
    [SectionId]               INT              NULL,
    [Section]                 NVARCHAR (100)   NULL,
    [SectionInBengali]        NVARCHAR (100)   NULL,
    [LineId]                  INT              NULL,
    [Line]                    NVARCHAR (100)   NULL,
    [LineInBengali]           NVARCHAR (100)   NULL,
    [EmployeeTypeId]          INT              NULL,
    [EmployeeType]            NVARCHAR (100)   NULL,
    [EmployeeTypeInBengali]   NVARCHAR (100)   NULL,
    [GradeId]                 INT              NULL,
    [Grade]                   NVARCHAR (100)   NULL,
    [GradeInBengali]          NVARCHAR (100)   NULL,
    [DesignationId]           INT              NULL,
    [Designation]             NVARCHAR (100)   NULL,
    [DesignationInBengali]    NVARCHAR (100)   NULL,
    [EmployeeCategoryId]      INT              NULL,
    [JoiningDate]             DATETIME         NULL,
    [QuitDate]                DATETIME         NULL,
    [TotalDays]               INT              NULL,
    [WorkingDays]             INT              NULL,
    [PresentDays]             INT              NULL,
    [LateDays]                INT              NULL,
    [OSDDays]                 INT              NULL,
    [AbsentDays]              INT              NULL,
    [LeaveDays]               INT              NULL,
    [LWPDays]                 INT              NULL,
    [HolidayDays]             INT              NULL,
    [WeekendDays]             INT              NULL,
    [Paydays]                 INT              NULL,
    [CasualLeave]             INT              NULL,
    [SickLeave]               INT              NULL,
    [MaternityLeave]          INT              NULL,
    [EarnLeave]               INT              NULL,
    [GrossSalary]             NUMERIC (18, 2)  NULL,
    [BasicSalary]             NUMERIC (18, 2)  NULL,
    [HouseRent]               NUMERIC (18, 2)  NULL,
    [MedicalAllowance]        NUMERIC (18, 2)  NULL,
    [Conveyance]              NUMERIC (18, 2)  NULL,
    [FoodAllowance]           NUMERIC (18, 2)  NULL,
    [EntertainmentAllowance]  NUMERIC (18, 2)  NULL,
    [LWPFee]                  NUMERIC (18, 2)  NULL,
    [AbsentFee]               NUMERIC (18, 2)  NULL,
    [PenaltyFee]              NUMERIC (18, 2)  NULL,
    [Advance]                 NUMERIC (18, 2)  NULL,
    [Stamp]                   NUMERIC (18, 2)  NULL,
    [TotalDeduction]          NUMERIC (18, 2)  NULL,
    [AttendanceBonus]         NUMERIC (18, 2)  NULL,
    [ShiftingBonus]           NUMERIC (18, 2)  NULL,
    [TotalBonus]              NUMERIC (18, 2)  NULL,
    [TotalPaid]               NUMERIC (18, 2)  NULL,
    [Rate]                    NUMERIC (18, 2)  NULL,
    [OTRate]                  NUMERIC (18, 2)  NULL,
    [OTHours]                 NUMERIC (18, 2)  NULL,
    [TotalOTAmount]           NUMERIC (18, 2)  NULL,
    [NetAmount]               NUMERIC (18, 2)  NULL,
    [TotalExtraOTHours]       NUMERIC (18, 2)  NULL,
    [TotalExtraOTAmount]      NUMERIC (18, 2)  NULL,
    [TotalWeekendOTHours]     NUMERIC (18, 2)  NULL,
    [TotalWeekendOTAmount]    NUMERIC (18, 2)  NULL,
    [TotalHolidayOTHours]     NUMERIC (18, 2)  NULL,
    [TotalHolidayOTAmount]    NUMERIC (18, 2)  NULL,
    [AdvancedIncomeTax]       DECIMAL (18, 2)  NULL,
    [CreatedDate]             DATETIME         NULL,
    [CreatedBy]               UNIQUEIDENTIFIER NULL,
    [EditedDate]              DATETIME         NULL,
    [EditedBy]                UNIQUEIDENTIFIER NULL,
    [IsActive]                BIT              NULL,
    CONSTRAINT [PK_EmployeeProcessedSalary_10PM_NoWeekend] PRIMARY KEY CLUSTERED ([Id] ASC)
);

