CREATE TABLE [dbo].[EmployeeProcessedSalaryTemp] (
    [Id]                     INT              NOT NULL,
    [Row]                    NVARCHAR (100)   NULL,
    [EmployeeId]             UNIQUEIDENTIFIER NOT NULL,
    [EmployeeCardId]         NVARCHAR (50)    NULL,
    [CompanyId]              INT              NULL,
    [CompanyName]            NVARCHAR (100)   NULL,
    [CompanyAddress]         NVARCHAR (100)   NULL,
    [Name]                   NVARCHAR (100)   NULL,
    [Designation]            NVARCHAR (100)   NULL,
    [Grade]                  NVARCHAR (100)   NULL,
    [JoiningDate]            NVARCHAR (100)   NULL,
    [BranchId]               INT              NULL,
    [Branch]                 NVARCHAR (100)   NULL,
    [BranchUnitId]           INT              NULL,
    [Unit]                   NVARCHAR (100)   NULL,
    [Department]             NVARCHAR (100)   NULL,
    [Section]                NVARCHAR (100)   NULL,
    [Line]                   NVARCHAR (100)   NULL,
    [TotalDays]              NVARCHAR (100)   NULL,
    [WorkingDays]            NVARCHAR (100)   NULL,
    [Paydays]                NVARCHAR (100)   NULL,
    [WeekendDays]            NVARCHAR (100)   NULL,
    [HolidayDays]            NVARCHAR (100)   NULL,
    [PresentDays]            NVARCHAR (100)   NULL,
    [AbsentDays]             NVARCHAR (100)   NULL,
    [LateDays]               NVARCHAR (100)   NULL,
    [LeaveDays]              NVARCHAR (100)   NULL,
    [LWPDays]                NVARCHAR (100)   NULL,
    [CasualLeave]            NVARCHAR (100)   NULL,
    [SickLeave]              NVARCHAR (100)   NULL,
    [MaternityLeave]         NVARCHAR (100)   NULL,
    [EarnLeave]              NVARCHAR (100)   NULL,
    [BasicSalary]            NUMERIC (18, 2)  NULL,
    [HouseRent]              NUMERIC (18, 2)  NULL,
    [MedicalAllowance]       NUMERIC (18, 2)  NULL,
    [Conveyance]             NUMERIC (18, 2)  NULL,
    [FoodAllowance]          NUMERIC (18, 2)  NULL,
    [EntertainmentAllowance] NUMERIC (18, 2)  NULL,
    [GrossSalary]            NUMERIC (18, 2)  NULL,
    [LWPFee]                 NUMERIC (18, 2)  NULL,
    [AbsentFee]              NUMERIC (18, 2)  NULL,
    [Advance]                NUMERIC (18, 2)  NULL,
    [Stamp]                  NUMERIC (18, 2)  NULL,
    [TotalDeduction]         NUMERIC (18, 2)  NULL,
    [AttendanceBonus]        NUMERIC (18, 2)  NULL,
    [ShiftingBonus]          NUMERIC (18, 2)  NULL,
    [TotalBonus]             NUMERIC (18, 2)  NULL,
    [TotalPaid]              NUMERIC (18, 2)  NULL,
    [OTHours]                NUMERIC (18, 2)  NULL,
    [OTRate]                 NUMERIC (18, 2)  NULL,
    [TotalOTAmount]          NUMERIC (18, 2)  NULL,
    [NetAmount]              NUMERIC (18, 2)  NULL,
    [Month]                  NVARCHAR (100)   NULL,
    [Year]                   NVARCHAR (100)   NULL,
    [DepartmentId]           INT              NULL,
    [SectionId]              INT              NULL,
    [LineId]                 INT              NULL,
    [EmployeeTypeId]         INT              NULL,
    [MonthName]              NVARCHAR (100)   NULL,
    [FromDate]               DATETIME         NULL,
    [ToDate]                 DATETIME         NULL
);

