CREATE TABLE [dbo].[FinalSettlement] (
    [FinalSettlementId]    INT              IDENTITY (1, 1) NOT NULL,
    [CompanyName]          NVARCHAR (50)    NULL,
    [CompanyAddress]       NVARCHAR (100)   NULL,
    [Month]                NVARCHAR (50)    NULL,
    [Year]                 NVARCHAR (50)    NULL,
    [NameInBangla]         NVARCHAR (50)    NULL,
    [EmployeeId]           UNIQUEIDENTIFIER NULL,
    [EmployeeCardId]       NVARCHAR (50)    NULL,
    [Designation]          NVARCHAR (50)    NULL,
    [Section]              NVARCHAR (50)    NULL,
    [Department]           NVARCHAR (50)    NULL,
    [JoiningDate]          NVARCHAR (50)    NULL,
    [QuitDate]             NVARCHAR (50)    NULL,
    [ServiceDuration]      NVARCHAR (50)    NULL,
    [EarnLeave]            DECIMAL (18, 2)  NULL,
    [DailyGrossSalary]     DECIMAL (18, 2)  NULL,
    [ServiceBenefit]       DECIMAL (18, 2)  NULL,
    [TotalWorkingDays]     INT              NULL,
    [TotalOTHour]          DECIMAL (18, 2)  NULL,
    [TotalPayDays]         INT              NULL,
    [OverTimeRate]         DECIMAL (18, 2)  NULL,
    [GrossSalary]          DECIMAL (18, 2)  NULL,
    [DailyBasicSalary]     DECIMAL (18, 2)  NULL,
    [BasicSalary]          DECIMAL (18, 2)  NULL,
    [AbsentDays]           INT              NULL,
    [BenefitGiven]         DECIMAL (18, 2)  NULL,
    [EarnLeaveAmount]      DECIMAL (18, 2)  NULL,
    [ServiceBenefitAmount] DECIMAL (18, 2)  NULL,
    [TotalAmountPaid]      DECIMAL (18, 2)  NULL,
    [AttendanceBonus]      DECIMAL (18, 2)  NULL,
    [AbsentFee]            DECIMAL (18, 2)  NULL,
    [Advance]              DECIMAL (18, 2)  NULL,
    [OtherDeduction]       DECIMAL (18, 2)  NULL,
    [StampAmount]          DECIMAL (18, 2)  NULL,
    [TotalDeduction]       DECIMAL (18, 2)  NULL,
    [NetAmount]            DECIMAL (18, 2)  NULL,
    [NetAmountInWord]      NVARCHAR (200)   NULL,
    [PreparationDate]      NVARCHAR (50)    NULL,
    CONSTRAINT [PK_FinalSettlement] PRIMARY KEY CLUSTERED ([FinalSettlementId] ASC)
);

