CREATE TABLE [dbo].[Inventory_MaterialIssueDetail] (
    [MaterialIssueDetailId] INT              IDENTITY (1, 1) NOT NULL,
    [MaterialIssueId]       INT              NOT NULL,
    [ItemId]                INT              NOT NULL,
    [SizeId]                INT              NULL,
    [BrandId]               INT              NULL,
    [OriginId]              INT              NULL,
    [MachineId]             INT              NULL,
    [TransactionDate]       DATETIME         NULL,
    [RequiredQuantity]      DECIMAL (18, 2)  NOT NULL,
    [IssuedQuantity]        DECIMAL (18, 2)  NOT NULL,
    [IssuedItemRate]        DECIMAL (18, 2)  NOT NULL,
    [StockInHand]           DECIMAL (18, 2)  NOT NULL,
    [CurrencyId]            INT              NOT NULL,
    [Remarks]               NVARCHAR (MAX)   NULL,
    [CreatedDate]           DATETIME         NULL,
    [CreatedBy]             UNIQUEIDENTIFIER NULL,
    [EditedDate]            DATETIME         NULL,
    [EditedBy]              UNIQUEIDENTIFIER NULL,
    [IsActive]              BIT              CONSTRAINT [DF_Inventory_MaterialIssueDetail_IsActive] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_Inventory_MaterialIssueDetail] PRIMARY KEY CLUSTERED ([MaterialIssueDetailId] ASC),
    CONSTRAINT [FK_Inventory_MaterialIssueDetail_Country] FOREIGN KEY ([OriginId]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [FK_Inventory_MaterialIssueDetail_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [dbo].[Currency] ([CurrencyId]),
    CONSTRAINT [FK_Inventory_MaterialIssueDetail_Inventory_Brand] FOREIGN KEY ([BrandId]) REFERENCES [dbo].[Inventory_Brand] ([BrandId]),
    CONSTRAINT [FK_Inventory_MaterialIssueDetail_Inventory_Item] FOREIGN KEY ([ItemId]) REFERENCES [dbo].[Inventory_Item] ([ItemId]),
    CONSTRAINT [FK_Inventory_MaterialIssueDetail_Inventory_MaterialIssue] FOREIGN KEY ([MaterialIssueId]) REFERENCES [dbo].[Inventory_MaterialIssue] ([MaterialIssueId]),
    CONSTRAINT [FK_Inventory_MaterialIssueDetail_Inventory_Size] FOREIGN KEY ([SizeId]) REFERENCES [dbo].[Inventory_Size] ([SizeId]),
    CONSTRAINT [FK_Inventory_MaterialIssueDetail_Production_Machine] FOREIGN KEY ([MachineId]) REFERENCES [dbo].[Production_Machine] ([MachineId])
);

