CREATE TABLE [dbo].[Inventory_MaterialReceiveAgainstPo] (
    [MaterialReceiveAgstPoId] BIGINT           IDENTITY (1, 1) NOT NULL,
    [RefNo]                   VARCHAR (10)     NOT NULL,
    [LcNo]                    VARCHAR (150)    NULL,
    [BuyerId]                 BIGINT           NULL,
    [OrderNo]                 VARCHAR (150)    NULL,
    [StyleNo]                 VARCHAR (150)    NULL,
    [CompId]                  VARCHAR (3)      NULL,
    [SupplierId]              INT              NOT NULL,
    [StoreId]                 INT              NOT NULL,
    [MRRNo]                   CHAR (15)        NULL,
    [MRRDate]                 DATETIME         NOT NULL,
    [VoucherNo]               VARCHAR (50)     NULL,
    [InvoiceNo]               VARCHAR (25)     NULL,
    [InvoiceDate]             DATETIME         NOT NULL,
    [ReceiveRegNo]            VARCHAR (25)     NULL,
    [ReceiveRegDate]          DATETIME         NOT NULL,
    [GateEntryNo]             VARCHAR (25)     NOT NULL,
    [GateEntryDate]           DATETIME         NOT NULL,
    [PoNo]                    VARCHAR (15)     NULL,
    [RType]                   CHAR (1)         NOT NULL,
    [PoDate]                  DATETIME         NULL,
    [TotalAmount]             DECIMAL (18, 5)  NOT NULL,
    [PayRef]                  VARCHAR (8)      NULL,
    [TotalDiscount]           DECIMAL (18, 5)  NULL,
    [NetAmount]               DECIMAL (18, 5)  NULL,
    [Remarks]                 NVARCHAR (250)   NULL,
    [EmployeeId]              UNIQUEIDENTIFIER NULL,
    [QcStatus]                BIT              NOT NULL,
    [GrnStatus]               BIT              NOT NULL,
    [QcDate]                  DATE             NULL,
    [GrnDate]                 DATE             NULL,
    [GrnRemarks]              NVARCHAR (250)   NULL,
    [QcRemarks]               NVARCHAR (250)   NULL,
    [OrderStyleRefId]         VARCHAR (7)      NULL,
    CONSTRAINT [PK_Inventory_MaterialReceiveAgainstPo] PRIMARY KEY CLUSTERED ([MaterialReceiveAgstPoId] ASC),
    CONSTRAINT [FK_Inventory_MaterialReceiveAgainstPo_Mrc_SupplierCompany] FOREIGN KEY ([SupplierId]) REFERENCES [dbo].[Mrc_SupplierCompany] ([SupplierCompanyId])
);

