CREATE TABLE [dbo].[Inventory_StoreLedger] (
    [StoreLedgerId]        INT              IDENTITY (1, 1) NOT NULL,
    [ItemId]               INT              NOT NULL,
    [SizeId]               INT              NULL,
    [BrandId]              INT              NULL,
    [OriginId]             INT              NULL,
    [GoodsReceivingNoteId] INT              NULL,
    [MaterialIssueId]      INT              NULL,
    [TransactionType]      NVARCHAR (100)   NOT NULL,
    [TransactionDate]      DATE             NOT NULL,
    [Quantity]             DECIMAL (18, 2)  NOT NULL,
    [UnitPrice]            DECIMAL (18, 5)  NOT NULL,
    [Amount]               DECIMAL (18, 5)  NOT NULL,
    [CurrencyId]           INT              NOT NULL,
    [CreatedDate]          DATETIME         NULL,
    [CreatedBy]            UNIQUEIDENTIFIER NULL,
    [EditedDate]           DATETIME         NULL,
    [EditedBy]             UNIQUEIDENTIFIER NULL,
    [IsActive]             BIT              CONSTRAINT [DF_Inventory_StoreLedger_IsActive] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_Inventory_StoreLedger] PRIMARY KEY CLUSTERED ([StoreLedgerId] ASC),
    CONSTRAINT [FK_Inventory_StoreLedger_Country] FOREIGN KEY ([OriginId]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [FK_Inventory_StoreLedger_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [dbo].[Currency] ([CurrencyId]),
    CONSTRAINT [FK_Inventory_StoreLedger_Inventory_Brand] FOREIGN KEY ([BrandId]) REFERENCES [dbo].[Inventory_Brand] ([BrandId]),
    CONSTRAINT [FK_Inventory_StoreLedger_Inventory_GoodsReceivingNote] FOREIGN KEY ([GoodsReceivingNoteId]) REFERENCES [dbo].[Inventory_GoodsReceivingNote] ([GoodsReceivingNotesId]),
    CONSTRAINT [FK_Inventory_StoreLedger_Inventory_Item] FOREIGN KEY ([ItemId]) REFERENCES [dbo].[Inventory_Item] ([ItemId]),
    CONSTRAINT [FK_Inventory_StoreLedger_Inventory_MaterialIssue] FOREIGN KEY ([MaterialIssueId]) REFERENCES [dbo].[Inventory_MaterialIssue] ([MaterialIssueId]),
    CONSTRAINT [FK_Inventory_StoreLedger_Inventory_Size] FOREIGN KEY ([SizeId]) REFERENCES [dbo].[Inventory_Size] ([SizeId])
);

