CREATE TABLE [dbo].[Inventory_StorePurchaseRequisitionDetail] (
    [StorePurchaseRequisitionDetailId]   INT              IDENTITY (1, 1) NOT NULL,
    [StorePurchaseRequisitionId]         INT              NOT NULL,
    [ItemId]                             INT              NOT NULL,
    [Description]                        NVARCHAR (MAX)   NULL,
    [SizeId]                             INT              NULL,
    [BrandId]                            INT              NULL,
    [OriginId]                           INT              NULL,
    [Quantity]                           DECIMAL (18, 2)  NOT NULL,
    [DesiredDate]                        DATETIME         NULL,
    [IsReceived]                         BIT              NOT NULL,
    [FunctionalArea]                     NVARCHAR (100)   NOT NULL,
    [SuppliedUptoDate]                   NVARCHAR (100)   NULL,
    [StockInHand]                        NVARCHAR (100)   NULL,
    [LastUnitPrice]                      DECIMAL (18, 2)  NULL,
    [EstimatedYearlyRequirement]         NVARCHAR (100)   NULL,
    [ModifiedRequiredQuantity]           DECIMAL (18, 2)  NULL,
    [ApprovedQuantity]                   DECIMAL (18, 2)  NULL,
    [ApprovalDate]                       DATETIME         NULL,
    [ApprovalStatusId]                   INT              NOT NULL,
    [RemarksOfRequisitionApprovalPerson] NVARCHAR (MAX)   NULL,
    [Quotation]                          NVARCHAR (MAX)   NULL,
    [ApprovedPurchase]                   NVARCHAR (MAX)   NULL,
    [PresentRate]                        DECIMAL (18, 2)  NOT NULL,
    [RemarksOfPurchaseApprovalPerson]    NVARCHAR (MAX)   NULL,
    [CreatedDate]                        DATETIME         NULL,
    [CreatedBy]                          UNIQUEIDENTIFIER NULL,
    [EditedBy]                           UNIQUEIDENTIFIER NULL,
    [EditedDate]                         DATETIME         NULL,
    [IsActive]                           BIT              CONSTRAINT [DF_Inventory_StorePurchaseRequisitionDetail_IsActive] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_Inventory_StorePurchaseRequisitionDetail] PRIMARY KEY CLUSTERED ([StorePurchaseRequisitionDetailId] ASC),
    CONSTRAINT [FK_Inventory_StorePurchaseRequisitionDetail_Country] FOREIGN KEY ([OriginId]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [FK_Inventory_StorePurchaseRequisitionDetail_Inventory_ApprovalStatus] FOREIGN KEY ([ApprovalStatusId]) REFERENCES [dbo].[Inventory_ApprovalStatus] ([ApprovalStatusId]),
    CONSTRAINT [FK_Inventory_StorePurchaseRequisitionDetail_Inventory_Brand] FOREIGN KEY ([BrandId]) REFERENCES [dbo].[Inventory_Brand] ([BrandId]),
    CONSTRAINT [FK_Inventory_StorePurchaseRequisitionDetail_Inventory_Item] FOREIGN KEY ([ItemId]) REFERENCES [dbo].[Inventory_Item] ([ItemId]),
    CONSTRAINT [FK_Inventory_StorePurchaseRequisitionDetail_Inventory_Size] FOREIGN KEY ([SizeId]) REFERENCES [dbo].[Inventory_Size] ([SizeId]),
    CONSTRAINT [FK_Inventory_StorePurchaseRequisitionDetail_Inventory_StorePurchaseRequisition] FOREIGN KEY ([StorePurchaseRequisitionId]) REFERENCES [dbo].[Inventory_StorePurchaseRequisition] ([StorePurchaseRequisitionId])
);

