CREATE TABLE [dbo].[Inventory_StyleShipment] (
    [StyleShipmentId]    BIGINT           IDENTITY (1, 1) NOT NULL,
    [StyleShipmentRefId] VARCHAR (8)      NOT NULL,
    [InvoiceNo]          VARCHAR (20)     NOT NULL,
    [InvoiceDate]        DATETIME         NULL,
    [Messrs]             NVARCHAR (200)   NOT NULL,
    [Address]            NVARCHAR (MAX)   NOT NULL,
    [DepoName]           VARCHAR (200)    NULL,
    [Through]            VARCHAR (100)    NOT NULL,
    [ThroughCellNo]      VARCHAR (20)     NULL,
    [VehicleNo]          VARCHAR (20)     NULL,
    [DriverName]         VARCHAR (50)     NULL,
    [DriverLicenceNo]    VARCHAR (20)     NULL,
    [DriverCellNo]       VARCHAR (50)     NULL,
    [DriverNid]          VARCHAR (20)     NULL,
    [BuyerRefId]         VARCHAR (3)      NOT NULL,
    [OrderNo]            VARCHAR (12)     NOT NULL,
    [OrderStyleRefId]    VARCHAR (7)      NOT NULL,
    [ShipmentMode]       VARCHAR (5)      NOT NULL,
    [CompId]             VARCHAR (3)      NOT NULL,
    [PrepairedBy]        UNIQUEIDENTIFIER NULL,
    [IsApproved]         BIT              NOT NULL,
    [ApprovedBy]         UNIQUEIDENTIFIER NULL,
    [Remarks]            VARCHAR (200)    NULL,
    [LockNo]             VARCHAR (20)     NULL,
    [ShipDate]           DATETIME         NULL,
    CONSTRAINT [PK_Inventory_StyleShipment] PRIMARY KEY CLUSTERED ([StyleShipmentId] ASC)
);

