CREATE TABLE [dbo].[Mrc_EmbellishmentDevelopmentDetail] (
    [EmbellishmentDevelopmentDetailId] INT              IDENTITY (1, 1) NOT NULL,
    [EmbellishmentId]                  INT              NOT NULL,
    [EmbellishmentDevelopmentId]       INT              NOT NULL,
    [CurrencyId]                       INT              NULL,
    [SendingStatusId]                  INT              NOT NULL,
    [ReadyStatusId]                    INT              NOT NULL,
    [SupplierId]                       INT              NULL,
    [Quantity]                         NUMERIC (18, 3)  NOT NULL,
    [UnitOfMeasure]                    NVARCHAR (50)    NULL,
    [Price]                            NUMERIC (18, 3)  NULL,
    [ImageUrl]                         NVARCHAR (MAX)   NULL,
    [SendingDate]                      DATETIME         NOT NULL,
    [PlannedStartDate]                 DATETIME         NULL,
    [PlannedEndDate]                   DATETIME         NULL,
    [ActualStartDate]                  DATETIME         NULL,
    [ActualEndDate]                    DATETIME         NULL,
    [CreatedDate]                      DATETIME         NULL,
    [CreatedBy]                        UNIQUEIDENTIFIER NULL,
    [EditedDate]                       DATETIME         NULL,
    [EditedBy]                         UNIQUEIDENTIFIER NULL,
    [IsActive]                         BIT              NOT NULL,
    CONSTRAINT [PK_Mrc_EmbellishmentDevelopmentDetail] PRIMARY KEY CLUSTERED ([EmbellishmentDevelopmentDetailId] ASC),
    CONSTRAINT [FK_Mrc_EmbellishmentDevelopmentDetail_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [dbo].[Currency] ([CurrencyId]),
    CONSTRAINT [FK_Mrc_EmbellishmentDevelopmentDetail_Mrc_Embellishment] FOREIGN KEY ([EmbellishmentId]) REFERENCES [dbo].[Mrc_Embellishment] ([EmbellishmentId]),
    CONSTRAINT [FK_Mrc_EmbellishmentDevelopmentDetail_Mrc_EmbellishmentDevelopment] FOREIGN KEY ([EmbellishmentDevelopmentId]) REFERENCES [dbo].[Mrc_EmbellishmentDevelopment] ([EmbellishmentDevelopmentId]),
    CONSTRAINT [FK_Mrc_EmbellishmentDevelopmentDetail_Mrc_ReadyStatus] FOREIGN KEY ([ReadyStatusId]) REFERENCES [dbo].[Mrc_ReadyStatus] ([ReadyStatusId]),
    CONSTRAINT [FK_Mrc_EmbellishmentDevelopmentDetail_Mrc_SendingStatus] FOREIGN KEY ([SendingStatusId]) REFERENCES [dbo].[Mrc_SendingStatus] ([SendingStatusId]),
    CONSTRAINT [FK_Mrc_EmbellishmentDevelopmentDetail_Mrc_SupplierCompany] FOREIGN KEY ([SupplierId]) REFERENCES [dbo].[Mrc_SupplierCompany] ([SupplierCompanyId])
);

