CREATE TABLE [dbo].[Mrc_TrimsAndAccessoriesDevelopmentDetail] (
    [TrimsAndAccessoriesDevelopmentDetailId] INT              IDENTITY (1, 1) NOT NULL,
    [TrimsAndAccessoriesDevelopmentId]       INT              NOT NULL,
    [SendingStatusId]                        INT              NOT NULL,
    [CurrencyId]                             INT              NULL,
    [TrimsAndAccessoriesId]                  INT              NOT NULL,
    [ReadyStatusId]                          INT              NOT NULL,
    [SupplierId]                             INT              NULL,
    [Quantity]                               NUMERIC (18, 3)  NOT NULL,
    [UnitOfMeasure]                          NVARCHAR (50)    NULL,
    [Price]                                  NUMERIC (18, 3)  NULL,
    [ImageUrl]                               NVARCHAR (MAX)   NULL,
    [SendingDate]                            DATETIME         NOT NULL,
    [PlannedStartDate]                       DATETIME         NULL,
    [PlannedEndDate]                         DATETIME         NULL,
    [ActualStartDate]                        DATETIME         NULL,
    [ActualEndDate]                          DATETIME         NULL,
    [CreatedDate]                            DATETIME         NULL,
    [CreatedBy]                              UNIQUEIDENTIFIER NULL,
    [EditedDate]                             DATETIME         NULL,
    [EditedBy]                               UNIQUEIDENTIFIER NULL,
    [IsActive]                               BIT              NOT NULL,
    CONSTRAINT [PK_Mrc_TrimAndAccessoriesDevelopmentDetail] PRIMARY KEY CLUSTERED ([TrimsAndAccessoriesDevelopmentDetailId] ASC),
    CONSTRAINT [FK_Mrc_TrimsAndAccessoriesDevelopmentDetail_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [dbo].[Currency] ([CurrencyId]),
    CONSTRAINT [FK_Mrc_TrimsAndAccessoriesDevelopmentDetail_Mrc_ReadyStatus] FOREIGN KEY ([ReadyStatusId]) REFERENCES [dbo].[Mrc_ReadyStatus] ([ReadyStatusId]),
    CONSTRAINT [FK_Mrc_TrimsAndAccessoriesDevelopmentDetail_Mrc_SendingStatus] FOREIGN KEY ([SendingStatusId]) REFERENCES [dbo].[Mrc_SendingStatus] ([SendingStatusId]),
    CONSTRAINT [FK_Mrc_TrimsAndAccessoriesDevelopmentDetail_Mrc_SupplierCompany] FOREIGN KEY ([SupplierId]) REFERENCES [dbo].[Mrc_SupplierCompany] ([SupplierCompanyId]),
    CONSTRAINT [FK_Mrc_TrimsAndAccessoriesDevelopmentDetail_Mrc_TrimsAndAccessories] FOREIGN KEY ([TrimsAndAccessoriesId]) REFERENCES [dbo].[Mrc_TrimsAndAccessories] ([TrimsAndAccessoriesId]),
    CONSTRAINT [FK_Mrc_TrimsAndAccessoriesDevelopmentDetail_Mrc_TrimsAndAccessoriesDevelopment1] FOREIGN KEY ([TrimsAndAccessoriesDevelopmentId]) REFERENCES [dbo].[Mrc_TrimsAndAccessoriesDevelopment] ([TrimsAndAccessoriesDevelopmentId])
);

