CREATE TABLE [dbo].[Mrc_LabDipDevelopmentHistory] (
    [LabDipDevelopmentHistoryId] INT              IDENTITY (1, 1) NOT NULL,
    [SpecSheetId]                INT              NOT NULL,
    [DepartmentId]               INT              NULL,
    [CurrencyId]                 INT              NULL,
    [ResponsiblePersonId]        UNIQUEIDENTIFIER NULL,
    [LabRoomSendingStatusId]     INT              NULL,
    [KeyProcessId]               INT              NOT NULL,
    [LabDipReadyStatusId]        INT              NULL,
    [LabRoomSendingDate]         DATETIME         NULL,
    [PlannedStartDate]           DATETIME         NULL,
    [PlannedEndDate]             DATETIME         NULL,
    [ActualStartDate]            DATETIME         NULL,
    [ActualEndDate]              DATETIME         NULL,
    [FabricationId]              INT              NULL,
    [Quantity]                   INT              NULL,
    [LabDipPrice]                DECIMAL (18, 3)  NULL,
    [CreatedDate]                DATETIME         NULL,
    [CreatedBy]                  UNIQUEIDENTIFIER NULL,
    [EditedDate]                 DATETIME         NULL,
    [EditedBy]                   UNIQUEIDENTIFIER NULL,
    [IsActive]                   BIT              NOT NULL,
    CONSTRAINT [PK_Mrc_LabDipDevelopmentHistory] PRIMARY KEY CLUSTERED ([LabDipDevelopmentHistoryId] ASC),
    CONSTRAINT [FK_Mrc_LabDipDevelopmentHistory_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [dbo].[Currency] ([CurrencyId]),
    CONSTRAINT [FK_Mrc_LabDipDevelopmentHistory_Department] FOREIGN KEY ([DepartmentId]) REFERENCES [dbo].[Department] ([Id]),
    CONSTRAINT [FK_Mrc_LabDipDevelopmentHistory_Employee] FOREIGN KEY ([ResponsiblePersonId]) REFERENCES [dbo].[Employee] ([EmployeeId]),
    CONSTRAINT [FK_Mrc_LabDipDevelopmentHistory_Mrc_Fabrication] FOREIGN KEY ([FabricationId]) REFERENCES [dbo].[Mrc_Fabrication] ([FabricationId]),
    CONSTRAINT [FK_Mrc_LabDipDevelopmentHistory_Mrc_KeyProcess] FOREIGN KEY ([KeyProcessId]) REFERENCES [dbo].[Mrc_KeyProcess] ([KeyProcessId]),
    CONSTRAINT [FK_Mrc_LabDipDevelopmentHistory_Mrc_ReadyStatus] FOREIGN KEY ([LabDipReadyStatusId]) REFERENCES [dbo].[Mrc_ReadyStatus] ([ReadyStatusId]),
    CONSTRAINT [FK_Mrc_LabDipDevelopmentHistory_Mrc_SendingStatus] FOREIGN KEY ([LabRoomSendingStatusId]) REFERENCES [dbo].[Mrc_SendingStatus] ([SendingStatusId]),
    CONSTRAINT [FK_Mrc_LabDipDevelopmentHistory_Mrc_SpecificationSheet] FOREIGN KEY ([SpecSheetId]) REFERENCES [dbo].[Mrc_SpecificationSheet] ([SpecificationSheetId])
);

