CREATE TABLE [dbo].[Mrc_SpecificationSheet] (
    [SpecificationSheetId]   INT              IDENTITY (1, 1) NOT NULL,
    [BuyerId]                INT              NOT NULL,
    [ContactPersonId]        INT              NOT NULL,
    [MerchandiserId]         UNIQUEIDENTIFIER NOT NULL,
    [StyleNo]                NVARCHAR (100)   NOT NULL,
    [JobNo]                  NVARCHAR (100)   NOT NULL,
    [ReferenceNo]            NVARCHAR (100)   NULL,
    [Department]             NVARCHAR (100)   NULL,
    [Season]                 NVARCHAR (100)   NULL,
    [Brand]                  NVARCHAR (100)   NULL,
    [StyleDescription]       NVARCHAR (MAX)   NULL,
    [FabricationDescription] NVARCHAR (MAX)   NULL,
    [Material]               NVARCHAR (100)   NULL,
    [Finishing]              NVARCHAR (100)   NULL,
    [ItemGroup]              NVARCHAR (100)   NULL,
    [SizeRange]              NVARCHAR (100)   NULL,
    [ApproximateQuantity]    NVARCHAR (100)   NULL,
    [LeadTimeInDays]         NVARCHAR (100)   NULL,
    [EntryDate]              DATETIME         NULL,
    [ShipmentDate]           DATETIME         NULL,
    [Remarks]                NVARCHAR (MAX)   NULL,
    [CreatedDate]            DATETIME         NULL,
    [CreatedBy]              UNIQUEIDENTIFIER NULL,
    [EditedDate]             DATETIME         NULL,
    [EditedBy]               UNIQUEIDENTIFIER NULL,
    [IsActive]               BIT              NOT NULL,
    CONSTRAINT [PK_SpecSheet] PRIMARY KEY CLUSTERED ([SpecificationSheetId] ASC),
    CONSTRAINT [FK_Mrc_SpecificationSheet_Employee] FOREIGN KEY ([MerchandiserId]) REFERENCES [dbo].[Employee] ([EmployeeId]),
    CONSTRAINT [FK_Mrc_SpecificationSheet_Mrc_Buyer] FOREIGN KEY ([BuyerId]) REFERENCES [dbo].[Mrc_Buyer] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_Mrc_SpecificationSheet_Mrc_BuyerContactPerson] FOREIGN KEY ([ContactPersonId]) REFERENCES [dbo].[Mrc_BuyerContactPerson] ([Id])
);

