CREATE TABLE [dbo].[Mrc_TrimsAndAccessoriesSubmissionHistory] (
    [TrimsAndAccessoriesSubmissionHistoryId] INT              IDENTITY (1, 1) NOT NULL,
    [SpecSheetId]                            INT              NOT NULL,
    [KeyProcessId]                           INT              NOT NULL,
    [SendingStatusId]                        INT              NULL,
    [CurrencyId]                             INT              NULL,
    [DepartmentId]                           INT              NULL,
    [ResponsiblePersonId]                    UNIQUEIDENTIFIER NULL,
    [SubmissionPrice]                        NUMERIC (18, 3)  NULL,
    [PlannedStartDate]                       DATETIME         NULL,
    [PlannedEndDate]                         DATETIME         NULL,
    [ActualStartDate]                        DATETIME         NULL,
    [ActualEndDate]                          DATETIME         NULL,
    [Remarks]                                NVARCHAR (MAX)   NULL,
    [CreatedDate]                            DATETIME         NULL,
    [CreatedBy]                              UNIQUEIDENTIFIER NULL,
    [EditedDate]                             DATETIME         NULL,
    [EditedBy]                               UNIQUEIDENTIFIER NULL,
    [IsActive]                               BIT              NOT NULL,
    CONSTRAINT [PK_Mrc_TrimsAndAccessoriesSubmissionHistory] PRIMARY KEY CLUSTERED ([TrimsAndAccessoriesSubmissionHistoryId] ASC),
    CONSTRAINT [FK_Mrc_TrimsAndAccessoriesSubmissionHistory_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [dbo].[Currency] ([CurrencyId]),
    CONSTRAINT [FK_Mrc_TrimsAndAccessoriesSubmissionHistory_Department] FOREIGN KEY ([DepartmentId]) REFERENCES [dbo].[Department] ([Id]),
    CONSTRAINT [FK_Mrc_TrimsAndAccessoriesSubmissionHistory_Employee] FOREIGN KEY ([ResponsiblePersonId]) REFERENCES [dbo].[Employee] ([EmployeeId]),
    CONSTRAINT [FK_Mrc_TrimsAndAccessoriesSubmissionHistory_Mrc_KeyProcess] FOREIGN KEY ([KeyProcessId]) REFERENCES [dbo].[Mrc_KeyProcess] ([KeyProcessId]),
    CONSTRAINT [FK_Mrc_TrimsAndAccessoriesSubmissionHistory_Mrc_SendingStatus] FOREIGN KEY ([SendingStatusId]) REFERENCES [dbo].[Mrc_SendingStatus] ([SendingStatusId]),
    CONSTRAINT [FK_Mrc_TrimsAndAccessoriesSubmissionHistory_Mrc_SpecificationSheet] FOREIGN KEY ([SpecSheetId]) REFERENCES [dbo].[Mrc_SpecificationSheet] ([SpecificationSheetId])
);

