CREATE TABLE [dbo].[Mrc_SampleDevelopmentHistory] (
    [SampleDevelopmentHistoryId] INT              IDENTITY (1, 1) NOT NULL,
    [SpecSheetId]                INT              NOT NULL,
    [SampleTypeId]               INT              NOT NULL,
    [DepartmentId]               INT              NULL,
    [ResponsiblePersonId]        UNIQUEIDENTIFIER NULL,
    [SampleRoomSendingStatusId]  INT              NULL,
    [SampleRoomSendingDate]      DATETIME         NULL,
    [SampleReadyStatusId]        INT              NULL,
    [PlannedStartDate]           DATETIME         NULL,
    [PlannedEndDate]             DATETIME         NULL,
    [ActualStartDate]            DATETIME         NULL,
    [ActualEndDate]              DATETIME         NULL,
    [KeyProcessId]               INT              NULL,
    [Fabrication]                NVARCHAR (MAX)   NULL,
    [Quantity]                   INT              NULL,
    [SamplePrice]                DECIMAL (18, 3)  NULL,
    [CurrencyId]                 INT              NULL,
    [CreatedDate]                DATETIME         NULL,
    [CreatedBy]                  UNIQUEIDENTIFIER NULL,
    [EditedDate]                 DATETIME         NULL,
    [EditedBy]                   UNIQUEIDENTIFIER NULL,
    [IsActive]                   BIT              NOT NULL,
    CONSTRAINT [PK_Mrc_SampleDevelopmentHistory] PRIMARY KEY CLUSTERED ([SampleDevelopmentHistoryId] ASC),
    CONSTRAINT [FK_Mrc_SampleDevelopmentHistory_Department] FOREIGN KEY ([DepartmentId]) REFERENCES [dbo].[Department] ([Id]),
    CONSTRAINT [FK_Mrc_SampleDevelopmentHistory_Mrc_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [dbo].[Currency] ([CurrencyId]),
    CONSTRAINT [FK_Mrc_SampleDevelopmentHistory_Mrc_KeyProcess] FOREIGN KEY ([KeyProcessId]) REFERENCES [dbo].[Mrc_KeyProcess] ([KeyProcessId]) ON DELETE CASCADE,
    CONSTRAINT [FK_Mrc_SampleDevelopmentHistory_Mrc_ReadyStatus] FOREIGN KEY ([SampleReadyStatusId]) REFERENCES [dbo].[Mrc_ReadyStatus] ([ReadyStatusId]),
    CONSTRAINT [FK_Mrc_SampleDevelopmentHistory_Mrc_SampleType] FOREIGN KEY ([SampleTypeId]) REFERENCES [dbo].[Mrc_SampleType] ([SampleTypeId]),
    CONSTRAINT [FK_Mrc_SampleDevelopmentHistory_Mrc_SendingStatus] FOREIGN KEY ([SampleRoomSendingStatusId]) REFERENCES [dbo].[Mrc_SendingStatus] ([SendingStatusId]),
    CONSTRAINT [FK_Mrc_SampleDevelopmentHistory_Mrc_SpecificationSheet] FOREIGN KEY ([SpecSheetId]) REFERENCES [dbo].[Mrc_SpecificationSheet] ([SpecificationSheetId]) ON DELETE CASCADE
);

