CREATE TABLE [dbo].[Mrc_OrderInformation] (
    [OrderId]            INT              IDENTITY (1, 1) NOT NULL,
    [SpecSheetId]        INT              NOT NULL,
    [OrderNo]            NVARCHAR (100)   NOT NULL,
    [SupplierId]         INT              NULL,
    [BuyerClientId]      INT              NULL,
    [ArticleNo]          NVARCHAR (100)   NULL,
    [PricePerDozen]      DECIMAL (18, 2)  NULL,
    [FabricConsumption]  DECIMAL (18, 2)  NULL,
    [FabricWeight]       DECIMAL (18, 2)  NULL,
    [TotalQuantity]      DECIMAL (18, 2)  NULL,
    [Remarks]            NVARCHAR (MAX)   NULL,
    [ShipmentDate]       DATETIME         NULL,
    [ExFactoryDateOnPO]  DATETIME         NULL,
    [ExFactoryAsPerPlan] DATETIME         NULL,
    [LeadTime]           INT              NULL,
    [NumberOfCarton]     INT              NULL,
    [TotalAmount]        INT              NULL,
    [CurrencyId]         INT              NULL,
    [PaymentTermId]      INT              NULL,
    [CreatedDate]        DATETIME         NULL,
    [CreatedBy]          UNIQUEIDENTIFIER NULL,
    [EditedDate]         DATETIME         NULL,
    [EditedBy]           UNIQUEIDENTIFIER NULL,
    [IsActive]           BIT              NOT NULL,
    CONSTRAINT [PK_Mrc_Order] PRIMARY KEY CLUSTERED ([OrderId] ASC),
    CONSTRAINT [FK_Mrc_OrderInformation_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [dbo].[Currency] ([CurrencyId]),
    CONSTRAINT [FK_Mrc_OrderInformation_Mrc_BuyerClient] FOREIGN KEY ([BuyerClientId]) REFERENCES [dbo].[Mrc_BuyerClient] ([BuyerClientId]),
    CONSTRAINT [FK_Mrc_OrderInformation_Mrc_PaymentTerms] FOREIGN KEY ([PaymentTermId]) REFERENCES [dbo].[Mrc_PaymentTerms] ([PaymentTermId]),
    CONSTRAINT [FK_Mrc_OrderInformation_Mrc_SpecificationSheet] FOREIGN KEY ([SpecSheetId]) REFERENCES [dbo].[Mrc_SpecificationSheet] ([SpecificationSheetId]),
    CONSTRAINT [FK_Mrc_OrderInformation_Mrc_SupplierCompany] FOREIGN KEY ([SupplierId]) REFERENCES [dbo].[Mrc_SupplierCompany] ([SupplierCompanyId])
);

