CREATE TABLE [dbo].[OM_BuyOrdStyle] (
    [OrderStyleId]    BIGINT          IDENTITY (1, 1) NOT NULL,
    [CompId]          VARCHAR (3)     NULL,
    [OrderStyleRefId] NVARCHAR (7)    NULL,
    [StyleentDate]    DATE            NULL,
    [OrderNo]         VARCHAR (50)    NULL,
    [StyleRefId]      VARCHAR (4)     NULL,
    [BuyerArt]        NVARCHAR (50)   NULL,
    [SeasonRefId]     VARCHAR (2)     NULL,
    [BrandRefId]      VARCHAR (3)     NULL,
    [CatIRefId]       VARCHAR (3)     NULL,
    [Rmks]            NVARCHAR (200)  NULL,
    [Quantity]        DECIMAL (18, 2) NULL,
    [Rate]            DECIMAL (18, 2) NULL,
    [DiscPer]         NUMERIC (18, 2) NULL,
    [Discount]        NUMERIC (18, 2) NULL,
    [Amt]             NUMERIC (16, 4) NULL,
    [ProductionQty]   NUMERIC (18, 2) NULL,
    [WORKORDER]       VARCHAR (12)    NULL,
    [JobQty]          NUMERIC (8, 2)  NULL,
    [IsCostEstimated] BIT             NULL,
    [AllowancePer]    NUMERIC (8, 2)  NULL,
    [PackplanThru]    VARCHAR (1)     NULL,
    [Amend]           VARCHAR (1)     NULL,
    [YarnAmend]       VARCHAR (1)     NULL,
    [AccAmend]        VARCHAR (1)     NULL,
    [PackAmend]       VARCHAR (1)     NULL,
    [DespatchClosed]  VARCHAR (1)     NULL,
    [despatchQty]     NUMERIC (8)     NULL,
    [UnitType]        VARCHAR (1)     NULL,
    [CutGAmend]       VARCHAR (1)     NULL,
    [GroupedStyleId]  INT             NULL,
    [IsGrouped]       BIT             NULL,
    [TransferredTo]   VARCHAR (12)    NULL,
    [CompanyUnitId]   INT             NULL,
    [Transfer]        CHAR (1)        NULL,
    [BaseUnit]        INT             NULL,
    [EnquiryId]       INT             NULL,
    [BuyerItem]       VARCHAR (40)    NULL,
    [OpenPrgAmend]    VARCHAR (1)     NULL,
    [GUOMid]          INT             NULL,
    [GUomConv]        SMALLINT        NULL,
    [StyleGroupId]    INT             NULL,
    [StyleDeptId]     INT             NULL,
    [QCId]            INT             NULL,
    [QuotationId]     INT             NULL,
    [GroupItem]       VARCHAR (1)     NULL,
    [FitId]           INT             NULL,
    [MisView]         VARCHAR (1)     NULL,
    [PI]              CHAR (30)       NULL,
    [LCSTID]          VARCHAR (1)     NULL,
    [YBD]             DATE            NULL,
    [YRD]             DATE            NULL,
    [FBD]             DATE            NULL,
    [KSD]             DATE            NULL,
    [KCD]             DATE            NULL,
    [DSD]             DATE            NULL,
    [DCD]             DATE            NULL,
    [PAD]             DATE            NULL,
    [CSD]             DATE            NULL,
    [CCD]             DATE            NULL,
    [IPD]             DATE            NULL,
    [SSD]             DATE            NULL,
    [SCD]             DATE            NULL,
    [FSD]             DATE            NULL,
    [FCD]             DATE            NULL,
    [IND]             DATE            NULL,
    [EFD]             DATE            NULL,
    [EXD]             DATE            NULL,
    [PSD]             DATE            NULL,
    [LCR]             DATE            NULL,
    [YID]             DATE            NULL,
    [AID]             DATE            NULL,
    [KnMC]            INT             NULL,
    [Factory]         VARCHAR (30)    NULL,
    [KnProd]          NUMERIC (18, 2) NULL,
    [KnDays]          INT             NULL,
    [LnDays]          INT             NULL,
    [LCD]             DATE            NULL,
    [BZF]             DATE            NULL,
    [EMF]             DATE            NULL,
    [ABD]             DATE            NULL,
    [TAD]             DATE            NULL,
    [PPSD]            DATE            NULL,
    [PPMD]            DATE            NULL,
    [PSND]            DATE            NULL,
    [PRD]             DATE            NULL,
    [ESD]             DATE            NULL,
    [CCRD]            DATE            NULL,
    [LDSD]            DATE            NULL,
    [LDAD]            DATE            NULL,
    [FID]             DATE            NULL,
    [THRD]            DATE            NULL,
    [WSD]             DATE            NULL,
    [WRD]             DATE            NULL,
    [FBDD]            DATE            NULL,
    [FSource]         VARCHAR (50)    NULL,
    [ActYBD]          DATE            NULL,
    [ActYRD]          DATE            NULL,
    [ActFBD]          DATE            NULL,
    [ActKSD]          DATE            NULL,
    [ActKCD]          DATE            NULL,
    [ActDSD]          DATE            NULL,
    [ActDCD]          DATE            NULL,
    [ActPAD]          DATE            NULL,
    [ActCSD]          DATE            NULL,
    [ActCCD]          DATE            NULL,
    [ActIPD]          DATE            NULL,
    [ActSSD]          DATE            NULL,
    [ActSCD]          DATE            NULL,
    [ActFSD]          DATE            NULL,
    [ActFCD]          DATE            NULL,
    [ActIND]          DATE            NULL,
    [ActEFD]          DATE            NULL,
    [ActEXD]          DATE            NULL,
    [ActPSD]          DATE            NULL,
    [ActYID]          DATE            NULL,
    [ActAID]          DATE            NULL,
    [ActLCD]          DATE            NULL,
    [ActBZD]          DATE            NULL,
    [ActEMF]          DATE            NULL,
    [ActABD]          DATE            NULL,
    [ActTAD]          DATE            NULL,
    [ActPPSD]         DATE            NULL,
    [ActPPMD]         DATE            NULL,
    [ActPSND]         DATE            NULL,
    [ActPRD]          DATE            NULL,
    [ActESD]          DATE            NULL,
    [ActCCRD]         DATE            NULL,
    [ActLDSD]         DATE            NULL,
    [ActLDAD]         DATE            NULL,
    [ActFID]          DATE            NULL,
    [ActTHRD]         DATE            NULL,
    [ActWSD]          DATE            NULL,
    [ActWRD]          DATE            NULL,
    [ActFBDD]         DATE            NULL,
    [ActBZF]          DATE            NULL,
    [SAPD]            DATE            NULL,
    [ActSAPD]         DATE            NULL,
    [CGRID]           VARCHAR (6)     NULL,
    [ActiveStatus]    BIT             NOT NULL,
    [TnaMode]         CHAR (1)        NULL,
    [ImagePath]       VARCHAR (300)   NULL,
    [TtlCm]           FLOAT (53)      NULL,
    [TtlSmv]          FLOAT (53)      NULL,
    CONSTRAINT [PK_OM_BuyOrdStyle] PRIMARY KEY CLUSTERED ([OrderStyleId] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IX_OM_BUYERORDERSTYLE_ORDERNOSTYLEREID]
    ON [dbo].[OM_BuyOrdStyle]([OrderStyleRefId] ASC);

