CREATE TABLE [dbo].[OM_SampleStyle] (
    [SampleStyleId] INT              IDENTITY (1, 1) NOT NULL,
    [StyleRefId]    CHAR (5)         NOT NULL,
    [SampleOrderId] INT              NOT NULL,
    [StyleNo]       VARCHAR (50)     NULL,
    [Fabrication]   VARCHAR (100)    NULL,
    [Gsm]           VARCHAR (50)     NULL,
    [ColorName]     VARCHAR (100)    NULL,
    [SizeName]      VARCHAR (100)    NULL,
    [FabQty]        FLOAT (53)       NULL,
    [ItemName]      VARCHAR (100)    NULL,
    [SampleType]    VARCHAR (100)    NULL,
    [SampleDate]    DATE             NULL,
    [EFDate]        DATE             NULL,
    [StyleQty]      INT              NULL,
    [Remarks]       VARCHAR (250)    NULL,
    [CompId]        CHAR (3)         NULL,
    [CreatedBy]     UNIQUEIDENTIFIER NOT NULL,
    [CreatedDate]   DATE             NOT NULL,
    [EditedBy]      UNIQUEIDENTIFIER NULL,
    [EditedDate]    DATE             NULL,
    [McDia]         VARCHAR (50)     NULL,
    [FinishDia]     VARCHAR (50)     NULL,
    [RibFab]        VARCHAR (150)    NULL,
    [RibQty]        FLOAT (53)       NULL,
    [ContasFab]     VARCHAR (150)    NULL,
    [ContasQty]     FLOAT (53)       NULL,
    CONSTRAINT [PK_OM_SampleStyle] PRIMARY KEY CLUSTERED ([SampleStyleId] ASC),
    CONSTRAINT [FK_OM_SampleStyle_OM_SampleOrder] FOREIGN KEY ([SampleOrderId]) REFERENCES [dbo].[OM_SampleOrder] ([SampleOrderId])
);

