CREATE TABLE [dbo].[OM_TempAssortShip] (
    [TempAssortId] BIGINT           IDENTITY (1, 1) NOT NULL,
    [CompId]       VARCHAR (3)      NULL,
    [UserId]       UNIQUEIDENTIFIER NULL,
    [ColorRow]     INT              NULL,
    [ColorRefId]   VARCHAR (4)      NULL,
    [C1]           INT              NULL,
    [C2]           INT              NULL,
    [C3]           INT              NULL,
    [C4]           INT              NULL,
    [C5]           INT              NULL,
    [C6]           INT              NULL,
    [C7]           INT              NULL,
    [C8]           INT              NULL,
    [C9]           INT              NULL,
    [C10]          INT              NULL,
    [C11]          INT              NULL,
    [C12]          INT              NULL,
    [C13]          INT              NULL,
    [C14]          INT              NULL,
    [C15]          INT              NULL,
    [C16]          INT              NULL,
    [C17]          INT              NULL,
    [C18]          INT              NULL,
    [C19]          INT              NULL,
    [C20]          INT              NULL,
    [C21]          INT              NULL,
    [C22]          INT              NULL,
    [C23]          INT              NULL,
    [C24]          INT              NULL,
    [C25]          INT              NULL,
    [Total]        INT              NULL
);

