CREATE TABLE [dbo].[OM_TNA] (
    [TnaRowId]        INT              IDENTITY (1, 1) NOT NULL,
    [CompId]          NVARCHAR (3)     NULL,
    [OrderStyleRefId] NVARCHAR (7)     NULL,
    [ActivityName]    NVARCHAR (200)   NULL,
    [SerialId]        INT              NULL,
    [LeadTime]        INT              NULL,
    [PSDate]          VARCHAR (20)     NULL,
    [PEDate]          VARCHAR (20)     NULL,
    [Rmks]            VARCHAR (100)    NULL,
    [XWho]            NVARCHAR (MAX)   NULL,
    [XWhen]           NVARCHAR (MAX)   NULL,
    [FlagValue]       NVARCHAR (3)     NULL,
    [SDate]           DATE             NULL,
    [ASDate]          VARCHAR (50)     NULL,
    [AEDate]          VARCHAR (50)     NULL,
    [Responsible]     NVARCHAR (MAX)   NULL,
    [UpdateRemarks]   NVARCHAR (MAX)   NULL,
    [ActiveStatus]    BIT              NULL,
    [CreatedBy]       UNIQUEIDENTIFIER NULL,
    [EditedBy]        UNIQUEIDENTIFIER NULL,
    [EditedDate]      DATETIME         NULL,
    [CreatedDate]     DATETIME         NULL,
    [ShortName]       VARCHAR (20)     NULL,
    [RequiredQty]     FLOAT (53)       NULL,
    [ActualQty]       FLOAT (53)       NULL,
    CONSTRAINT [PK_OM_TNA] PRIMARY KEY CLUSTERED ([TnaRowId] ASC)
);

