CREATE TABLE [dbo].[PFLDyeingDec16] (
    [Sl#]                            FLOAT (53)     NULL,
    [F2]                             NVARCHAR (255) NULL,
    [ID No]                          FLOAT (53)     NULL,
    [Name]                           NVARCHAR (255) NULL,
    [Designation]                    NVARCHAR (255) NULL,
    [Grade]                          FLOAT (53)     NULL,
    [Joining Date]                   DATETIME       NULL,
    [Attendance & Leave Information] FLOAT (53)     NULL,
    [F9]                             FLOAT (53)     NULL,
    [F10]                            FLOAT (53)     NULL,
    [F11]                            FLOAT (53)     NULL,
    [F12]                            FLOAT (53)     NULL,
    [F13]                            FLOAT (53)     NULL,
    [F14]                            FLOAT (53)     NULL,
    [Salary Information]             FLOAT (53)     NULL,
    [F16]                            FLOAT (53)     NULL,
    [F17]                            FLOAT (53)     NULL,
    [F18]                            FLOAT (53)     NULL,
    [F19]                            FLOAT (53)     NULL,
    [F20]                            FLOAT (53)     NULL,
    [Deduction Amount]               FLOAT (53)     NULL,
    [F22]                            FLOAT (53)     NULL,
    [F23]                            FLOAT (53)     NULL,
    [F24]                            FLOAT (53)     NULL,
    [F25]                            FLOAT (53)     NULL,
    [Over Time]                      FLOAT (53)     NULL,
    [F27]                            FLOAT (53)     NULL,
    [F28]                            FLOAT (53)     NULL,
    [Net Payable Amount]             FLOAT (53)     NULL,
    [Signature]                      NVARCHAR (255) NULL
);

