CREATE TABLE [dbo].[Pro_Batch] (
    [BatchId]            BIGINT           IDENTITY (1, 1) NOT NULL,
    [BtType]             INT              NULL,
    [BtRefNo]            NVARCHAR (8)     NULL,
    [BatchNo]            NVARCHAR (50)    NOT NULL,
    [BatchDate]          DATETIME         NULL,
    [PartyId]            BIGINT           NOT NULL,
    [MachineId]          INT              NOT NULL,
    [BatchQty]           DECIMAL (18, 2)  NULL,
    [ColorId]            BIGINT           NOT NULL,
    [BatchStatus]        INT              NOT NULL,
    [CreatedDate]        DATETIME         NULL,
    [CreatedBy]          UNIQUEIDENTIFIER NULL,
    [EditedDate]         DATETIME         NULL,
    [EditedBy]           UNIQUEIDENTIFIER NULL,
    [IsActive]           BIT              CONSTRAINT [DF_Pro_Batch_IsActive] DEFAULT ((1)) NOT NULL,
    [CompId]             VARCHAR (3)      NULL,
    [ItemId]             INT              NULL,
    [Gsm]                VARCHAR (50)     NULL,
    [GrColorRefId]       VARCHAR (4)      NULL,
    [FColorRefId]        VARCHAR (4)      NULL,
    [GSizeRefId]         VARCHAR (4)      NULL,
    [FSizeRefId]         VARCHAR (4)      NULL,
    [ShadePerc]          DECIMAL (18, 5)  NULL,
    [CostRate]           DECIMAL (18, 5)  NULL,
    [BillRate]           DECIMAL (18, 5)  NULL,
    [BuyerRefId]         VARCHAR (4)      NULL,
    [OrderNo]            VARCHAR (12)     NULL,
    [OrderStyleRefId]    VARCHAR (7)      NULL,
    [ConsumptionGroupId] INT              NULL,
    [ApprovedLdNo]       VARCHAR (50)     NULL,
    [Remarks]            VARCHAR (150)    NULL,
    [LoadingDateTime]    DATETIME         NULL,
    [UnLoadingDateTime]  DATETIME         NULL,
    [GroupSubProcessId]  INT              NULL,
    [JobRefId]           CHAR (6)         NULL,
    CONSTRAINT [PK_Pro_Batch] PRIMARY KEY CLUSTERED ([BatchId] ASC),
    CONSTRAINT [FK_Pro_Batch_Color] FOREIGN KEY ([ColorId]) REFERENCES [dbo].[Color] ([ColorId]),
    CONSTRAINT [FK_Pro_Batch_Party] FOREIGN KEY ([PartyId]) REFERENCES [dbo].[Party] ([PartyId]),
    CONSTRAINT [FK_Pro_Batch_Production_Machine] FOREIGN KEY ([MachineId]) REFERENCES [dbo].[Production_Machine] ([MachineId])
);

