CREATE TABLE [dbo].[ProcessedExtraOTTemp] (
    [Id]                     INT              NULL,
    [EmployeeId]             UNIQUEIDENTIFIER NOT NULL,
    [EmployeeCardId]         NVARCHAR (100)   NULL,
    [Name]                   NVARCHAR (100)   NULL,
    [CompanyId]              INT              NULL,
    [CompanyName]            NVARCHAR (100)   NULL,
    [CompanyAddress]         NVARCHAR (100)   NULL,
    [BranchId]               INT              NULL,
    [Branch]                 NVARCHAR (100)   NULL,
    [BranchUnitId]           INT              NULL,
    [Unit]                   NVARCHAR (100)   NULL,
    [BranchUnitDepartmentId] INT              NULL,
    [Department]             NVARCHAR (100)   NULL,
    [DepartmentSectionId]    INT              NULL,
    [Section]                NVARCHAR (100)   NULL,
    [DepartmentLineId]       INT              NULL,
    [Line]                   NVARCHAR (100)   NULL,
    [EmployeeTypeId]         INT              NULL,
    [EmployeeType]           NVARCHAR (100)   NULL,
    [Designation]            NVARCHAR (100)   NULL,
    [Grade]                  NVARCHAR (100)   NULL,
    [JoiningDate]            NVARCHAR (100)   NULL,
    [BasicSalary]            NUMERIC (18, 2)  NULL,
    [GrossSalary]            NUMERIC (18, 2)  NULL,
    [TotalExtraOTHour]       NUMERIC (18, 2)  NULL,
    [OTHourRate]             NUMERIC (18, 2)  NULL,
    [OTAmount]               NUMERIC (18, 2)  NULL,
    [MonthYear]              NVARCHAR (100)   NULL,
    [FromDate]               DATETIME         NULL,
    [ToDate]                 DATETIME         NULL,
    CONSTRAINT [PK_ProcessedExtraOTTemp] PRIMARY KEY CLUSTERED ([EmployeeId] ASC)
);

