CREATE TABLE [dbo].[RPTProdReceiveBalance] (
    [SL]               BIGINT         NULL,
    [ProcessRefId]     VARCHAR (3)    NOT NULL,
    [CompId]           VARCHAR (3)    NULL,
    [Factory]          NVARCHAR (100) NOT NULL,
    [PartyId]          BIGINT         NOT NULL,
    [CompanyName]      NVARCHAR (100) NOT NULL,
    [FullAddress]      NVARCHAR (MAX) NOT NULL,
    [OrderStyleRefId]  VARCHAR (7)    NULL,
    [IsPrint]          BIT            NOT NULL,
    [IsEmbroidery]     BIT            NOT NULL,
    [BuyerName]        NVARCHAR (100) NOT NULL,
    [OrderNo]          VARCHAR (30)   NULL,
    [StyleName]        NVARCHAR (100) NULL,
    [JobNo]            VARCHAR (50)   NULL,
    [CutRefNo]         VARCHAR (6)    NULL,
    [InvoiceNo]        VARCHAR (10)   NOT NULL,
    [InvDate]          DATE           NOT NULL,
    [Part]             NVARCHAR (100) NOT NULL,
    [ColorName]        NVARCHAR (50)  NOT NULL,
    [ColorRefId]       VARCHAR (4)    NULL,
    [Quantity]         INT            NULL,
    [SendingQty]       INT            NULL,
    [ChallanNo]        VARCHAR (20)   NULL,
    [ChallanDate]      DATETIME       NOT NULL,
    [ChalanQty]        INT            NOT NULL,
    [ReceiveQty]       INT            NOT NULL,
    [ProcessRejectQty] INT            NOT NULL,
    [FabricRejectQty]  INT            NOT NULL,
    [TSendQty]         INT            NOT NULL,
    [TRecQty]          INT            NOT NULL,
    [TProcessRectQty]  INT            NOT NULL,
    [TFabRejectQty]    INT            NOT NULL
);

