CREATE TABLE [dbo].[SkillMatrixPointTable] (
    [PointId]               INT              IDENTITY (1, 1) NOT NULL,
    [EmployeeId]            UNIQUEIDENTIFIER NOT NULL,
    [EmployeeCardId]        NVARCHAR (10)    NOT NULL,
    [ExperienceYear]        FLOAT (53)       NULL,
    [ExperiencePoint]       FLOAT (53)       NULL,
    [ExperienceWPoint]      FLOAT (53)       NULL,
    [MultiMCTtl]            FLOAT (53)       NULL,
    [MultiMCPoint]          FLOAT (53)       NULL,
    [MultiMCWPoint]         FLOAT (53)       NULL,
    [MultiProcessTtl]       FLOAT (53)       NULL,
    [MultiProcessPoint]     FLOAT (53)       NULL,
    [MultiProcessWPoint]    FLOAT (53)       NULL,
    [ProcessGradePoint]     FLOAT (53)       NULL,
    [ProcessGradeWPoint]    FLOAT (53)       NULL,
    [AttitudeGrade]         NVARCHAR (50)    NULL,
    [AttitudePoint]         FLOAT (53)       NULL,
    [AttitudeWPoint]        FLOAT (53)       NULL,
    [PerformancePercentage] FLOAT (53)       NULL,
    [PerformancePoint]      FLOAT (53)       NULL,
    [PerformanceWPoint]     FLOAT (53)       NULL,
    [TotalPoints]           FLOAT (53)       NULL,
    [Grading]               NVARCHAR (50)    NULL,
    [ProcessedWages]        DECIMAL (18, 2)  NULL,
    [CreatedDate]           DATETIME         NULL,
    [CreatedBy]             UNIQUEIDENTIFIER NULL,
    [EditedDate]            DATETIME         NULL,
    [EditedBy]              UNIQUEIDENTIFIER NULL,
    [IsActive]              BIT              NOT NULL,
    CONSTRAINT [PK_SkillMatrixPointTable] PRIMARY KEY CLUSTERED ([PointId] ASC)
);

