CREATE TABLE [dbo].[Table_A] (
    [CompanyId]                 INT              NULL,
    [CompanyName]               NVARCHAR (100)   NULL,
    [CompanyAddress]            NVARCHAR (MAX)   NULL,
    [BranchId]                  INT              NULL,
    [BranchName]                NVARCHAR (100)   NULL,
    [BranchUnitId]              INT              NULL,
    [UnitName]                  NVARCHAR (100)   NULL,
    [BranchUnitDepartmentId]    INT              NULL,
    [DepartmentName]            NVARCHAR (100)   NULL,
    [DepartmentSectionId]       INT              NULL,
    [SectionName]               NVARCHAR (100)   NULL,
    [DepartmentLineId]          INT              NULL,
    [LineName]                  NVARCHAR (100)   NULL,
    [EmployeeId]                UNIQUEIDENTIFIER NOT NULL,
    [EmployeeCardId]            NVARCHAR (100)   NOT NULL,
    [EmployeeName]              NVARCHAR (100)   NOT NULL,
    [EmployeeTypeId]            INT              NULL,
    [EmployeeType]              NVARCHAR (100)   NULL,
    [EmployeeGradeId]           INT              NULL,
    [EmployeeGrade]             NVARCHAR (100)   NULL,
    [EmployeeDesignationId]     INT              NULL,
    [EmployeeDesignation]       NVARCHAR (100)   NULL,
    [JoiningDate]               DATETIME         NULL,
    [QuitDate]                  DATETIME         NULL,
    [BranchUnitWorkShiftId]     INT              NULL,
    [WorkShiftName]             NVARCHAR (100)   NULL,
    [EmployeeWorkShiftId]       INT              NULL,
    [MobileNo]                  NVARCHAR (100)   NULL,
    [TransactionDate]           DATE             NOT NULL,
    [InTime]                    TIME (7)         NULL,
    [OutTime]                   TIME (7)         NULL,
    [LastDayOutTime]            TIME (7)         NULL,
    [Status]                    NVARCHAR (100)   NULL,
    [LateInMinutes]             INT              NULL,
    [TotalContinuousAbsentDays] INT              NULL,
    [OTHours]                   NUMERIC (18, 2)  NULL,
    [LastDayOTHours]            NUMERIC (18, 2)  NULL,
    [ExtraOTHours]              NUMERIC (18, 2)  NULL,
    [LastDayExtraOTHours]       NUMERIC (18, 2)  NULL,
    [WeekendOTHours]            NUMERIC (18, 2)  NULL,
    [HolidayOTHours]            NUMERIC (18, 2)  NULL,
    [Remarks]                   NVARCHAR (100)   NULL,
    [CreatedDate]               DATETIME         NULL,
    [CreatedBy]                 UNIQUEIDENTIFIER NULL,
    [IsActive]                  BIT              NULL
);

