CREATE TABLE [dbo].[tmpEmployee] (
    [RowID]                     INT              IDENTITY (1, 1) NOT NULL,
    [CompanyId]                 INT              NULL,
    [CompanyName]               NVARCHAR (100)   NULL,
    [CompanyAddress]            NVARCHAR (MAX)   NULL,
    [BranchId]                  INT              NULL,
    [BranchName]                NVARCHAR (100)   NULL,
    [BranchUnitId]              INT              NULL,
    [UnitName]                  NVARCHAR (100)   NULL,
    [BranchUnitDepartmentId]    INT              NULL,
    [DepartmentName]            NVARCHAR (100)   NULL,
    [DepartmentSectionId]       INT              NULL,
    [SectionName]               NVARCHAR (100)   NULL,
    [DepartmentLineId]          INT              NULL,
    [LineName]                  NVARCHAR (100)   NULL,
    [EmployeeId]                UNIQUEIDENTIFIER NULL,
    [EmployeeCardId]            NVARCHAR (100)   NULL,
    [EmployeeName]              NVARCHAR (100)   NULL,
    [EmployeeTypeId]            INT              NULL,
    [EmployeeType]              NVARCHAR (100)   NULL,
    [EmployeeGradeId]           INT              NULL,
    [EmployeeGrade]             NVARCHAR (100)   NULL,
    [EmployeeDesignationId]     INT              NULL,
    [EmployeeDesignation]       NVARCHAR (100)   NULL,
    [JoiningDate]               DATETIME         NULL,
    [QuitDate]                  DATETIME         NULL,
    [MobileNo]                  NVARCHAR (100)   NULL,
    [EmployeeWorkShiftId]       INT              NULL,
    [BranchUnitWorkShiftId]     INT              NULL,
    [WorkShiftName]             NVARCHAR (100)   NULL,
    [ShiftDate]                 DATETIME         NULL,
    [InTime]                    TIME (7)         NULL,
    [OutTime]                   TIME (7)         NULL,
    [LastDayOutTime]            TIME (7)         NULL,
    [Status]                    NVARCHAR (100)   NULL,
    [LateInMinutes]             INT              NULL,
    [TotalContinuousAbsentDays] INT              NULL,
    [OTHours]                   NUMERIC (18, 2)  NULL,
    [LastDayOTHours]            NUMERIC (18, 2)  NULL,
    [ExtraOTHours]              NUMERIC (18, 2)  NULL,
    [LastDayExtraOTHours]       NUMERIC (18, 2)  NULL,
    [WeekendOTHours]            NUMERIC (18, 2)  NULL,
    [HolidayOTHours]            NUMERIC (18, 2)  NULL,
    [Remarks]                   NVARCHAR (100)   NULL,
    [HD]                        CHAR (1)         NULL,
    [WD]                        CHAR (1)         NULL,
    [ShiftInTime]               TIME (7)         NULL,
    [ShiftOutTime]              TIME (7)         NULL,
    [OTMinutes]                 INT              NULL,
    [EOTHours]                  NUMERIC (18, 2)  NULL,
    [IsEligibleForOvertime]     BIT              NULL,
    [LPDate]                    DATETIME         NULL
);


GO
CREATE CLUSTERED INDEX [ClusteredIndex-20161102-171740]
    ON [dbo].[tmpEmployee]([CompanyId] ASC, [ShiftDate] ASC, [EmployeeId] ASC);

