//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Acc_FinancialPeriod : BaseModel
    {
        public Acc_FinancialPeriod()
        {
            this.Acc_VoucherMaster = new HashSet<Acc_VoucherMaster>();
            this.Acc_OpeningClosing = new HashSet<Acc_OpeningClosing>();
            this.Acc_BankReconcilationMaster = new HashSet<Acc_BankReconcilationMaster>();
        }

        public int Id { get; set; }
        [Required(ErrorMessage = "Required")]
        public string PeriodName { get; set; }

        [Required(ErrorMessage = "Required")]
        public Nullable <DateTime> PeriodStartDate { get; set; }

        [Required(ErrorMessage = "Required")]
        public Nullable<DateTime> PeriodEndDate { get; set; }

        [Required(ErrorMessage = "Required")]
        public Nullable<bool> ActiveStatus { get; set; }

        [Required(ErrorMessage = "Required")]
        public Nullable<int> SortOrder { get; set; }
        
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CDT { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EDT { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }

        public virtual ICollection<Acc_VoucherMaster> Acc_VoucherMaster { get; set; }
        public virtual ICollection<Acc_OpeningClosing> Acc_OpeningClosing { get; set; }
        public virtual ICollection<Acc_BankReconcilationMaster> Acc_BankReconcilationMaster { get; set; }
    }
}
