//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Acc_CostCentre : BaseModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Required")]
        public int SectorId { get; set; }

        [Required(ErrorMessage = "Required")]
        public string CostCentreCode { get; set; }

        [Required(ErrorMessage = "Required")]
        public string CostCentreName { get; set; }

        [Required(ErrorMessage = "Required")]
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CDT { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EDT { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }

        public virtual Acc_CompanySector Acc_CompanySector { get; set; }
        public virtual ICollection<Acc_SalaryMapping> Acc_SalaryMapping { get; set; }
    }
}
