//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Acc_CompanySector : BaseModel
    {
        public Acc_CompanySector()
        {
            this.Acc_CostCentre = new HashSet<Acc_CostCentre>();
            this.Acc_VoucherMaster = new HashSet<Acc_VoucherMaster>();
            this.Acc_OpeningClosing = new HashSet<Acc_OpeningClosing>();
            this.Acc_PermitedChartOfAccount = new HashSet<Acc_PermitedChartOfAccount>();
            this.Acc_BankReconcilationMaster = new HashSet<Acc_BankReconcilationMaster>();
            this.Acc_SalaryMapping = new HashSet<Acc_SalaryMapping>();
        }

        public int Id { get; set; }

        [Required(ErrorMessage = "Required")]
        public string SectorCode { get; set; }

        [Required(ErrorMessage = "Required")]
        public string SectorName { get; set; }
        public string SectorAddress { get; set; }

        [Required(ErrorMessage = "Required")]
        public Nullable<int> SortOrder { get; set; }
        public Nullable<System.DateTime> CDT { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EDT { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }

        public virtual ICollection<Acc_CostCentre> Acc_CostCentre { get; set; }
        public virtual ICollection<Acc_VoucherMaster> Acc_VoucherMaster { get; set; }
        public virtual ICollection<Acc_OpeningClosing> Acc_OpeningClosing { get; set; }
        public virtual ICollection<Acc_PermitedChartOfAccount> Acc_PermitedChartOfAccount { get; set; }
        public virtual ICollection<Acc_BankReconcilationMaster> Acc_BankReconcilationMaster { get; set; }
        public virtual ICollection<Acc_SalaryMapping> Acc_SalaryMapping { get; set; }
    }
}