//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SCERP.Model.InventoryModel;

namespace SCERP.Model.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_DyeingSpChallanDetail
    {
       
        public long DyeingSpChallanDetailId { get; set; }
        public long DyeingSpChallanId { get; set; }
        public long BatchId { get; set; }
        public long BatchDetailId { get; set; }
        public int SpGroupId { get; set; }
        public double GreyWeight { get; set; }
        public Nullable<double> FinishWeight { get; set; }
        public double Rate { get; set; }
        public string Remarks { get; set; }
        public string CompId { get; set; }
        public double? CcuffQty { get; set; }
        public virtual Pro_Batch Pro_Batch { get; set; }
        public virtual PROD_DyeingSpChallan PROD_DyeingSpChallan { get; set; }
        public virtual PROD_GroupSubProcess PROD_GroupSubProcess { get; set; }
        public virtual PROD_BatchDetail PROD_BatchDetail { get; set; }
     
    }
}
