//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Model.CommonModel;

namespace SCERP.Model.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_DyeingJobOrder
    {
        public PROD_DyeingJobOrder()
        {
            this.PROD_DyeingJobOrderDetail = new HashSet<PROD_DyeingJobOrderDetail>();
        }
    
        public long DyeingJobOrderId { get; set; }
        [Required]
        public string JobRefId { get; set; }
         [Required]
        public System.DateTime JobDate { get; set; }
         [Required]
        public string WorkOrderNo { get; set; }
         [Required]
        public long PartyId { get; set; }
         [Required]
        public System.DateTime DeliveryDate { get; set; }
         [Required]
        public string JobType { get; set; }
        public string BuyerRefId { get; set; }
        public string OrderNo { get; set; }
        public string OrderStyleRefId { get; set; }
        public string BuyerName { get; set; }
        public string OrderName { get; set; }
        public string StyleName { get; set; }
        public string Remarks { get; set; }
         [Required]
        public string CompId { get; set; }
        [Required]
        public string ProcessRefId { get; set; }
        public virtual Party Party { get; set; }
        public virtual ICollection<PROD_DyeingJobOrderDetail> PROD_DyeingJobOrderDetail { get; set; }
    }
}
