//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Model.CommonModel;
using SCERP.Model.InventoryModel;

namespace SCERP.Model.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_DyeingSpChallan
    {
        public PROD_DyeingSpChallan()
        {
            this.PROD_DyeingSpChallanDetail = new HashSet<PROD_DyeingSpChallanDetail>();
            this.Inventory_FinishFabStore = new HashSet<Inventory_FinishFabStore>();
            
        }
    
        public long DyeingSpChallanId { get; set; }
        [Required]
        public string DyeingSpChallanRefId { get; set; }
        [Required]
        public string ChallanNo { get; set; }
        [Required]
        public System.DateTime ChallanDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        [Required]
        public long ParyId { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> ApprovedBy { get; set; }
        public string CompId { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual ICollection<PROD_DyeingSpChallanDetail> PROD_DyeingSpChallanDetail { get; set; }
        public virtual ICollection<Inventory_FinishFabStore> Inventory_FinishFabStore { get; set; }
        
        public virtual Party Party { get; set; }
    }
}
