//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_GroupSubProcess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROD_GroupSubProcess()
        {
            this.PROD_DyeingSpChallanDetail = new HashSet<PROD_DyeingSpChallanDetail>();
        }
    
        public int GroupSubProcessId { get; set; }
        public string GroupName { get; set; }
        public string SpCode { get; set; }
        public string CompId { get; set; }
        public string GroupType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROD_DyeingSpChallanDetail> PROD_DyeingSpChallanDetail { get; set; }
    }
}
