//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;

namespace SCERP.Model.Production
{
    public partial class PROD_StanderdMinValDetail
    {
        public long StanderdMinValDetailId { get; set; }
        public long StanderdMinValueId { get; set; }
        public string CompId { get; set; }
        public string StanderdMinValueRefId { get; set; }
        public string SubProcessRefId { get; set; }
        public Nullable<decimal> StMvD { get; set; }
        public virtual PROD_StanderdMinValue PROD_StanderdMinValue { get; set; }
    }
}
