//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_CuttingSequence
    {
        public PROD_CuttingSequence()
        {
            this.PROD_CuttingTag = new HashSet<PROD_CuttingTag>();
        }
    
        public long CuttingSequenceId { get; set; }
        public string CuttingSequenceRefId { get; set; }
        public string CompId { get; set; }
        public string BuyerRefId { get; set; }
        public string OrderNo { get; set; }
        public string OrderStyleRefId { get; set; }
        public string ColorRefId { get; set; }
        public int SlNo { get; set; }
        public string ComponentRefId { get; set; }
    
        public virtual ICollection<PROD_CuttingTag> PROD_CuttingTag { get; set; }
    }
}
