//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model.Planning;
using SCERP.Model.Production;
using SCERP.Model.TrackingModel;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Production_Machine : SearchModel<Production_Machine>
    {
        public Production_Machine()
        {
            this.Inventory_MaterialIssueDetail = new HashSet<Inventory_MaterialIssueDetail>();
            this.Pro_Batch = new HashSet<Pro_Batch>();
            this.TrackMachineLog = new HashSet<TrackMachineLog>();
            this.PROD_SewingInputProcess = new HashSet<PROD_SewingInputProcess>();
            this.PROD_KnittingRoll = new HashSet<PROD_KnittingRoll>();
            this.PLAN_TargetProduction = new HashSet<PLAN_TargetProduction>();
            this.PLAN_DailyLineLayout = new HashSet<PLAN_DailyLineLayout>();
  
        }
    
        public int MachineId { get; set; }
        public string CompId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string ProcessorRefId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string MachineRefId { get; set; }
        public string ProcessRefId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string Name { get; set; }
        public string Description { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Nullable<int> NoMachine { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Nullable<decimal> EfficiencyPer { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Nullable<decimal> IdelPer { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Nullable<decimal> RatedCapacity { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
        public virtual ICollection<Pro_Batch> Pro_Batch { get; set; }
        public ICollection<Inventory_MaterialIssueDetail> Inventory_MaterialIssueDetail { get; set; }
        public virtual ICollection<TrackMachineLog> TrackMachineLog { get; set; }
        public virtual ICollection<PROD_SewingInputProcess> PROD_SewingInputProcess { get; set; }
        public virtual ICollection<PROD_KnittingRoll> PROD_KnittingRoll { get; set; }
        public virtual ICollection<PLAN_TargetProduction> PLAN_TargetProduction { get; set; }
        public virtual ICollection<PLAN_DailyLineLayout> PLAN_DailyLineLayout { get; set; }


    }
}