//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using SCERP.Common;

namespace SCERP.Model.Production
{

    public partial class PROD_Production : ProSearchModel<PROD_Production>
    {
        public PROD_Production()
        {
            this.PROD_ProductionDetaill = new HashSet<PROD_ProductionDetaill>();
        }
        public long ProductionId { get; set; }
        public string CompId { get; set; }
        public string ProductionRefId { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Nullable<System.DateTime> ProdDate { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string ProcessRefId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string ProrgramRefId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string ProcessorRefId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string MachineRefId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string Rmks { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string SlipNo { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string PType { get; set; }
        public ICollection<PROD_ProductionDetaill> PROD_ProductionDetaill { get; set; }
    }
}
