//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace SCERP.Model.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROD_DyeingJobOrderDetail
    {
        public long DyeingJobOrderDetailId { get; set; }
        public long DyeingJobOrderId { get; set; }
         [Required]
        public int ItemId { get; set; }
         [Required]
        public string ComponentRefId { get; set; }
         [Required]
        public string ColorRefId { get; set; }
        public string MdSizeRefId { get; set; }
        public string FdSizeRefId { get; set; }
         [Required]
        public double Quantity { get; set; }
         [Required]
         public double? GreyWit { get; set; }
        [Required]
        public double Rate { get; set; }
         [Required]
        public string CompId { get; set; }
        public string Remarks { get; set; }
        public double? Gsm { get; set; }
        public virtual PROD_DyeingJobOrder PROD_DyeingJobOrder { get; set; }
    }
}
