//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace SCERP.Model.Production
{
    
    public partial class VProgramDetail
    {
        public string CompId { get; set; }
        public long ProgramDetailId { get; set; }
        public string PrgramRefId { get; set; }
        public long ProgramId { get; set; }
        public decimal Quantity { get; set; }
        public string ColorRefId { get; set; }
        public string SizeRefId { get; set; }
        public string SizeName { get; set; }
        public string ColorName { get; set; }
        public string ItemCode { get; set; }
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public string UnitName { get; set; }
        public string MType { get; set; }
        public string ProcessRefId { get; set; }
        public string FinishSizeRefId { get; set; }
        public string FinishSizeName { get; set; }
        public string SleeveLength { get; set; }
        public string LotRefId { get; set; }
        public string LotName { get; set; }
        public string ComponentRefId { get; set; }
        public string ComponentName { get; set; }
        public Nullable<double> Rate { get; set; }
        public string GSM { get; set; }
        public string Remarks { get; set; }
        public int? MeasurementUinitId { get; set; }
        public string BrandName { get; set; }
        public int? NoOfCone { get; set; }
        public double YRatio { get; set; }
        [NotMapped]
        public string CompositName
        {
            get
            {
                return ItemName + "|" + ColorName + "|" + SizeName;
            }
        }

 

    }
}
