//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SCERP.Model.Production
{
  
    
    public partial class VSubProcess
    {
        public long SubProcessId { get; set; }
        public string CompId { get; set; }
        public string SubProcessRefId { get; set; }
        public string ProcessRefId { get; set; }
        public string SubProcessName { get; set; }
        public int ProcessId { get; set; }
        public string ProcessName { get; set; }
    }
}
