//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace SCERP.Model.Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwProdDyeingSpChallanDetail
    {
      
        public long DyeingSpChallanDetailId { get; set; }
        public long DyeingSpChallanId { get; set; }
        public long BatchId { get; set; }
        public long BatchDetailId { get; set; }
        public int SpGroupId { get; set; }
        public double GreyWeight { get; set; }
        public Nullable<double> FinishWeight { get; set; }
        public double Rate { get; set; }
        public string Remarks { get; set; }
        public string CompId { get; set; }
        public string BatchNo { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string ItemName { get; set; }
        public string GroupName { get; set; }
        public double? CcuffQty { get; set; }
    }
}
