//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace SCERP.Model.Production
{
  
    public partial class VwProduction
    {
        public long ProductionId { get; set; }
        public string CompId { get; set; }
        public string ProductionRefId { get; set; }
        public Nullable<System.DateTime> ProdDate { get; set; }
        public string ProcessRefId { get; set; }
        public string ProrgramRefId { get; set; }
        public string ProcessorRefId { get; set; }
        public string MachineRefId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string Rmks { get; set; }
        public string SlipNo { get; set; }
        public string PType { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string ProcessorName { get; set; }
        public string MachineName { get; set; }
    }
}
