//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class AttendanceBonusSetting : SearchModel<AttendanceBonusSetting>
    {
        public int AttendanceBonusSettingId { get; set; }

        [Required(ErrorMessage = "Required !")]
        public int AbsentDays { get; set; }

        [Required(ErrorMessage = "Required !")]

        public int LateDays { get; set; }

        [Required(ErrorMessage = "Required !")]
        public int LeavewithoutApplication { get; set; }

        [Required(ErrorMessage = "Required !")]
        public int LeavewithApplication { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Required !")]
        public System.DateTime? FromDate { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ToDate { get; set; }

        public Nullable<System.DateTime> CDT { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EDT { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
    }
}
