//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AttendanceBonus : SearchModel<BranchUnitWorkShift>
    {
        public int AttendanceBonusId { get; set; }
       
        public int DesignationId { get; set; }

        [Range(1, 500000, ErrorMessage = "Invalid amount!")]
        public decimal Amount { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> FromDate { get; set; }
    
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ToDate { get; set; }

        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }

        public virtual EmployeeDesignation EmployeeDesignation { get; set; }
    }
}
