//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class AuthorizationType : SearchModel<AuthorizationType>
    {
        public AuthorizationType()
        {
            this.AuthorizedPerson = new HashSet<AuthorizedPerson>();
        }

        public int Id { get; set; }

         [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int ProcessKeyId { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int AuthorizationId { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.AuthorizationTypeValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string TypeName { get; set; }

        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<AuthorizedPerson> AuthorizedPerson { get; set; }
    }
}
