//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model;
using SCERP.Model.HRMModel;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class BranchUnit : SearchModel<BranchUnit>
    {
        public BranchUnit()
        {
            this.ExceptionDay = new HashSet<ExceptionDay>();
            this.BranchUnitDepartment = new HashSet<BranchUnitDepartment>();
            this.BranchUnitWorkShift = new HashSet<BranchUnitWorkShift>();
            this.LeaveSetting = new HashSet<LeaveSetting>();
            this.WorkGroup = new HashSet<WorkGroup>();
            this.UserPermissionForDepartmentLevel = new HashSet<UserPermissionForDepartmentLevel>();
        }
        public int BranchUnitId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int BranchId { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int UnitId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }

        public virtual Branch Branch { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual ICollection<BranchUnitDepartment> BranchUnitDepartment { get; set; }
        public virtual ICollection<BranchUnitWorkShift> BranchUnitWorkShift { get; set; }
        public virtual ICollection<LeaveSetting> LeaveSetting { get; set; }
        public virtual ICollection<WorkGroup> WorkGroup { get; set; }
        public virtual ICollection<UserPermissionForDepartmentLevel> UserPermissionForDepartmentLevel { get; set; }
        public virtual ICollection<ExceptionDay> ExceptionDay { get; set; } 
    }
}
