//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class BranchUnitDepartment : SearchModel<BranchUnitDepartment>
    {
        public BranchUnitDepartment()
        {
            this.DepartmentLine = new HashSet<DepartmentLine>();
            this.DepartmentSection = new HashSet<DepartmentSection>();
            this.EmployeeCompanyInfo=new Collection<EmployeeCompanyInfo>();
            this.UserPermissionForDepartmentLevel = new HashSet<UserPermissionForDepartmentLevel>();
            this.Inventory_MaterialRequisition=new HashSet<Inventory_MaterialRequisition>();
            this.PLAN_ProductionLine = new HashSet<PLAN_ProductionLine>();
            this.GeneralDaySetup = new Collection<GeneralDaySetup>();
            this.HeadOfDepartment = new HashSet<HeadOfDepartment>();
        }
        public int BranchUnitDepartmentId { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int BranchUnitId { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int UnitDepartmentId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual BranchUnit BranchUnit { get; set; }
        public virtual UnitDepartment UnitDepartment { get; set; }
        public virtual ICollection<DepartmentLine> DepartmentLine { get; set; }
        public virtual ICollection<DepartmentSection> DepartmentSection { get; set; }
        public virtual ICollection<EmployeeCompanyInfo> EmployeeCompanyInfo { get; set; }
        public virtual ICollection<UserPermissionForDepartmentLevel> UserPermissionForDepartmentLevel { get; set; }
        public virtual ICollection<Inventory_MaterialRequisition> Inventory_MaterialRequisition { get; set; }
        public virtual ICollection<PLAN_ProductionLine> PLAN_ProductionLine { get; set; }
        public virtual ICollection<GeneralDaySetup> GeneralDaySetup { get; set; }
        public virtual ICollection<HeadOfDepartment> HeadOfDepartment { get; set; }
        
    }
}
