//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class BranchUnitWorkShift : SearchModel<BranchUnitWorkShift>
    {
        public BranchUnitWorkShift()
        {
            this.EmployeeWorkShift=new Collection<EmployeeWorkShift>();
        }

        public int BranchUnitWorkShiftId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int BranchUnitId { get; set; }

        public int WorkShiftId { get; set; }
        public int Status { get; set; }

       [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [DataType(DataType.Date)]
        public System.DateTime? FromDate { get; set; }
     
        [DataType(DataType.Date)]
        public System.DateTime? ToDate { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }

        public virtual BranchUnit BranchUnit { get; set; }
        public virtual WorkShift WorkShift { get; set; }

        public virtual ICollection<EmployeeWorkShift> EmployeeWorkShift { get; set; }
        
    }
}
