//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public class Branch : SearchModel<Branch>
    {
        public Branch()
        {
            this.EmployeeCompanyInfoes = new HashSet<EmployeeCompanyInfo>();
            this.Lines = new HashSet<Line>();
            this.WorkGroups = new HashSet<WorkGroup>();
            this.BranchUnit = new HashSet<BranchUnit>();
            this.UserPermissionForDepartmentLevel = new HashSet<UserPermissionForDepartmentLevel>();

          
            this.Inventory_ItemStore = new Collection<Inventory_ItemStore>();
        }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int Id { get; set; }

   
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]

        [RegularExpression(CustomRegEx.BranchNameValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string Name { get; set; }

         [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string NameInBengali { get; set; }

         [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int CompanyId { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.FullAddressValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string FullAddress { get; set; }


       [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string FullAddressInBengali { get; set; }

       
        [RegularExpression(CustomRegEx.PostOfficeValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string PostOffice { get; set; }

        public string PostOfficeInBengali { get; set; }

       
        [RegularExpression(CustomRegEx.PostCodeValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string PostCode { get; set; }

         [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
         [RegularExpression(CustomRegEx.PhoneNoValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string Phone { get; set; }


     
        [RegularExpression(CustomRegEx.EmailValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string Email { get; set; }

      
        [RegularExpression(CustomRegEx.FaxValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string Fax { get; set; }

        public Nullable<int> PoliceStationId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }

        public bool IsActive { get; set; }

        public virtual Company Company { get; set; }
        public virtual District District { get; set; }
        public virtual PoliceStation PoliceStation { get; set; }
        public virtual ICollection<EmployeeCompanyInfo> EmployeeCompanyInfoes { get; set; }
        public virtual ICollection<Line> Lines { get; set; }
        public virtual ICollection<WorkGroup> WorkGroups { get; set; }
        public virtual ICollection<BranchUnit> BranchUnit { get; set; }
        public virtual ICollection<UserPermissionForDepartmentLevel> UserPermissionForDepartmentLevel { get; set; }


       public virtual ICollection<Inventory_ItemStore> Inventory_ItemStore { get; set; }
        
    }
}
