//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Company : SearchModel<Company>
    {
        public Company()
        {
            this.Branch = new HashSet<Branch>();
            this.EmployeeCompanyInfoes = new HashSet<EmployeeCompanyInfo>();
            this.Lines = new HashSet<Line>();
            this.WorkGroups = new HashSet<WorkGroup>();
            this.EmployeeCardInfo = new HashSet<EmployeeCardInfo>();
            this.UserPermissionForDepartmentLevel = new HashSet<UserPermissionForDepartmentLevel>();
        }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int Id { get; set; }
        public string CompanyRefId { get; set; }
        [Required(ErrorMessage =CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.CompanyNameValidationExpression, ErrorMessage =CustomErrorMessage.CommonErrorMessage)]
        public string Name { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string NameInBengali { get; set; }


        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.FullAddressValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string FullAddress { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string FullAddressInBengali { get; set; }

        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> PoliceStationId { get; set; }


       
        [RegularExpression(CustomRegEx.PostOfficeValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string PostOffice { get; set; }

        public string PostOfficeInBengali { get; set; }

        
        [RegularExpression(CustomRegEx.PostCodeValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string PostCode { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.MobileNoValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string Phone { get; set; }

       
        [RegularExpression(CustomRegEx.EmailValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string Email { get; set; }

       
        [RegularExpression(CustomRegEx.FaxValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string Fax { get; set; }


       
        [RegularExpression(CustomRegEx.WebSiteValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string Website { get; set; }


        //[RegularExpression(CustomRegEx.TinValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string TinNo { get; set; }

        //[RegularExpression(CustomRegEx.VatValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string VatRegNo { get; set; }

        public Nullable<int> NumberOfBranches { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.PersonNameValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]   
        public string ContactPerson { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [Display(Name = "DomainName")]
        public string DomainName { get; set; }
        public string ImagePath { get; set; }
        
        [RegularExpression(CustomRegEx.ContactPersonDesignationValidationExpression, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string ContactPersonDesignation { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.MobileNoValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string ContactPersonMobile { get; set; }

      
        [RegularExpression(CustomRegEx.EmailValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string ContactPersonEmail { get; set; }

        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }

        public virtual ICollection<Branch> Branch { get; set; }
        public virtual District District { get; set; }
        public virtual PoliceStation PoliceStation { get; set; }
        public virtual ICollection<EmployeeCompanyInfo> EmployeeCompanyInfoes { get; set; }
        public virtual ICollection<Line> Lines { get; set; }
        public virtual ICollection<WorkGroup> WorkGroups { get; set; }
        public virtual ICollection<EmployeeCardInfo> EmployeeCardInfo { get; set; }
        public virtual ICollection<UserPermissionForDepartmentLevel> UserPermissionForDepartmentLevel { get; set; }
    }
}
