//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public class Country : SearchModel<Country>
    {
        public Country()
        {
            OM_PortOfLoading=new HashSet<OM_PortOfLoading>();
            this.Inventory_ItemStoreDetail = new HashSet<Inventory_ItemStoreDetail>();
            this.Inventory_StoreLedger = new HashSet<Inventory_StoreLedger>();
            this.District = new Collection<District>();
            this.State = new HashSet<State>();
            this.City = new HashSet<City>();
            this.Inventory_MaterialIssueDetail = new HashSet<Inventory_MaterialIssueDetail>();
            this.PoliceStation=new Collection<PoliceStation>();
            this.EmployeePermanentAddress = new Collection<EmployeePermanentAddress>();
            this.EmployeePresentAddress=new Collection<EmployeePresentAddress>();
            this.Inventory_StorePurchaseRequisitionDetail=new HashSet<Inventory_StorePurchaseRequisitionDetail>();
        }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int Id { get; set; }


        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.CountryNameValidationExpression, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
  
        public string CountryName { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]     
        public string CountryNameInBengali { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.CountryCodeValidationExpression, ErrorMessage =CustomErrorMessage.CommonErrorMessage)]     
        public string CountryCode { get; set; }

        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }

        public virtual ICollection<OM_PortOfLoading> OM_PortOfLoading { get; set; }

        public virtual ICollection<City> City { get; set; }
        public virtual ICollection<State> State { get; set; }
        public virtual ICollection<Inventory_StoreLedger> Inventory_StoreLedger { get; set; }
        public virtual ICollection<Inventory_ItemStoreDetail> Inventory_ItemStoreDetail { get; set; }
        public virtual ICollection<EmployeePermanentAddress> EmployeePermanentAddress { get; set; }
        public virtual ICollection<EmployeePresentAddress> EmployeePresentAddress { get; set; }
        public virtual ICollection<District> District { get; set; }
        public virtual ICollection<PoliceStation> PoliceStation { get; set; }
        public virtual ICollection<Inventory_MaterialIssueDetail> Inventory_MaterialIssueDetail { get; set; }
        public virtual ICollection<Inventory_StorePurchaseRequisitionDetail> Inventory_StorePurchaseRequisitionDetail{ get; set; }
    }
}
