//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class EmployeePermanentAddress
    {
        public int Id { get; set; }
        public System.Guid EmployeeId { get; set; }


        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]

        public string MailingAddress { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string MailingAddressInBengali { get; set; }

        public Nullable<int> CountryId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> PoliceStationId { get; set; }

     
        public string PostOffice { get; set; }

        public string PostOfficeInBengali { get; set; }

     
        public string PostCode { get; set; }

        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }

        [Required]
        public int Status { get; set; }

        [Required]
        public bool IsActive { get; set; }

        public virtual Country Country { get; set; }
        public virtual District District { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual PoliceStation PoliceStation { get; set; }
    }
}
