//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmployeeDailyAttendance : SearchModel<EmployeeDailyAttendance>
    {

        public int Id { get; set; }
        public System.Guid EmployeeId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string EmployeeCardId { get; set; }
        public System.DateTime TransactionDateTime { get; set; }

        public byte? FunctionKey { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]

        public bool IsFromMachine { get; set; }

        [Required(ErrorMessage = @"Required")]
        public int Limit { get; set; }

        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }

        public virtual Employee Employee { get; set; }
    }
}
