//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using SCERP.Common;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmployeeLeave : SearchModel<EmployeeLeave>
    {
        public int Id { get; set; }

        public System.Guid EmployeeId { get; set; }

        public string EmployeeCardId { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int LeaveTypeId { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public System.DateTime? SubmitDate { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public System.DateTime? AppliedFromDate { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public System.DateTime? AppliedToDate { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int AppliedTotalDays { get; set; }

        public string LeavePurpose { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string EmergencyPhoneNo { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string AddressDuringLeave { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime? RecommendedFromDate { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime? RecommendedToDate { get; set; }

        public int? RecommendedTotalDays { get; set; }

        public int? RecommendationStatus { get; set; }

        public System.DateTime? RecommendationStatusDate { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public System.Guid? RecommendationPerson { get; set; }

        public string RecommendationComment { get; set; }


        [DataType(DataType.Date)]
        public System.DateTime? ApprovedFromDate { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime? ApprovedToDate { get; set; }

        public int? ApprovedTotalDays { get; set; }

        public int? ApprovalStatus { get; set; }

        public System.DateTime? ApprovalStatusDate { get; set; }

        public  System.Guid? ApprovalPerson { get; set; }

        public string ApprovalComment { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime? ConsumedFromDate { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime? ConsumedToDate { get; set; }

        public int? ConsumedTotalDays { get; set; }

        public int? JoinedBeforeDays { get; set; }

        public System.DateTime? ResumeDate { get; set; }
       
      
        public System.DateTime? CreatedDate { get; set; }
        public System.Guid? CreatedBy { get; set; }
        public System.DateTime? EditedDate { get; set; }
        public System.Guid? EditedBy { get; set; }
        public bool IsActive { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual LeaveType LeaveType { get; set; }
    }
}
