//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model.HRMModel;
using SCERP.Model.InventoryModel;
using SCERP.Model.TrackingModel;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Employee : SearchModel<Employee>
    {
        public Employee()
        {
            this.Inventory_AuthorizedPerson = new Collection<Inventory_AuthorizedPerson>();
            this.AuthorizedPerson = new HashSet<AuthorizedPerson>();
            this.EmployeeBankInfo = new HashSet<EmployeeBankInfo>();
            this.EmployeeDailyAttendance = new HashSet<EmployeeDailyAttendance>();
            this.EmployeeCompanyInfo = new HashSet<EmployeeCompanyInfo>();
            this.EmployeeDocuments = new HashSet<EmployeeDocument>();
            this.EmployeeEducation = new HashSet<EmployeeEducation>();
            this.EmployeeEntitlement = new HashSet<EmployeeEntitlement>();
            this.EmployeeSkillSet = new HashSet<EmployeeSkillSet>();
            this.EmployeeInOut = new HashSet<EmployeeInOut>();
            this.EmployeeLeave = new HashSet<EmployeeLeave>();
            this.EmployeePermanentAddress = new HashSet<EmployeePermanentAddress>();
            this.EmployeePresentAddress = new HashSet<EmployeePresentAddress>();
            this.EmployeeSalary = new HashSet<EmployeeSalary>();
            this.EmployeeSalary_Processed = new HashSet<EmployeeSalary_Processed>();
            this.EmployeeSalary_Processed_Temp = new HashSet<EmployeeSalary_Processed_Temp>();
            this.Employment = new HashSet<Employment>();
            this.Employment = new HashSet<Employment>();
            this.EmployeeShortLeave = new HashSet<EmployeeShortLeave>();

            this.EmployeeWorkGroup = new Collection<EmployeeWorkGroup>();
            this.EmployeeWorkShift = new Collection<EmployeeWorkShift>();
            this.EmployeeFamilyInfo = new Collection<EmployeeFamilyInfo>();
            this.OvertimeEligibleEmployee = new Collection<OvertimeEligibleEmployee>();
            this.Inventory_MaterialIssue = new HashSet<Inventory_MaterialIssue>();
            this.Inventory_MaterialIssueRequisition = new HashSet<Inventory_MaterialIssueRequisition>();
            this.OutStationDuty = new HashSet<OutStationDuty>();
            this.EmployeeSkill = new HashSet<EmployeeSkill>();
            this.Inventory_PurchaseRequisitionApprovalFlowConfiguration = new HashSet<Inventory_PurchaseRequisitionApprovalFlowConfiguration>();

            this.SalaryAdvance = new HashSet<SalaryAdvance>();
            this.EmployeeBonus = new HashSet<EmployeeBonus>();

            this.EmployeeInOutModel = new HashSet<EmployeeInOutModel>();

            this.HeadOfDepartment = new HashSet<HeadOfDepartment>();
            this.TrackMachineLog = new HashSet<TrackMachineLog>();

            this.HrmPenalty = new HashSet<HrmPenalty>();
            this.HrmPenalty1 = new HashSet<HrmPenalty>();

            this.PayrollExcludedEmployeeFromSalaryProcess = new HashSet<PayrollExcludedEmployeeFromSalaryProcess>();
            this.HouseKeepingRegister = new HashSet<HouseKeepingRegister>();
         
        }
      
        public virtual ICollection<HrmPenalty> HrmPenalty { get; set; }
        public virtual ICollection<HrmPenalty> HrmPenalty1 { get; set; }

        public int Id { get; set; }
        public System.Guid EmployeeId { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.EmployeeCardIdlValidationExpression, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string EmployeeCardId { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.PersonNameValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string Name { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string NameInBengali { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.PersonNameValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string MothersName { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string MothersNameInBengali { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.PersonNameValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string FathersName { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string FathersNameInBengali { get; set; }

        //[Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.PersonNameValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string SpousesName { get; set; }

        public string SpousesNameInBengali { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [DataType(DataType.Date)]
        public System.DateTime? DateOfBirth { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public byte GenderId { get; set; }


        public Nullable<int> MaritalStateId { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> MariageAnniversary { get; set; }


        //[Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.NationalityValidationExpression, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string Nationality { get; set; }


        public string NationalityInBengali { get; set; }


        //[Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.NationalIdCardValidationExpression, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string NationalIdNo { get; set; }

        //[Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.BirthRegiNoValidationExpression, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string BirthRegistrationNo { get; set; }


        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int ReligionId { get; set; }

        //[Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.TaxIdentificationNoValidationExpression, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string TaxIdentificationNo { get; set; }

        //[Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.DriviningLicenceValidationExpression, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string DrivingLicenseNo { get; set; }

        //[Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.PassportNoValidationExpression, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string PassportNo { get; set; }


        public Nullable<int> BloodGroupId { get; set; }

        [Required]
        public string PhotographPath { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [DataType(DataType.Date)]
        public System.DateTime? JoiningDate { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [DataType(DataType.Date)]
        public System.DateTime? ConfirmationDate { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime? QuitDate { get; set; }
        public Nullable<int> QuitTypeId { get; set; }
        public string ServiceDuration { get; set; }

        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }

        [Required]
        public int Status { get; set; }

        [Required]
        public bool IsActive { get; set; }


        public virtual BloodGroup BloodGroup { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Religion Religion { get; set; }
        public virtual MaritalState MaritalState { get; set; }
        public virtual QuitType QuitType { get; set; }

        public virtual ICollection<EmployeeBankInfo> EmployeeBankInfo { get; set; }
        public virtual ICollection<EmployeeDailyAttendance> EmployeeDailyAttendance { get; set; }
        public virtual ICollection<EmployeeDocument> EmployeeDocuments { get; set; }
        public virtual ICollection<EmployeeEducation> EmployeeEducation { get; set; }
        public virtual ICollection<EmployeeEntitlement> EmployeeEntitlement { get; set; }
        public virtual ICollection<EmployeeSkillSet> EmployeeSkillSet { get; set; }
        public virtual ICollection<EmployeeInOut> EmployeeInOut { get; set; }
        public virtual ICollection<EmployeeLeave> EmployeeLeave { get; set; }
        public virtual ICollection<EmployeePermanentAddress> EmployeePermanentAddress { get; set; }
        public virtual ICollection<EmployeePresentAddress> EmployeePresentAddress { get; set; }
        public virtual ICollection<EmployeeSalary> EmployeeSalary { get; set; }
        public virtual ICollection<EmployeeSalary_Processed> EmployeeSalary_Processed { get; set; }
        public virtual ICollection<EmployeeSalary_Processed_Temp> EmployeeSalary_Processed_Temp { get; set; }
        public virtual ICollection<Employment> Employment { get; set; }
        public virtual ICollection<EmployeeCompanyInfo> EmployeeCompanyInfo { get; set; }


        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<AuthorizedPerson> AuthorizedPerson { get; set; }

        public virtual ICollection<EmployeeWorkGroup> EmployeeWorkGroup { get; set; }
        public virtual ICollection<EmployeeWorkShift> EmployeeWorkShift { get; set; }

        public virtual ICollection<EmployeeFamilyInfo> EmployeeFamilyInfo { get; set; }

        public virtual ICollection<OvertimeEligibleEmployee> OvertimeEligibleEmployee { get; set; }

        public virtual ICollection<OutStationDuty> OutStationDuty { get; set; }
        public virtual ICollection<EmployeeSkill> EmployeeSkill { get; set; }
        public virtual ICollection<Inventory_PurchaseRequisitionApprovalFlowConfiguration> Inventory_PurchaseRequisitionApprovalFlowConfiguration { get; set; }
        public virtual ICollection<Inventory_AuthorizedPerson> Inventory_AuthorizedPerson { get; set; }
        public virtual ICollection<SalaryAdvance> SalaryAdvance { get; set; }


        public virtual ICollection<Inventory_MaterialIssue> Inventory_MaterialIssue { get; set; }
        public virtual ICollection<Inventory_MaterialIssueRequisition> Inventory_MaterialIssueRequisition { get; set; }

        public virtual ICollection<EmployeeBonus> EmployeeBonus { get; set; }

        public virtual ICollection<EmployeeInOutModel> EmployeeInOutModel { get; set; }

        public virtual ICollection<HeadOfDepartment> HeadOfDepartment { get; set; }


        public virtual ICollection<TrackMachineLog> TrackMachineLog { get; set; }

        public virtual ICollection<PayrollExcludedEmployeeFromSalaryProcess> PayrollExcludedEmployeeFromSalaryProcess { get; set; }
        public virtual ICollection<HouseKeepingRegister> HouseKeepingRegister { get; set; }
        public virtual ICollection<EmployeeShortLeave> EmployeeShortLeave { get; set; }
        

    }
}
