//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.ObjectModel;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmployeeType : SearchModel<EmployeeType>
    {
        public EmployeeType()
        {
            this.EmployeeCompanyInfoes = new HashSet<EmployeeCompanyInfo>();
            this.EmployeeDesignation = new HashSet<EmployeeDesignation>();
            this.EmployeeGrades = new HashSet<EmployeeGrade>();
            this.EmployeeLeaves = new HashSet<EmployeeLeave>();
            this.LeaveSetting = new HashSet<LeaveSetting>();
            this.SalarySetup = new HashSet<SalarySetup>();
            this.UserPermissionForEmployeeLevel = new Collection<UserPermissionForEmployeeLevel>();
            this.EmployeeGrade = new Collection<EmployeeGrade>();
        }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int Id { get; set; }



        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.EmployeeTypeValidationExpression, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string Title { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string TitleInBengali { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CDT { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EDT { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }

        public virtual ICollection<EmployeeCompanyInfo> EmployeeCompanyInfoes { get; set; }
        public virtual ICollection<EmployeeDesignation> EmployeeDesignation { get; set; }
        public virtual ICollection<EmployeeGrade> EmployeeGrades { get; set; }
        public virtual ICollection<EmployeeLeave> EmployeeLeaves { get; set; }
        public virtual ICollection<LeaveSetting> LeaveSetting { get; set; }
        public virtual ICollection<SalarySetup> SalarySetup { get; set; }
        public virtual ICollection<UserPermissionForEmployeeLevel> UserPermissionForEmployeeLevel { get; set; }
        public virtual ICollection<EmployeeGrade> EmployeeGrade { get; set; }
    }

}

