//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Model;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class EmployeeWorkShift : SearchModel<EmployeeWorkShift>
    {
        public int EmployeeWorkShiftId { get; set; }
        public System.Guid EmployeeId { get; set; }

        [Required(ErrorMessage = "Required")]
        public int BranchUnitWorkShiftId { get; set; }
  
        public System.DateTime ShiftDate { get; set; }
        public string Remarks { get; set; }
        public bool Status { get; set; }

        [DataType(DataType.Date)]
        public DateTime? StartDate { get; set; }

        [DataType(DataType.Date)]
        public DateTime? EndDate { get; set; }

        public int CheckingBranchUnitWorkShiftId { get; set; }

        [DataType(DataType.Date)]
        public DateTime? CheckingShiftDate { get; set; }

        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual BranchUnitWorkShift BranchUnitWorkShift { get; set; }
    }
}
