//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSkillLevel
    {
        public EmployeeSkillLevel()
        {
            this.EmployeeSkillSets = new HashSet<EmployeeSkillSet>();
        }
    
        public int Id { get; set; }
        public byte SkillLevel { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<EmployeeSkillSet> EmployeeSkillSets { get; set; }
    }
}
