//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Employment
    {
        [Required]
        public int Id { get; set; }

        [Required]
        public System.Guid EmployeeId { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.CompanyNameValidationExpression, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string CompanyName { get; set; }
       
        [RegularExpression(CustomRegEx.FullAddressValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string CompanyAddress { get; set; }

        [RegularExpression(CustomRegEx.DepartmentNameValidationExpression, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string Department { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.ContactPersonDesignationValidationExpression, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string Designation { get; set; }

        [RegularExpression(CustomRegEx.ResponsibilityValidationExpression, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string Respinsibilities { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> FromDate { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ToDate { get; set; }

        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }

        [Required]
        public bool IsActive { get; set; }

        public virtual Employee Employee { get; set; }
    }
}
