//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using SCERP;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class EmployeeDesignation : SearchModel<EmployeeDesignation>
    {
        public EmployeeDesignation()
        {
            this.EmployeeCompanyInfo = new HashSet<EmployeeCompanyInfo>();
            this.OvertimeSettings = new Collection<OvertimeSettings>();
            this.AttendanceBonus = new HashSet<AttendanceBonus>();
        }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int Id { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.EmployeeDesignationValidationExpression, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string Title { get; set; }


        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string TitleInBengali { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int GradeId { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int EmployeeTypeId { get; set; }

        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }

        public virtual EmployeeType EmployeeType { get; set; }
        public virtual EmployeeGrade EmployeeGrade { get; set; }
        public virtual CompanyOrganogram CompanyOrganogram { get; set; }
        public virtual ICollection<EmployeeCompanyInfo> EmployeeCompanyInfo { get; set; }
        public virtual ICollection<OvertimeSettings> OvertimeSettings { get; set; }
        public virtual ICollection<AttendanceBonus> AttendanceBonus { get; set; }
    }
}
