//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class EmployeeCompanyInfo : SearchModel<EmployeeCompanyInfo>
    {

        public Nullable<long> RowNumber { get; set; }
        public int TotalRows { get; set; }

        public int EmployeeCompanyInfoId { get; set; }
        public System.Guid EmployeeId { get; set; }
        public int BranchUnitId { get; set; }
        public int BranchUnitDepartmentId { get; set; }
        public int EmployeeTypeId { get; set; }
        public int DesignationId { get; set; }
        public int? DepartmentSectionId { get; set; }
        public int? DepartmentLineId { get; set; }
        public int? JobTypeId { get; set; }

        [RegularExpression(CustomRegEx.PunchCardValidationExpression, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string PunchCardNo { get; set; }

        [Required(ErrorMessage = "Required!")]
        public bool IsEligibleForOvertime { get; set; }

        [Required(ErrorMessage = "Required!")]
        [DataType(DataType.Date)]
        public System.DateTime? FromDate { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ToDate { get; set; }

        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }

        public bool IsActive { get; set; }

        public virtual BranchUnitDepartment BranchUnitDepartment { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual EmployeeDesignation EmployeeDesignation { get; set; }
        public virtual DepartmentSection DepartmentSection { get; set; }
        public virtual DepartmentLine DepartmentLine { get; set; }
        public virtual SkillSet SkillSet { get; set; }
    }
}
