//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class EmployeeBankInfo
    {
        public EmployeeBankInfo()
        {

        }

        public int Id { get; set; }

        [Required]
        public System.Guid EmployeeId { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.BankNameValidationExpression, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string BankName { get; set; }
      
        [RegularExpression(CustomRegEx.BranchNameValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string BranchName { get; set; }

        public int? AccountTypeId { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.AccountNameValidationExpression, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string AccountName { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.AccountNumberValidationExpression, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string AccountNumber { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> FromDate { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ToDate { get; set; }

        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }

        [Required]
        public bool IsActive { get; set; }

        public virtual Employee Employee { get; set; }

        public virtual BankAccountType BankAccountType { get; set; }
    }
}
