//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class Entitlement : SearchModel<Entitlement>
    {
        public Entitlement()
        {
            this.EmployeeEntitlement = new HashSet<EmployeeEntitlement>();
        }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int Id { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.BenefitTitleValidationExpression, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string Title { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string TitleInBengali { get; set; }

        public string Description { get; set; }

        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }

        public bool IsActive { get; set; }

        public virtual ICollection<EmployeeEntitlement> EmployeeEntitlement { get; set; }
    }
}
