//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class GeneralDaySetup : SearchModel<GeneralDaySetup>
    {
        public int GeneralDaySetupId { get; set; }
        public int BranchUnitDepartmentId { get; set; }

        [DataType(DataType.Date)]
        [Required]
        public System.DateTime? DeclaredDate { get; set; }

        public string Description { get; set; }

        [Required]
        public bool IsAllowedInternal { get; set; }

        [Required]
        public bool IsAllowedExternal { get; set; }

        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }

        public virtual BranchUnitDepartment BranchUnitDepartment { get; set; }
    }
}
