//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model.HRMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrmSkillMatrixDetail
    {
        public int SkillMatrixDetailId { get; set; }
        public int SkillMatrixId { get; set; }
        public int SkillMatrixProcessId { get; set; }
        public int ProcessPercentage { get; set; }
        public int SkillMatrixGradeId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
        public string CompId { get; set; }
    
        public virtual HrmSkillMatrix HrmSkillMatrix { get; set; }
        public virtual HrmSkillMatrixGrade HrmSkillMatrixGrade { get; set; }
        public virtual HrmSkillMatrixProcess HrmSkillMatrixProcess { get; set; }
    }
}
