//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model.HRMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrmSkillMatrixProcess
    {
        public HrmSkillMatrixProcess()
        {
            this.HrmSkillMatrixDetail = new HashSet<HrmSkillMatrixDetail>();
        }
    
        public int SkillMatrixProcessId { get; set; }
        public string ProcessName { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
        public string CompId { get; set; }
    
        public virtual ICollection<HrmSkillMatrixDetail> HrmSkillMatrixDetail { get; set; }
    }
}
