//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class LeaveSetting : SearchModel<LeaveSetting>
    {
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int Id { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int EmployeeTypeId { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int LeaveTypeId { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int BranchUnitId { get; set; }


        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.NoOfDaysValidationExpression, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public int? NoOfDays { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.NoOfDaysValidationExpression, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public int? MaximumAtATime { get; set; }


        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }

        public virtual EmployeeType EmployeeType { get; set; }
        public virtual LeaveType LeaveType { get; set; }
        public virtual BranchUnit BranchUnit { get; set; }
    }
}
