//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Linq.Expressions;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Line : SearchModel<Line>
    {        
        public Line()
        {     
            this.DepartmentLine = new HashSet<DepartmentLine>();
            this.EmployeeCompanyInfoes = new HashSet<EmployeeCompanyInfo>();
            this.PLAN_ProductionLine = new HashSet<PLAN_ProductionLine>();
        }

       [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int LineId { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.LineNameValidationExpression, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string Name { get; set; }

       [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string NameInBengali { get; set; }

        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }

        
        public virtual ICollection<DepartmentLine> DepartmentLine { get; set; }
        public virtual ICollection<EmployeeCompanyInfo> EmployeeCompanyInfoes { get; set; }
        public virtual ICollection<PLAN_ProductionLine> PLAN_ProductionLine { get; set; }
    }
}
