//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class MaritalState : SearchModel<MaritalState>
    {
        public MaritalState()
        {
            this.Employee = new HashSet<Employee>();
        }

        public int MaritalStateId { get; set; }


        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.MaritialStatusValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string Title { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string TitleInBengali { get; set; }

        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public bool IsActive { get; set; }

        public virtual ICollection<Employee> Employee { get; set; }
    }
}
