//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PoliceStation: SearchModel<PoliceStation>
    {
        public PoliceStation()
        {
            this.Branch = new HashSet<Branch>();
            this.Company = new HashSet<Company>();
            this.EmployeePermanentAddress = new HashSet<EmployeePermanentAddress>();
            this.EmployeePresentAddress = new HashSet<EmployeePresentAddress>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage = "Required!")]
        [RegularExpression(@"^([a-zA-Z\s\-])+$", ErrorMessage = "Invalid format!")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Required!")]
        public string NameInBengali { get; set; }

        [Required(ErrorMessage = "Required!")]
        public int DistrictId { get; set; }

        [Required(ErrorMessage = "Required!")]
        public int CountryId { get; set; }

        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Branch> Branch { get; set; }
        public virtual ICollection<Company> Company { get; set; }
        public virtual District District { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<EmployeePermanentAddress> EmployeePermanentAddress { get; set; }
        public virtual ICollection<EmployeePresentAddress> EmployeePresentAddress { get; set; }
    }
}
