//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class SkillOperation : SearchModel<SkillOperation>
    {
        public SkillOperation()
        {
            this.EfficiencyRate = new HashSet<EfficiencyRate>();
            this.EmployeeSkill = new HashSet<EmployeeSkill>();
     
        }
    
        public int SkillOperationId { get; set; }
        public int CategoryId { get; set; }
        public int SkillSetDifficultyId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }

       
        public virtual ICollection<EfficiencyRate> EfficiencyRate { get; set; }
        public virtual ICollection<EmployeeSkill> EmployeeSkill { get; set; }
        public virtual SkillSetCategory SkillSetCategory { get; set; }
        public virtual SkillSetDifficulty SkillSetDifficulty { get; set; }
        
    
    }
}
