//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillLevel
    {
        public SkillLevel()
        {
            this.EmployeeSkillSets = new HashSet<EmployeeSkillSet>();
        }

        public int SkillLevelId { get; set; }
        public int SkillLevel1 { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }

        public virtual ICollection<EmployeeSkillSet> EmployeeSkillSets { get; set; }
    }
}
