//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class SkillSetDifficulty : SearchModel<SkillSetDifficulty>
    {
        public SkillSetDifficulty()
        {
            this.SkillOperation = new HashSet<SkillOperation>();
        }
    
        public int SkillSetDifficultyId { get; set; }
        public string DifficultyName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<SkillOperation> SkillOperation { get; set; }
    }
}
