//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Unit : SearchModel<Unit>
    {
        public Unit()
        {
            this.BranchUnit = new HashSet<BranchUnit>();
            this.UnitDepartments = new HashSet<UnitDepartment>();
        }

        public int UnitId { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.UnitNameValidationExpression, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string Name { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string NameInBengali { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }

        public virtual ICollection<BranchUnit> BranchUnit { get; set; }
        public virtual ICollection<UnitDepartment> UnitDepartments { get; set; }
    }
}
