//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEmployeeIDCardInfoInBengali
    {
        public System.Guid EmployeeId { get; set; }
        public string CardId { get; set; }
        public string EmployeeCardId { get; set; }
        public string Name { get; set; }
        public string CompanyName { get; set; }
        public string Branch { get; set; }
        public string Unit { get; set; }
        public string Department { get; set; }
        public string Section { get; set; }
        public string Line { get; set; }
        public string Designation { get; set; }
        public string Grade { get; set; }
        public string EmployeeJobType { get; set; }
        public string JoiningDate { get; set; }
        public int BranchUnitDepartmentId { get; set; }
        public Nullable<int> DepartmentSectionId { get; set; }
        public Nullable<int> DepartmentLineId { get; set; }
        public string PhotographPath { get; set; }
        public int BranchId { get; set; }
        public int CompanyId { get; set; }
        public int EmployeeTypeId { get; set; }
        public string BloodGroup { get; set; }
        public string FathersNameInBengali { get; set; }
        public string MailingAddressInBengali { get; set; }
        public string PostOfficeInBengali { get; set; }
        public string PoliceStationInBengali { get; set; }
        public string DistrictNameInBengali { get; set; }
        public string EmergencyPhoneInBengali { get; set; }
        public string NationalIdNo { get; set; }
        public string BirthRegistrationNo { get; set; }
    }
}
