//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEmployeeShortLeave
    {
        public int Id { get; set; }
        public System.Guid EmployeeId { get; set; }
        public byte ReasonType { get; set; }
        public string ReasonDescription { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan FromTime { get; set; }
        public System.TimeSpan ToTime { get; set; }
        public Nullable<System.TimeSpan> TotalHours { get; set; }
        public string Designation { get; set; }
        public string EmployeeCardId { get; set; }
        public string EmployeeName { get; set; }
        public string CompanyName { get; set; }
        public string BranchName { get; set; }
        public string UnitName { get; set; }
        public string DepartmentName { get; set; }
        public string SectionName { get; set; }
        public string LineName { get; set; }
        public string EmployeeTypeTitle { get; set; }
        public int CompanyId { get; set; }
        public int BranchId { get; set; }
        public int BranchUnitId { get; set; }
        public int BranchUnitDepartmentId { get; set; }
        public Nullable<int> DepartmentSectionId { get; set; }
        public Nullable<int> DepartmentLineId { get; set; }
        public int EmployeeTypeId { get; set; }
        public int EmployeeGradeId { get; set; }
        public string EmployeeGradeName { get; set; }
    }
}
