//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class WorkShift : SearchModel<WorkShift>
    {
        public WorkShift()
        {
            this.BranchUnitWorkShift = new HashSet<BranchUnitWorkShift>();
        }

        public int WorkShiftId { get; set; }


        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.WorkShiftNameValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string Name { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string NameInBengali { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]        
        public string NameDetail { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string NameDetailInBengali { get; set; }

        public System.TimeSpan StartTime { get; set; }

        public System.TimeSpan EndTime { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [Range(0, int.MaxValue, ErrorMessage = "Assign positive number")]
        public int InBufferTime { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [Range(0, int.MaxValue, ErrorMessage = "Assign positive number")]
        public int MaxBeforeTime { get; set; }


        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [Range(0, int.MaxValue, ErrorMessage = "Assign positive number")]
        public int MaxAfterTime { get; set; }


        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [Range(0, int.MaxValue, ErrorMessage = "Assign positive number")]
        public int ExceededMaxAfterTime { get; set; }

        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }

        public virtual ICollection<BranchUnitWorkShift> BranchUnitWorkShift { get; set; }
    }
}
