//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class WorkGroup : SearchModel<WorkGroup>
    {
        public WorkGroup()
        {
            this.EmployeeWorkGroups = new HashSet<EmployeeWorkGroup>();
        }


        public int WorkGroupId { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(CustomRegEx.WorkGroupNameValidationException, ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string Name { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string NameInBengali { get; set; }

        [Required]
        public int BranchUnitId { get; set; }

        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }

        [Required]
        public bool IsActive { get; set; }

        public virtual BranchUnit BranchUnit { get; set; }
        public virtual ICollection<EmployeeWorkGroup> EmployeeWorkGroups { get; set; }
    }
}
