//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class EmployeeSalary
    {
        public int Id { get; set; }

        [Required]
        public System.Guid EmployeeId { get; set; }


        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(@"^([\d\.])+$", ErrorMessage = "Invalid format!")]
        public decimal GrossSalary { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(@"^([\d\.])+$", ErrorMessage = "Invalid format!")]
        public decimal BasicSalary { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(@"^([\d\.])+$", ErrorMessage = "Invalid format!")]
        public decimal HouseRent { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(@"^([\d\.])+$", ErrorMessage = "Invalid format!")]
        public decimal MedicalAllowance { get; set; }

        [RegularExpression(@"^([\d\.])+$", ErrorMessage = "Invalid format!")]
        public decimal? FoodAllowance { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [RegularExpression(@"^([\d\.])+$", ErrorMessage = "Invalid format!")]
        public decimal Conveyance { get; set; }

        [RegularExpression(@"^([\d\.])+$", ErrorMessage = "Invalid format!")]
        public decimal? EntertainmentAllowance { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [DataType(DataType.Date)]
        public System.DateTime? FromDate { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ToDate { get; set; }

        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }

        public bool IsActive { get; set; }


        public virtual Employee Employee { get; set; }
    }
}
