//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class OvertimeEligibleEmployee : SearchModel<OvertimeEligibleEmployee>
    {
        public int OvertimeEligibleEmployeeId { get; set; }
        public System.Guid EmployeeId { get; set; }
        [Required(ErrorMessage = "Required!")]
        [DataType(DataType.Date)]
        public System.DateTime OvertimeDate { get; set; }
        [Required(ErrorMessage = "Required!")]
        [DataType(DataType.Text)]
        [Range(2, 3,ErrorMessage ="2 or 3")]
        public decimal? OvertimeHour { get; set; }
        public string Remarks { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Employee Employee { get; set; }

  
    }
}
