//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_ProgramDetail
    {
        public long ProgramDetailId { get; set; }
        public long ProgramId { get; set; }
        public string CompId { get; set; }
        public string PrgramRefId { get; set; }
        public string MType { get; set; }
        public string ItemCode { get; set; }
        public string ColorRefId { get; set; }
        public string LotRefId { get; set; }
        public string SizeRefId { get; set; }
        public string FinishSizeRefId { get; set; }
        public string SleeveLength { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<double> Rate { get; set; }
        public string GSM { get; set; }
        public string Remarks { get; set; }
        public double YRatio { get; set; }
        public int? NoOfCone { get; set; }
        public string ComponentRefId { get; set; }
        public virtual PLAN_Program PLAN_Program { get; set; }
    }
}
