//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace SCERP.Model.Planning
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_TargetProduction
    {
        public PLAN_TargetProduction()
        {
            this.PLAN_TargetProductionDetail = new HashSet<PLAN_TargetProductionDetail>();
        }
    
        public long TargetProductionId { get; set; }
        public string CompId { get; set; }
        [Required(ErrorMessage ="Required!!")]
        public string TargetProductionRefId { get; set; }

        public string BuyerRefId { get; set; }

        [Required(ErrorMessage = "Required!!")]
        public string OrderStyleRefId { get; set; }
        [Required(ErrorMessage = "Required!!")]
        public string OrderNo { get; set; }
         [Required(ErrorMessage = "Please select required Line")]
        public int LineId { get; set; }
        [Range(1, int.MaxValue, ErrorMessage = "Please enter a value bigger than {1}")]
        [Required(ErrorMessage = "Required!!")]
         public int TotalTargetQty { get; set; }
       
        [Required(ErrorMessage = "Missing Start Date!!")]
        public Nullable<System.DateTime> StartDate { get; set; }
         [Required(ErrorMessage = "Missing End Date!!")]
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public virtual Production_Machine Production_Machine { get; set; }
        public virtual ICollection<PLAN_TargetProductionDetail> PLAN_TargetProductionDetail { get; set; }
    }
}
