//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model.CommonModel;
using SCERP.Model.InventoryModel;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class PLAN_Program : ProSearchModel<PLAN_Program>
    {
        public PLAN_Program()
        {
            this.PLAN_ProgramDetail = new HashSet<PLAN_ProgramDetail>();
            this.Inventory_FabricReturn = new HashSet<Inventory_FabricReturn>();
            this.PROD_KnittingRoll = new HashSet<PROD_KnittingRoll>();
        }

        public long ProgramId { get; set; }
        public string CompId { get; set; }
        public string ProgramRefId { get; set; }
           [Required(ErrorMessage =CustomErrorMessage.RequiredErrorMessage)]
        public Nullable<System.DateTime> PrgDate { get; set; }
           [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string ProcessRefId { get; set; }
        public string ProcessorRefId { get; set; }
           [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string Attention { get; set; }
           [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string BuyerRefId { get; set; }
           [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string OrderNo { get; set; }
           [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string OrderStyleRefId { get; set; }

        public string ProgramType { get; set; }
        public string CID { get; set; }
        public string xStatus { get; set; }
        public string Rmks { get; set; }
        public string CGRID { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public long PartyId { get; set; }
        public Party Party { get; set; }
        public bool IsApproved { get; set; }
        public Guid? ApprovedBy { get; set; }
        public Guid? PrepairedBy { get; set; }
        public bool? IsLock { get; set; }
        public virtual ICollection<Inventory_FabricReturn> Inventory_FabricReturn { get; set; }
        public virtual ICollection<PLAN_ProgramDetail> PLAN_ProgramDetail { get; set; }
        public virtual ICollection<PROD_KnittingRoll> PROD_KnittingRoll { get; set; }
    }
}
