//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model.Planning
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAN_TargetProductionDetail
    {
        public long TragetProductionDetailId { get; set; }
        public string CompId { get; set; }
        public long TargetProductionId { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public int TargetQty { get; set; }
    
        public virtual PLAN_TargetProduction PLAN_TargetProduction { get; set; }
    }
}
