//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class PLAN_ProductionLineStatus : SearchModel<PLAN_ProductionLineStatus>
    {
        public int ProductionLineStatusId { get; set; }
        public System.DateTime Date { get; set; }
        public int ProductionLineId { get; set; }
        public Nullable<int> NoOfOperator { get; set; }
        public Nullable<int> WorkingMinutes { get; set; }
        public Nullable<int> ProjectedEfficiency { get; set; }
        public Nullable<int> ActualEfficiency { get; set; }
        public Nullable<int> ProjectedCapacity { get; set; }
        public Nullable<int> ActualCapacity { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
    }
}
