//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Mrc_TimeAndActionCalendar
    {
        public Mrc_TimeAndActionCalendar()
        {
            this.NotificationRecipients = new HashSet<NotificationRecipient>();
        }

        public int TimeAndActionId { get; set; }


        [Required]
        public int SpecSheetId { get; set; }

        [Required]
        [DisplayName("Keyprocess")]
        public int KeyProcessId { get; set; }

        [DisplayName("Planned start date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> PlannedStartDate { get; set; }

        [DisplayName("Planned end date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> PlannedEndDate { get; set; }

        [DisplayName("Actual start date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ActualStartDate { get; set; }

        [DisplayName("Actual end date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ActualEndDate { get; set; }

        [DisplayName("Department name")]
        public Nullable<int> DepartmentId { get; set; }

        [DisplayName("Responsible person")]
        public Nullable<System.Guid> ResponsiblePersonId { get; set; }
        [DisplayName("Notify before days")]
        public Nullable<int> NotifyBeforeDays { get; set; }
        [DisplayName("Notification Interval In Hour")]
        public Nullable<int> NotificationIntervalInHour { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }

        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Mrc_KeyProcess Mrc_KeyProcess { get; set; }
        public virtual Mrc_SpecificationSheet Mrc_SpecificationSheet { get; set; }
        public virtual ICollection<NotificationRecipient> NotificationRecipients { get; set; }
    }
}
