//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using SCERP.Model.CommercialModel;
using SCERP.Model.InventoryModel;
using SCERP.Model.MerchandisingModel;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using SCERP.Model.CommonModel;
    using System;
    using System.Collections.Generic;

    public partial class Mrc_SupplierCompany : ProSearchModel<Mrc_SupplierCompany>
    {
        public Mrc_SupplierCompany()
        {
         
            this.CommBbLcInfo = new HashSet<CommBbLcInfo>();
            this.Inventory_ItemStore = new Collection<Inventory_ItemStore>();
            this.Inventory_Booking = new HashSet<Inventory_Booking>();
            this.OM_FabricOrder = new HashSet<OM_FabricOrder>();
            this.OM_ConsumptionSupplier=new HashSet<OM_ConsumptionSupplier>();
            this.ProFormaInvoice = new HashSet<ProFormaInvoice>();
        }

        public int SupplierCompanyId { get; set; }
        [Required(ErrorMessage = "Required!")]
        [Display(Name = "Company Name:")]
        public string CompanyName { get; set; }
        [Display(Name = "Contact Name :")]
        public string ContactName { get; set; }
        public string SupplierCode { get; set; }
          [Display(Name = "Address :")]
        public string Address { get; set; }
           [Display(Name = "Email :")]
        public string Email { get; set; }
            [Display(Name = "Phone :")]
        public string Phone { get; set; }
          [Display(Name = "Web :")]
        public string Web { get; set; }
            [Display(Name = "Fax :")]
        public string Fax { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
        public virtual ICollection<CommBbLcInfo> CommBbLcInfo { get; set; }
     
        public virtual ICollection<Inventory_Booking> Inventory_Booking { get; set; }
        public virtual ICollection<Inventory_MaterialReceiveAgainstPo> Inventory_MaterialReceiveAgainstPo { get; set; }
        public virtual ICollection<OM_FabricOrder> OM_FabricOrder { get; set; }
        public virtual ICollection<Inventory_ItemStore> Inventory_ItemStore { get; set; }
        public virtual ICollection<PROD_CuttingTagSupplier> PROD_CuttingTagSupplier { get; set; }
        public virtual ICollection<OM_ConsumptionSupplier> OM_ConsumptionSupplier { get; set; }
        public virtual ICollection<ProFormaInvoice> ProFormaInvoice { get; set; }
        
    }
}
