//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationRecipient:BaseModel
    {
        public int NotificationRecipientId { get; set; }
        public int TimeAndActionId { get; set; }
        public string SendCopyToEmail { get; set; }
        public string SendCopyToPhone { get; set; }
        public bool IsNotifyByEmail { get; set; }
        public bool IsNotifyByPhone { get; set; }
        public bool IsNotifyByPortal { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Mrc_TimeAndActionCalendar Mrc_TimeAndActionCalendar { get; set; }
    }
}
