//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using SCERP.Common;
using SCERP.Model.InventoryModel;
using SCERP.Model.MerchandisingModel;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_Buyer:ProSearchModel<OM_Buyer>
    {
        public OM_Buyer()
        {
            this.Inventory_Booking = new HashSet<Inventory_Booking>();
            this.OM_CostSheetMaster=new List<OM_CostSheetMaster>();
            this.OM_SampleOrder=new HashSet<OM_SampleOrder>();
        }
        [Required]
        public long BuyerId { get; set; }
        public string BuyerRefId { get; set; }
        public string CompId { get; set; }
        [Required(ErrorMessage = "Required !!")]
        [Remote("CheckExistingBuyer", "OmBuyer", HttpMethod = "POST", AdditionalFields = "BuyerId", ErrorMessage = @"Buyer already exists!")]
        public string BuyerName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        [Required(ErrorMessage = "City Missing!")]
        public int CityId { get; set; }
          [Required(ErrorMessage = "Country Missing!")]
        public int CountryId { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string EMail { get; set; }
        public string Remarks { get; set; }
        public string xStatus { get; set; }
        public string EmpId { get; set; }
        public string ACode { get; set; }
        public virtual ICollection<Inventory_Booking> Inventory_Booking { get; set; }
        public virtual ICollection<OM_SampleOrder> OM_SampleOrder { get; set; }
        public virtual ICollection<OM_CostSheetMaster> OM_CostSheetMaster { get; set; }
    }
}
