//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model.MerchandisingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_BulkBooking
    {
        public OM_BulkBooking()
        {
            this.OM_BulkBookingDetail = new HashSet<OM_BulkBookingDetail>();
        }
    
        public long BulkBookingId { get; set; }
        public string BulkBookingRefId { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string Attention { get; set; }
        public int MerchadiserId { get; set; }
        public string Note { get; set; }
        public string CompId { get; set; }

        public virtual ICollection<OM_BulkBookingDetail> OM_BulkBookingDetail { get; set; }
        public virtual OM_Merchandiser OM_Merchandiser { get; set; }
    }
}
