//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    public partial class OM_BuyOrdShip:ProSearchModel<OM_BuyOrdShip>
    {
        public int OrderShipId { get; set; }
         [Required]
        public string CompId { get; set; }
        public string OrderShipRefId { get; set; }
        public string OrderNo { get; set; }
        public string OrderStyleRefId { get; set; }
        public string LotNo { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Nullable<System.DateTime> ShipDate { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int? CountryId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string PortOfLoadingRefId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Nullable<decimal> Quantity { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string IModeRefId { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DeliveryDate { get; set; }

        public string StyleIRefId { get; set; }
        public Nullable<decimal> JobQty { get; set; }
        public Nullable<decimal> FinishQty { get; set; }
        public Nullable<int> ShipRowId { get; set; }
        public Nullable<decimal> ProductionQty { get; set; }
        [Display(Name = "Despatch Qty")]
        public Nullable<int> DespatchQty { get; set; }
        public string ShipAmend { get; set; }
        public string CINo { get; set; }
           [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public DateTime? ETD { get; set; }

        public string Remarks { get; set; }


    }
}
