//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model.MerchandisingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_BulkBookingYarnDetail
    {
        public long BulkBookingYearnDetailId { get; set; }
        public long BulkBookingDetailId { get; set; }
        public string ColorName { get; set; }
        public string CountName { get; set; }
        public int OrdQty { get; set; }
        public double ConsQty { get; set; }
        public string Remarks { get; set; }
        public string CompId { get; set; }
        public string  ItemName { get; set; }
        public virtual OM_BulkBookingDetail OM_BulkBookingDetail { get; set; }
    }
}
