//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_BuyOrdShipDetail
    {
       
        public long OrderShipDetailId { get; set; }
        public string CompId { get; set; }
        public string OrderShipRefId { get; set; }
        public string ColorRefId { get; set; }
        public string SizeRefId { get; set; }
        [Required(ErrorMessage = "Required")]
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> QuantityP { get; set; }
        public Nullable<decimal> PAllow { get; set; }
        public Nullable<int> ColorRow { get; set; }
        public Nullable<int> SizeRow { get; set; }
        public Nullable<int> ShQty { get; set; }
    }
}
