//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;


    public partial class OM_BuyOrdStyle : ProSearchModel<OM_BuyOrdStyle>
    {
        public long OrderStyleId { get; set; }
         [Required]
        public string CompId { get; set; }
        public string OrderStyleRefId { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Required")]
        public Nullable<System.DateTime> StyleentDate { get; set; }
        public string OrderNo { get; set; }
         [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string StyleRefId { get; set; }
        
        public string BuyerArt { get; set; }
       [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string SeasonRefId { get; set; }
    
        public string BrandRefId { get; set; }
        public string CatIRefId { get; set; }
        public string Rmks { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> DiscPer { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public Nullable<decimal> ProductionQty { get; set; }
        public string WORKORDER { get; set; }
        public Nullable<decimal> JobQty { get; set; }
        public Nullable<bool> IsCostEstimated { get; set; }
        public Nullable<decimal> AllowancePer { get; set; }
        public string PackplanThru { get; set; }
        public string Amend { get; set; }
        public string YarnAmend { get; set; }
        public string AccAmend { get; set; }
        public string PackAmend { get; set; }
        public string DespatchClosed { get; set; }
        public Nullable<decimal> despatchQty { get; set; }
        public string UnitType { get; set; }
        public string CutGAmend { get; set; }
        public Nullable<int> GroupedStyleId { get; set; }
        public Nullable<bool> IsGrouped { get; set; }
        public string TransferredTo { get; set; }
        public Nullable<int> CompanyUnitId { get; set; }
        public string Transfer { get; set; }
        public Nullable<int> BaseUnit { get; set; }
        public Nullable<int> EnquiryId { get; set; }
        public string BuyerItem { get; set; }
        public string OpenPrgAmend { get; set; }
        public Nullable<int> GUOMid { get; set; }
        public Nullable<short> GUomConv { get; set; }
        public Nullable<int> StyleGroupId { get; set; }
        public Nullable<int> StyleDeptId { get; set; }
        public Nullable<int> QCId { get; set; }
        public Nullable<int> QuotationId { get; set; }
        public string GroupItem { get; set; }
        public Nullable<int> FitId { get; set; }
        public string MisView { get; set; }
        public string PI { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string LCSTID { get; set; }
        public Nullable<System.DateTime> YBD { get; set; }
        public Nullable<System.DateTime> YRD { get; set; }
        public Nullable<System.DateTime> FBD { get; set; }
        public Nullable<System.DateTime> KSD { get; set; }
        public Nullable<System.DateTime> KCD { get; set; }
        public Nullable<System.DateTime> DSD { get; set; }
        public Nullable<System.DateTime> DCD { get; set; }
        public Nullable<System.DateTime> PAD { get; set; }
        public Nullable<System.DateTime> CSD { get; set; }
        public Nullable<System.DateTime> CCD { get; set; }
        public Nullable<System.DateTime> IPD { get; set; }
        public Nullable<System.DateTime> SSD { get; set; }
        public Nullable<System.DateTime> SCD { get; set; }
        public Nullable<System.DateTime> FSD { get; set; }
        public Nullable<System.DateTime> FCD { get; set; }
        public Nullable<System.DateTime> IND { get; set; }
        public Nullable<System.DateTime> EFD { get; set; }
        public Nullable<System.DateTime> EXD { get; set; }
        public Nullable<System.DateTime> PSD { get; set; }
        public Nullable<System.DateTime> LCR { get; set; }
        public Nullable<System.DateTime> YID { get; set; }
        public Nullable<System.DateTime> AID { get; set; }
        public Nullable<int> KnMC { get; set; }
        public string Factory { get; set; }
        public Nullable<decimal> KnProd { get; set; }
        public Nullable<int> KnDays { get; set; }
        public Nullable<int> LnDays { get; set; }
        public Nullable<System.DateTime> LCD { get; set; }
        public Nullable<System.DateTime> BZF { get; set; }
        public Nullable<System.DateTime> EMF { get; set; }
        public Nullable<System.DateTime> ABD { get; set; }
        public Nullable<System.DateTime> TAD { get; set; }
        public Nullable<System.DateTime> PPSD { get; set; }
        public Nullable<System.DateTime> PPMD { get; set; }
        public Nullable<System.DateTime> PSND { get; set; }
        public Nullable<System.DateTime> PRD { get; set; }
        public Nullable<System.DateTime> ESD { get; set; }
        public Nullable<System.DateTime> CCRD { get; set; }
        public Nullable<System.DateTime> LDSD { get; set; }
        public Nullable<System.DateTime> LDAD { get; set; }
        public Nullable<System.DateTime> FID { get; set; }
        public Nullable<System.DateTime> THRD { get; set; }
        public Nullable<System.DateTime> WSD { get; set; }
        public Nullable<System.DateTime> WRD { get; set; }
        public Nullable<System.DateTime> FBDD { get; set; }
        public string FSource { get; set; }
        public Nullable<System.DateTime> ActYBD { get; set; }
        public Nullable<System.DateTime> ActYRD { get; set; }
        public Nullable<System.DateTime> ActFBD { get; set; }
        public Nullable<System.DateTime> ActKSD { get; set; }
        public Nullable<System.DateTime> ActKCD { get; set; }
        public Nullable<System.DateTime> ActDSD { get; set; }
        public Nullable<System.DateTime> ActDCD { get; set; }
        public Nullable<System.DateTime> ActPAD { get; set; }
        public Nullable<System.DateTime> ActCSD { get; set; }
        public Nullable<System.DateTime> ActCCD { get; set; }
        public Nullable<System.DateTime> ActIPD { get; set; }
        public Nullable<System.DateTime> ActSSD { get; set; }
        public Nullable<System.DateTime> ActSCD { get; set; }
        public Nullable<System.DateTime> ActFSD { get; set; }
        public Nullable<System.DateTime> ActFCD { get; set; }
        public Nullable<System.DateTime> ActIND { get; set; }
        public Nullable<System.DateTime> ActEFD { get; set; }
        public Nullable<System.DateTime> ActEXD { get; set; }
        public Nullable<System.DateTime> ActPSD { get; set; }
        public Nullable<System.DateTime> ActYID { get; set; }
        public Nullable<System.DateTime> ActAID { get; set; }
        public Nullable<System.DateTime> ActLCD { get; set; }
        public Nullable<System.DateTime> ActBZD { get; set; }
        public Nullable<System.DateTime> ActEMF { get; set; }
        public Nullable<System.DateTime> ActABD { get; set; }
        public Nullable<System.DateTime> ActTAD { get; set; }
        public Nullable<System.DateTime> ActPPSD { get; set; }
        public Nullable<System.DateTime> ActPPMD { get; set; }
        public Nullable<System.DateTime> ActPSND { get; set; }
        public Nullable<System.DateTime> ActPRD { get; set; }
        public Nullable<System.DateTime> ActESD { get; set; }
        public Nullable<System.DateTime> ActCCRD { get; set; }
        public Nullable<System.DateTime> ActLDSD { get; set; }
        public Nullable<System.DateTime> ActLDAD { get; set; }
        public Nullable<System.DateTime> ActFID { get; set; }
        public Nullable<System.DateTime> ActTHRD { get; set; }
        public Nullable<System.DateTime> ActWSD { get; set; }
        public Nullable<System.DateTime> ActWRD { get; set; }
        public Nullable<System.DateTime> ActFBDD { get; set; }
        public Nullable<System.DateTime> ActBZF { get; set; }
        public Nullable<System.DateTime> SAPD { get; set; }
        public Nullable<System.DateTime> ActSAPD { get; set; }
        public string CGRID { get; set; }
        public string TnaMode { get; set; }
        public bool ActiveStatus { get; set; }
        public string ImagePath { get; set; }
        public double? TtlCm { get; set; }
        public double? TtlSmv { get; set; }

    }
}
