//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class OM_BuyerOrder
    {
        public long BuyerOrderId { get; set; }
        [Required]
        public string CompId { get; set; }
         [Required]
        public string OrderNo { get; set; }
         [Required]
        public Nullable<System.DateTime> OrderDate { get; set; }
         [Required]
        public string RefNo { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public string SampleOrdNo { get; set; }
        public string BuyerRefId { get; set; }
        public string DGRefNo { get; set; }
        public string BuyerRef { get; set; }
         [Required]
        public Nullable<int> Quantity { get; set; }
        public string ManagerId { get; set; }
        public string MerchandiserId { get; set; }
        public string AgentRefId { get; set; }
        public string ShipagentRefId { get; set; }
        public string ConsigneeRefId { get; set; }
        public string PayTermRefId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> Exchange { get; set; }
        public Nullable<decimal> AgencyPer { get; set; }
        public Nullable<int> GUOMId { get; set; }
        public Nullable<short> GUOMConv { get; set; }
        public Nullable<int> BasUnit { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> OrderCategoryId { get; set; }
        public string OrderTypeRefId { get; set; }
        public string SystemRefId { get; set; }
        public string SMode { get; set; }
        public string StyleType { get; set; }
        public Nullable<int> OrdStyleTypeRefId { get; set; }
        public Nullable<int> TeamRefId { get; set; }
        public Nullable<int> PaymentModeRefId { get; set; }
        public Nullable<System.DateTime> CommittedDate { get; set; }
        public string Closed { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<decimal> OAmount { get; set; }
        public string Fab { get; set; }
        public string SCont { get; set; }
        public string OrderStatus { get; set; }
        public string SeasonRefId { get; set; }
        public Nullable<int> LcRefId { get; set; }
        public string TnaMode { get; set; }
    }
}
