//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model.MerchandisingModel
{
    using System;
    using System.Collections.Generic;
    public partial class OM_BulkBookingDetail
    {
        public OM_BulkBookingDetail()
        {
            this.OM_BulkBookingYarnDetail = new HashSet<OM_BulkBookingYarnDetail>();
        }
        public long BulkBookingDetailId { get; set; }
        public long BulkBookingId { get; set; }
        public int SequenceNo { get; set; }
        public string BuyerRefId { get; set; }
        public string OrderNo { get; set; }
        public string StyleNo { get; set; }
        public string ItemName { get; set; }
        public string Fabrication { get; set; }
        public Nullable<double> GSM { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string CompId { get; set; }
    
        public virtual OM_BulkBooking OM_BulkBooking { get; set; }
        public virtual ICollection<OM_BulkBookingYarnDetail> OM_BulkBookingYarnDetail { get; set; }
    }
}
