//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using SCERP.Common;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class OM_Category : ProSearchModel<OM_Category>
    {
        public int CatergoryId { get; set; }
         [Required]
        public string CompId { get; set; }
        public string CatRefId { get; set; }
        [Required(ErrorMessage = "Category Missing!")]
        [Remote("CheckExistingCategory", "OmCategory", HttpMethod = "POST", AdditionalFields = "CatergoryId", ErrorMessage = @"Category already exists!")]
        public string CatName { get; set; }
        public Nullable<bool> Quota { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> QuotaUnit { get; set; }
        public Nullable<decimal> EqualPcs { get; set; }
    }
}
