//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_CostSheetTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OM_CostSheetTemplate()
        {
            this.OM_CostSheetDetail = new HashSet<OM_CostSheetDetail>();
        }
    
        public int TemplateId { get; set; }
        public int SerialNo { get; set; }
        public string Particular { get; set; }
        public int TempGroupId { get; set; }
        public int ItemTypeId { get; set; }
        public string UnitName { get; set; }
        public string CompId { get; set; }
        public Nullable<double> ParticularRate { get; set; }// external filed

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_CostSheetDetail> OM_CostSheetDetail { get; set; }
        public virtual OM_ItemType OM_ItemType { get; set; }
        public virtual OM_TempGroup OM_TempGroup { get; set; }
    }
}
