//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using SCERP.Common;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_CostDefination:ProSearchModel<OM_CostDefination>
    {
        public int CostDefinationId { get; set; }
        public string CompId { get; set; }
        public string CostRefId { get; set; }
        [Required(ErrorMessage = "CostDefination Missing!")]
        [Remote("CheckExistingCostDefination", "CostDefination", HttpMethod = "POST", AdditionalFields = "CostDefinationId", ErrorMessage = @"Name already exists!")]
        public string CostName { get; set; }
        [Required(ErrorMessage = "Group Name Missing!")]
        public string CostGroup { get; set; }
    }
}
