//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_CostSheetMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OM_CostSheetMaster()
        {
            this.OM_CostSheetDetail = new HashSet<OM_CostSheetDetail>();
        }
    
        public long CostSheetMasterId { get; set; }
        public string CostSheetMasterRefId { get; set; }
        public long BuyerId { get; set; } 
        public string OrderNo { get; set; }
        public string StyleNo { get; set; }
        public int? OrderQty { get; set; }
        public string Item { get; set; }
        public string Fabrication { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public string YarnCount { get; set; }
        public double Gsm { get; set; }
        public int ItemTypeId { get; set; }
        public string CompId { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_CostSheetDetail> OM_CostSheetDetail { get; set; }

       public virtual OM_ItemType OM_ItemType { get; set; }
        public virtual OM_Buyer OM_Buyer { get; set; }
    }
}
