//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using SCERP.Common;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_Consignee:ProSearchModel<OM_Consignee>
    {
        public long ConsigneeId { get; set; }
        public string CompId { get; set; }
        public string ConsigneeRefId { get; set; }
        [Required(ErrorMessage = "Consignee Missing!")]
        [Remote("CheckExistingConsignee", "Consignee", HttpMethod = "POST", AdditionalFields = "ConsigneeId", ErrorMessage = @"Consignee already exists!")]
        public string ConsigneeName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string ConsigneeLookup { get; set; }
        public string PackList { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> SourceID { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.CommonErrorMessage)]
        public string BuyerRefId { get; set; }

        public int CItyId { get; set; }
        public int CountryId { get; set; }
        public string ShippingMarks { get; set; }
        public string Suppliercode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string EMail { get; set; }
    }
}
