//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model.MerchandisingModel;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_Consumption:ProSearchModel<OM_Consumption>
    {
        public OM_Consumption()
        {
            this.OM_ConsumptionSupplier=new List<OM_ConsumptionSupplier>();
        }
        public long ConsumptionId { get; set; }
        public string CompId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string ConsRefId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ConsDate { get; set; }
        public string OrderStyleRefId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string ConsGroup { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string ConsTypeRefId { get; set; }
          [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Nullable<decimal> Quantity { get; set; }
        public string ItemCode { get; set; }
        public string OrderNo { get; set; }
        public decimal? Rate { get; set; }
        public int? SupplierId { get; set; }
        public string ItemDescription { get; set; }
        public virtual ICollection<OM_ConsumptionSupplier> OM_ConsumptionSupplier { get; set; }
    }
}
