//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_CompConsumptionDetail
    {
        public long CompConsumptionDetailId { get; set; }
         [Required]
        public string CompID { get; set; }
        public string OrderStyleRefId { get; set; }
        public Nullable<int> CompomentSlNo { get; set; }
        public string ConsRefId { get; set; }
        public string GColorRefId { get; set; }
        public string GSizeRefId { get; set; }
        public string PColorRefId { get; set; }
        public string PSizeRefId { get; set; }
        public Nullable<decimal> GSM { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }

        public Nullable<decimal> PPQty { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> PAllow { get; set; }
        public Nullable<decimal> TQty { get; set; }
        public int LayQty { get; set; }
        public string BaseColorRefId { get; set; }
        public decimal? QuantityP { get; set; }
        public string TableWidthID { get; set; }
        public decimal? ProcessLoss { get; set; }
        public string ApprovedLD { get; set; }
        public int? RequiredQty { get; set; }
    }
}
