//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_Color:ProSearchModel<OM_Color>
    {
        [Required]
        public int ColorId { get; set; }
        public string CompId { get; set; }
        public string ColorRefId { get; set; }
        [Required(ErrorMessage = "Color Name Missing!")]
        [Remote("CheckExistingColor", "OmColor",HttpMethod ="POST", AdditionalFields = "ColorId", ErrorMessage = @"Color already exists!")]
        public string ColorName { get; set; }

        public string ColorCode { get; set; }
   
        public string TypeId { get; set; }

        public string BrandName { get; set; }

    }
}
