//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_CostOrdStyle
    {
        public long CostOrderStyleId { get; set; }
        public string CompId { get; set; }
        public string OrderStyleRefId { get; set; }
        public Nullable<System.DateTime> CostDate { get; set; }
        public string CostRefId { get; set; }
        public decimal CostRate { get; set; }
        public double? Qty { get; set; }
        public string Unit { get; set; }
    }
}
