//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_CompConsumption:ProSearchModel<OM_CompConsumption>
    {
        public long CompConsumptionId { get; set; }
         [Required]
        public string CompId { get; set; }
        public string OrderStyleRefId { get; set; }
        public int ComponentSlNo { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string ConsRefId { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Nullable<System.DateTime> EnDate { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string ComponentRefId { get; set; }
         [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Nullable<int> NParts { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string FabricType { get; set; }
        public string Description { get; set; }
        public string OrderNo { get; set; } //New added
        
    }
}
