//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using SCERP.Model.CommonModel;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_EmbWorkOrder
    {
        public OM_EmbWorkOrder()
        {
            this.OM_EmbWorkOrderDetail = new HashSet<OM_EmbWorkOrderDetail>();
        }
        public int EmbWorkOrderId { get; set; }
        public string RefId { get; set; }
        public long PartyId { get; set; }
        public string MerchandiserRefId { get; set; }
        public string ProcessRefId { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public string Attention { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.Guid> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public string CompId { get; set; }
        public virtual Party Party { get; set; }
        public virtual ICollection<OM_EmbWorkOrderDetail> OM_EmbWorkOrderDetail { get; set; }
    }
}
