//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_EmbWorkOrderDetail
    {
        public int EmbWorkOrderDetailId { get; set; }
        public string BuyerRefId { get; set; }
        public string OrderNo { get; set; }
        public string OrderStyleRefId { get; set; }
        public int EmbWorkOrderId { get; set; }
        public string ItemName { get; set; }
        public string GColorRefId { get; set; }
        public string GSizeRefId { get; set; }
        public string FabricType { get; set; }
        public string EmbellishmentType { get; set; }
        public string ComponentRefId { get; set; }
        public string FinishColor { get; set; }
        public string FinishSize { get; set; }
        public int Qty { get; set; }
        public double Rate { get; set; }
        public string Remarks { get; set; }
        public string CompId { get; set; }
    
        public virtual OM_EmbWorkOrder OM_EmbWorkOrder { get; set; }
    }
}
