//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model.MerchandisingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_FabricOrderDetail
    {
        public int FabricOrderDetailId { get; set; }
        public int FabricOrderId { get; set; }
        public string OrderStyleRefId { get; set; }
        public string CompId { get; set; }
        public bool YLocked { get; set; }
        public Guid? LockedBy { get; set; }
        public DateTime? LockedDate { get; set; }
        public Guid? UnLockedBy { get; set; }
        public DateTime? UnLockedDate { get; set; }
        public virtual OM_FabricOrder OM_FabricOrder { get; set; }
    }
}
