//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_FabConsumption
    {
        public long FabConsumptionId { get; set; }
        public string ConsRefId { get; set; }
        public Nullable<System.DateTime> ConsDate { get; set; }
        public string StyleIRefId { get; set; }
        public string ConsGroup { get; set; }
        public string ConsTypeRefId { get; set; }
        public Nullable<decimal> TotalQty { get; set; }
        public string OrderNo { get; set; }
        public string OrderStyleRefId { get; set; }
        public string CompId { get; set; }
    }
}
