//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;

namespace SCERP.Model.MerchandisingModel
{
    using System;
    using System.Collections.Generic;

    public partial class OM_FabricOrder
    {
        public OM_FabricOrder()
        {
            this.OM_FabricOrderDetail = new HashSet<OM_FabricOrderDetail>();
        }

        public int FabricOrderId { get; set; }
        public string FabricOrderRefId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public int SupplierId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Nullable<System.DateTime> OrderDate { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Nullable<System.DateTime> ExpDate { get; set; }
        public Nullable<System.Guid> PreparedBy { get; set; }
        public string Remarks { get; set; }
         [Required]
        public string CompId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string OrderNo { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string BuyerRefId { get; set; }
        public string MerchandiserRefId { get; set; }
        public string Status { get; set; }
       
        public virtual Mrc_SupplierCompany Mrc_SupplierCompany { get; set; }
        public virtual ICollection<OM_FabricOrderDetail> OM_FabricOrderDetail { get; set; }
    }
}
