//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_ItemType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OM_ItemType()
        {
            this.OM_CostSheetTemplate = new HashSet<OM_CostSheetTemplate>();
            this.OM_CostSheetMaster=new List<OM_CostSheetMaster>();
        }
    
        public int ItemTypeId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string CompId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_CostSheetTemplate> OM_CostSheetTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OM_CostSheetMaster> OM_CostSheetMaster { get; set; }
    }
}
