//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model.InventoryModel;
using SCERP.Model.MerchandisingModel;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_Merchandiser:ProSearchModel<OM_Merchandiser>
    {
        public OM_Merchandiser()
        {
            this.Inventory_Booking = new HashSet<Inventory_Booking>();
            this.OM_BulkBooking = new HashSet<OM_BulkBooking>();
            this.OM_SampleOrder = new List<OM_SampleOrder>();
        }
    
        public int MerchandiserId { get; set; }
        public string CompId { get; set; }
        public string EmpId { get; set; }
        [Required(ErrorMessage =CustomErrorMessage.RequiredErrorMessage)]
        public string EmpName { get; set; }
       
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string TeamLdrId { get; set; }
        public int TeamId { get; set; }
    
        public string Email { get; set; }
      
        public string Phone { get; set; }
        public virtual ICollection<OM_SampleOrder> OM_SampleOrder { get; set; }

        public virtual ICollection<OM_BulkBooking> OM_BulkBooking { get; set; }
        public virtual ICollection<Inventory_Booking> Inventory_Booking { get; set; }
    }
}
