//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using SCERP.Common;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_OrderType:ProSearchModel<OM_OrderType>
    {
        public int OrderTypeId { get; set; }
        public string OTypeRefId { get; set; }
        [Required(ErrorMessage = "OrderType Missing!")]
        [Remote("CheckExistingOrderType", "OrderType", HttpMethod = "POST", AdditionalFields = "OrderTypeId", ErrorMessage = @"OrderType already exists!")]
        public string OTypeName { get; set; }
        public string Prefix { get; set; }
    }
}
