//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using SCERP.Common;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class OM_PaymentTerm : ProSearchModel<OM_PaymentTerm>
    {
        public int PayentTermId { get; set; }
        public string CompId { get; set; }
        public string PayTermRefId { get; set; }
        [Required(ErrorMessage = "PaymentTerm Missing!")]
        [Remote("CheckExistingPaymentTerm", "PaymentTerm", HttpMethod = "POST", AdditionalFields = "PayentTermId", ErrorMessage = @"PaymentTerm already exists!")]

        public string PayTerm { get; set; }
        public decimal ECGCPerc { get; set; }
        public Nullable<decimal> InsurancePerc { get; set; }
        public Nullable<int> CreditDays { get; set; }
        public string PayType { get; set; }
    }
}
