//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using SCERP.Common;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class OM_PortOfLoading : ProSearchModel<OM_PortOfLoading>
    {
        public int PortOfLoadingId { get; set; }
        public string CompId { get; set; }
        public string PortOfLoadingRefId { get; set; }
        [Required(ErrorMessage = "Port Name Missing!")]
        [Remote("CheckExistingPortOfLoading", "PortOfLoading", HttpMethod = "POST", AdditionalFields = "PortOfLoadingId", ErrorMessage = @"Port already exists!")]
        public string PortOfLoadingName { get; set; }
        public int? CountryId { get; set; }
        public Nullable<int> SourceId { get; set; }
        public string PortType { get; set; }
        public virtual Country Country { get; set; }
    }
}
