//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using SCERP.Common;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    public partial class OM_Style : ProSearchModel<OM_Style>
    {
        public long StyleId { get; set; }
        public string CompID { get; set; }
        public string StylerefId { get; set; }
        [Required(ErrorMessage = "Style Name Missing !!")]
        public string StyleName { get; set; }
        public int ItemId { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> SourceId { get; set; }
        public string Department { get; set; }
        public string Season { get; set; }
        public Nullable<int> EnquiryId { get; set; }
        public string TypeId { get; set; }
        public string CatId { get; set; }
        public string PrdId { get; set; }
    }
}
