//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using SCERP.Common;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class OM_Season : ProSearchModel<OM_Season>
    {
        public int SeasonId { get; set; }
        public string CompId { get; set; }
        public string SeasonRefId { get; set; }
        [Required(ErrorMessage = "Season Missing!")] 
        public string SeasonName { get; set; }
    }
}
