//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace SCERP.Model.MerchandisingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_ThreadConsumption
    {
        public OM_ThreadConsumption()
        {
            this.OM_ThreadConsumptionDetail = new HashSet<OM_ThreadConsumptionDetail>();
        }
    
        public int ThreadConsumptionId { get; set; }
        [Required(ErrorMessage = "Required")]
        public string BuyerRefId { get; set; }
            [Required(ErrorMessage = "Required")]
        public string OrderNo { get; set; }
            [Required(ErrorMessage = "Required")]
        public string OrderStyleRefId { get; set; }
            [Required(ErrorMessage = "Required")]
        public string SizeRefId { get; set; }
            [Required(ErrorMessage = "Required")]
        public System.DateTime EntryDate { get; set; }
        public string Remarks { get; set; }
            [Required(ErrorMessage = "Required")]
        public string CompId { get; set; }
        public System.Guid CreatedBy { get; set; }
        public Nullable<System.Guid> ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual ICollection<OM_ThreadConsumptionDetail> OM_ThreadConsumptionDetail { get; set; }
    }
}
