//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace SCERP.Model.MerchandisingModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_ThreadConsumptionDetail
    {
        public int ThreadConsumptionDetailId { get; set; }
        public int ThreadConsumptionId { get; set; }
        [Required(ErrorMessage = "Message")]
        public string ItemName { get; set; }
         [Required(ErrorMessage = "Message")]
        public string Color { get; set; }
         [Required(ErrorMessage = "Message")]
        public string Component { get; set; }
         [Required(ErrorMessage = "Message")]
        public string UnitType { get; set; }
         [Required(ErrorMessage = "Message")]
        public double ConsQty { get; set; }
        public string Remarks { get; set; }
    
        public virtual OM_ThreadConsumption OM_ThreadConsumption { get; set; }
    }
}
