//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class OM_YarnConsumption : ProSearchModel<OM_YarnConsumption>
    {
        public long YarnConsumptionId { get; set; }
        public string CompId { get; set; }
        
        public string ConsRefId { get; set; }
  
        public string GrColorRefId { get; set; }
   
        public string KSizeRefId { get; set; }
        public string KColorRefId { get; set; }
        public Nullable<decimal> CPercent { get; set; }
        public Nullable<decimal> KQty { get; set; }
        public Nullable<decimal> PLoss { get; set; }
        public string DReq { get; set; }
        public Nullable<decimal> WMtr { get; set; }
        public string YCRef { get; set; }
        public string ItemCode { get; set; }
        public decimal? Rate { get; set; }
        public int? SupplierId { get; set; }
        public string PiRefId { get; set; }
    }
}
