//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class VBuyerOrder : ProSearchModel<OM_BuyerOrder>
    {
        public long BuyerOrderId { get; set; }
        public string CompId { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string OrderNo { get; set; }

        [DataType(DataType.Date)]
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Nullable<System.DateTime> OrderDate { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string RefNo { get; set; }

        public Nullable<System.DateTime> RefDate { get; set; }
        public string SampleOrdeNo { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string BuyerRefId { get; set; }

        public string BuyerName { get; set; }
        public string SampleOrdNo { get; set; } // not exit in  view

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string ManagerId { get; set; } // not exit in  view
        public string DGRefNo { get; set; }
        public string BuyerRef { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Nullable<int> Quantity { get; set; }

        public string MerchandiserId { get; set; }
        public string EmpName { get; set; }
        public string AgentRefId { get; set; }
        public string AgentName { get; set; }
        public string ShipagentRefId { get; set; }
        public string SAgentName { get; set; }
        public string ConsigneeRefId { get; set; }
        public string ConsigneeName { get; set; }
        public string PayTermRefId { get; set; }
        public string PayTerm { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string OrderTypeRefId { get; set; }

        public string OTypeName { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string SMode { get; set; }

        public Nullable<int> PaymentModeRefId { get; set; }
        public Nullable<decimal> OAmount { get; set; }
        public string Fab { get; set; }
        public string SCont { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string SeasonRefId { get; set; }

        public string SeasonName { get; set; }

        public Nullable<System.DateTime> ShipDate { get; set; }
        public int TotalStyleInOrder { get; set; }
        public decimal ShipQty { get; set; }
        [Required]
        public string OrderStatus { get; set; }
        [Required]
        public string Remarks { get; set; }
        
        public string MeasurementUnit
        {
            get
            {
                return "Pces";
            }
        }

        public string Status
        {
            get
            {
                return Quantity - ShipQty == 0 ? "Done" : "InProgress";
            }
        }

        public Nullable<int> LcRefId { get; set; }
        public string LcNo { get; set; }

        public int TotalLcRecords { get; set; }

        public string Closed { get; set; }

        public DateTime? CloseDate { get; set; }
    }
}
