//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace SCERP.Model.MerchandisingModel
{
    public partial class VCompConsumptionDetail
    {
        public long CompConsumptionDetailId { get; set; }
        public long CompConsumptionId { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string UnitName { get; set; }
        public string BaseColorName { get; set; }
        public string CompId { get; set; }
        public string GColorName { get; set; }
        public string GSizeName { get; set; }
        public string PColorName { get; set; }
        public string PSizeName { get; set; }
        public string ConsRefId { get; set; }
        public string GColorRefId { get; set; }
        public string GSizeRefId { get; set; }
        public string PColorRefId { get; set; }
        public string PSizeRefId { get; set; }
        public string BaseColorRefId { get; set; }
        public Nullable<decimal> PAllow { get; set; }
        public Nullable<decimal> PPQty { get; set; }
        public Nullable<decimal> TQty { get; set; }
        public Nullable<decimal> GSM { get; set; }
        public Nullable<decimal> Length { get; set; }
        public string OrderStyleRefId { get; set; }
        public string TableWidthID { get; set; }
        public string TableWidth { get; set; }
        public decimal? QuantityP { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<int> CompomentSlNo { get; set; }
        public decimal PDzCons { get; set; } 
        public string ConsTypeRefId { get; set; }
        public string ConsGroup { get; set; }
        public int LayQty { get; set; }
        public decimal? ProcessLoss { get; set; }
        public decimal? GreyQty { get; set; }
        public decimal? YConsQty { get; set; }
        
        public string ApprovedLD { get; set; }
        public int? CompType { get; set; }
        public int? RequiredQty { get; set; }
        public int? SizeRow { get; set; }

  
    }
}
