//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace SCERP.Model.MerchandisingModel
{
    public partial class VCompConsumption
    {
        public long CompConsumptionId { get; set; }
        public string CompId { get; set; }
        public string ConsRefId { get; set; }
        public string OrderStyleRefId { get; set; }
        public Nullable<System.DateTime> EnDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> NParts { get; set; }
        public int ComponentSlNo { get; set; }
        public string FabricType { get; set; }
        public string ComponentRefId { get; set; }
        public string FabricTypeName { get; set; }
        public string ComponentName { get; set; }
        public string FabricName { get; set; }
        public decimal? TCompQty { get; set; }
        public int? CompType { get; set; }
    }
}
