//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using SCERP.Model.Production;

namespace SCERP.Model.MerchandisingModel
{
    public partial class VConsumptionDetail : ProSearchModel<OM_ConsumptionDetail>
    {
  
        public long ConsumptionDetailId { get; set; }
        public long ConsumptionId { get; set; } // new added 
        public string CompId { get; set; }
        public string GColorName { get; set; }
        public string GSizeName { get; set; }
        public string PColorName { get; set; }
        public string PSizeName { get; set; }
        public string ConsRefId { get; set; }
        public string GColorRefId { get; set; }
        public string GSizeRefId { get; set; }
        public string PColorRefId { get; set; }
        public string PSizeRefId { get; set; }
        public decimal? QuantityP { get; set; }
        public Nullable<decimal> PAllow { get; set; }
        public Nullable<decimal> PPQty { get; set; }
        public Nullable<decimal> TotalQty { get; set; }
        public decimal PDzCons { get; set; } // new added 
        public string ConsTypeRefId { get; set; } // new added 
        public decimal PDzQty { get; set; }
        public string Remarks { get; set; }
        public int? SizeRow { get; set; }
      

    }
}
