//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace SCERP.Model.MerchandisingModel
{
    public partial class VConsumption
    {
        public string CompId { get; set; }
        public string OrderNo { get; set; }
        public string OrderName { get; set; }
        public string StyleName { get; set; }
        public string OrderStyleRefId { get; set; }
        public string ConsGroupName { get; set; }
        public string ConsTypeName { get; set; }
        public long ConsumptionId { get; set; }
        public string ConsRefId { get; set; }
        public Nullable<System.DateTime> ConsDate { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string Unit { get; set; }
        public string ConsGroup { get; set; }
        public string ConsTypeRefId { get; set; }
        public decimal? Rate { get; set; }
        public int? SupplierId { get; set; }
        public string SupplierName { get; set; }
        public string ItemDescription { get; set; }
    }
}
