//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SCERP.Model.MerchandisingModel
{
    
    public partial class VOrderStyleDetail
    {
        public string OrderNo { get; set; }
        public string OrderStyleRefId { get; set; }
        public string StyleRefId { get; set; }
        public int ItemId { get; set; }
        public string ColorRefId { get; set; }
        public string SizeRefId { get; set; }
        public int Quantity { get; set; }
        public string ItemName { get; set; }
        public string ColorName { get; set; }
        public string SizeName { get; set; }
        public string CompId { get; set; }
        public string UnitName { get; set; }
        public string ItemCode { get; set; }
    }
}
