//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace SCERP.Model.MerchandisingModel
{
    public  partial class VwConsuptionOrderStyle
    {
        public string MerchandiserId { get; set; }
        public string CompId { get; set; }
        public string StyleName { get; set; }
        public string SeasonName { get; set; }
        public string ItemName { get; set; }
        public string ItemCode { get; set; }
        public string RefNo { get; set; }
        public string BuyerRef { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string OrderNo { get; set; }
        public string OrderStyleRefId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> TotalFabAccessories { get; set; }
        public Nullable<decimal> TotalFabQty { get; set; }
        public Nullable<int> TotalPackingAccessories { get; set; }
        public Nullable<int> TotalAccessories { get; set; }
     
    }
}
