//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    public partial class VwOM_BuyOrdShip
    {
        public int OrderShipId { get; set; }
        public string CompId { get; set; }
        public string OrderShipRefId { get; set; }
        public string OrderNo { get; set; }
        public string OrderStyleRefId { get; set; }
        public string LotNo { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public int? CountryId { get; set; }
    
        public string PortOfLoadingRefId { get; set; }
    
        public Nullable<decimal> Quantity { get; set; }
       
        public string IModeRefId { get; set; }
    
        public Nullable<System.DateTime> DeliveryDate { get; set; }

        public string StyleIRefId { get; set; }
        public Nullable<decimal> JobQty { get; set; }
        public Nullable<decimal> FinishQty { get; set; }
        public Nullable<int> ShipRowId { get; set; }
        public Nullable<decimal> ProductionQty { get; set; }
  
        public Nullable<int> DespatchQty { get; set; }
        public string ShipAmend { get; set; }
        public string CINo { get; set; }
        public DateTime? ETD { get; set; }
        public string Remarks { get; set; }
        public string CountryName { get; set; }
        public string PortOfLoadingName { get; set; }
        public string ModeName { get; set; }

    }
}
