//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model.Production;

namespace SCERP.Model.MerchandisingModel
{
    public partial class VYarnConsumption : ProSearchModel<VYarnConsumption>
    {
        public long YarnConsumptionId { get; set; }
        public string OrderStyleRefId { get; set; } 
        public string ItemCode { get; set; }
           [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string ItemName { get; set; }
        public string UnitName { get; set; }
        public string GColorName { get; set; }
        [Required(ErrorMessage =CustomErrorMessage.RequiredErrorMessage)]
        public string KColorName { get; set; }
         [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string KSizeName { get; set; }
  
        public string YCRef { get; set; }
        public string CompId { get; set; }
        public string ConsRefId { get; set; }
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Nullable<decimal> CPercent { get; set; }
        public string DReq { get; set; }
        public string GrColorRefId { get; set; }
        public string KColorRefId { get; set; }
        public string KSizeRefId { get; set; }
        public Nullable<decimal> KQty { get; set; }
         [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Nullable<decimal> PLoss { get; set; }
        public Nullable<decimal> WMtr { get; set; }
        public decimal? Rate { get; set; }
        public string SupplierName { get; set; }
        public int? SupplierId { get; set; }
        public string PiRefId { get; set; }

    }
}
