//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class City:ProSearchModel<City>
    {
        public int CityId { get; set; }
        [Required(ErrorMessage = "Required")]
        public string CityName { get; set; }
           [Required(ErrorMessage = "Required")]
        public int CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual State State { get; set; }
    }
}
