//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model.CommonModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMailTemplateComp
    {
        public int EailTemplateCompId { get; set; }
        public string CompId { get; set; }
        public int EailTemplateId { get; set; }
    
        public virtual EmailTemplate EmailTemplate { get; set; }
    }
}
