//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace SCERP.Model.CommonModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplateUser
    {
        public int EmailTamplateUserId { get; set; }
        public string CompId { get; set; }
        [Required(ErrorMessage = "Template is Missing")]
        public int EailTamplateId { get; set; }
        [Required(ErrorMessage = "Email User Missing")]
        public int EmailUserId { get; set; }
        [Required(ErrorMessage = "Sending Type Missing")]
        public string SendingType { get; set; }
    
        public virtual EmailTemplate EmailTemplate { get; set; }
        public virtual EmailUser EmailUser { get; set; }
    }
}
