//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace SCERP.Model.CommonModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplate
    {
        public EmailTemplate()
        {
            this.EMailTemplateComp = new HashSet<EMailTemplateComp>();
            this.EmailTemplateUser = new HashSet<EmailTemplateUser>();
        }
    
        public int EmailTemplateId { get; set; }
        public string EmailTemplateRefId { get; set; }
        [Required(ErrorMessage = "Template is Missing")]
        public string EmailTemplateName { get; set; }
    
        public virtual ICollection<EMailTemplateComp> EMailTemplateComp { get; set; }
        public virtual ICollection<EmailTemplateUser> EmailTemplateUser { get; set; }
    }
}
