//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace SCERP.Model.CommonModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GatePass
    {
        public GatePass()
        {
            this.GatePassDetail = new HashSet<GatePassDetail>();
        }
    
        public int GatePassId { get; set; }
        public string RefId { get; set; }
        public string BillNo { get; set; }
        public string ChallanNo { get; set; }
         [Required]
        public Nullable<System.DateTime> ChallanDate { get; set; }
        [Required]
        public string PartyName { get; set; }
         [Required]
        public string Address { get; set; }
         [Required]
        public string Through { get; set; }
         [Required]
        public string Designation { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public string CompId { get; set; }
        public Nullable<System.Guid> ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
        public string BuyerName { get; set; }
        public string OrderName { get; set; }
        public string StyleName { get; set; }
        public string DriverName { get; set; }
        public string VehicleNo { get; set; }
        public string TypeId { get; set; }
        public virtual ICollection<GatePassDetail> GatePassDetail { get; set; }
    }
}
