//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.ObjectModel;
using System.Web.Mvc;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasurementUnit:SearchModel<MeasurementUnit>
    {
     
        public int UnitId { get; set; }
        [Remote("CheckMeasurementUnit", "MeasurementUnit", AdditionalFields = "UnitId", ErrorMessage = "Measurement Unit already exist")]
        public string UnitName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
        public virtual ICollection<Inventory_StoreLedger> Inventory_StoreLedger { get; set; }
    
    }
}
