//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.ComponentModel.DataAnnotations;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class State:ProSearchModel<State>
    {
        public State()
        {
            this.City = new HashSet<City>();
        }
    
        public int StateId { get; set; }
        [Required(ErrorMessage = "Required")]
        public string StateName { get; set; }
        [Required(ErrorMessage = "Required")]
        public int CountryId { get; set; }
        public double? Latitude { get; set; }
        public double? Longitude { get; set; }
        public virtual ICollection<City> City { get; set; }
        public virtual Country Country { get; set; }
    }
}
