//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.ObjectModel;
using SCERP.Common;
using SCERP.Model.CRMModel;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class Module : SearchModel<Module>
    {
        public Module()
        {
            this.CRMDocumentationOperation = new HashSet<CRMDocumentationOperation>();
            this.CRMDocumentationReport = new HashSet<CRMDocumentationReport>();
            this.ModuleFeature = new HashSet<ModuleFeature>();
        }

        public int Id { get; set; }
        [Required]
        public string ModuleName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CDT { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EDT { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }

        public virtual ICollection<CRMDocumentationOperation> CRMDocumentationOperation { get; set; }
        public virtual ICollection<CRMDocumentationReport> CRMDocumentationReport { get; set; }
        public virtual ICollection<ModuleFeature> ModuleFeature { get; set; }
    }
}
