//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using SCERP.Common;
using SCERP.Model.Production;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public class ModuleFeature : SearchModel<ModuleFeature>
    {
        public ModuleFeature()
        {
            this.UserRoles = new HashSet<UserRole>();
            this.Children = new Collection<ModuleFeature>();
        }

        public int Id { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        
        public string FeatureName { get; set; }
        
        public Nullable<int> ParentFeatureId { get; set; }
        
        public int ModuleId { get; set; }

        public string NavURL { get; set; }

        public Nullable<bool> ShowInMenu { get; set; }

        public int OrderId { get; set; }

        public Nullable<System.DateTime> CDT { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EDT { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }

        public virtual Module Module { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }

        public virtual ICollection<ModuleFeature> Children { get; set; }

    }
}
