//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class UserPermissionForDepartmentLevel
    {
        public int UserPermissionForDepartmentLevelId { get; set; }
        [Required]
        public string UserName { get; set; }
        public int CompanyId { get; set; }
        public int BranchId { get; set; }
        public int BranchUnitId { get; set; }
        public int BranchUnitDepartmentId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual BranchUnit BranchUnit { get; set; }
        public virtual BranchUnitDepartment BranchUnitDepartment { get; set; }
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
    }
}
