//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    
    public  class UserRole
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string CompId { get; set; }
        public int ModuleFeatureId { get; set; }
        public Nullable<int> AccessLevel { get; set; }
        public Nullable<System.DateTime> CDT { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EDT { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ModuleFeature ModuleFeature { get; set; }
        public virtual User User { get; set; }

    }
}
