//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.ObjectModel;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class User : SearchModel<User>
    {
        public User()
        {
            this.UserRoles = new HashSet<UserRole>();
            this.UserPermissionForDepartmentLevel = new Collection<UserPermissionForDepartmentLevel>();
            this.UserPermissionForEmployeeLevel = new Collection<UserPermissionForEmployeeLevel>();
        }

        public int Id { get; set; }

        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public Guid EmployeeId { get; set; }
        public Guid ContactId { get; set; }

        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

       // [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
        [Required]
        [Display(Name = "Email Id")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Enter valid email Id")]
        public string EmailAddress { get; set; } 
        public byte[] PasswordHash { get; set; }


        public Nullable<System.Guid> Salt { get; set; }

        //[Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        //[DataType(DataType.Password)]
        //[Display(Name = "Confirm Password")]
        //[Compare("Password", ErrorMessage = "password doesn't match")]
        //public string ConfirmPassword { get; set; }

        //[Display(Name = "Remember me?")]
        //public bool RememberMe { get; set; }

        public Nullable<System.DateTime> CDT { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EDT { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string TnaResponsible { get; set; }
        public bool IsSystemUser { get; set; }
        public string DomainName { get; set; }
        public string CompId { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }

        public virtual ICollection<UserPermissionForDepartmentLevel> UserPermissionForDepartmentLevel { get; set; }
        public virtual ICollection<UserPermissionForEmployeeLevel> UserPermissionForEmployeeLevel { get; set; }
    }
}
