//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using SCERP.Common;

namespace SCERP.Model
{
    using System;
    using System.Collections.Generic;

    public partial class UserPermissionForEmployeeLevel
    {
        public int UserPermissionForEmployeeLevelId { get; set; }
        
        [Required(ErrorMessage = CustomErrorMessage.RequiredErrorMessage)]
        public string UserName { get; set; }
   
        public int EmployeeTypeId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual EmployeeType EmployeeType { get; set; }
        public virtual User User { get; set; }
    }
}
