//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model.CRMModel
{
    using System;
    using System.Collections.Generic;

    public partial class CRMCollaborator : SearchModel<CRMCollaborator>
    {
        public CRMCollaborator()
        {
            this.CRMDocumentationOperation = new HashSet<CRMDocumentationOperation>();
            this.CRMDocumentationOperation1 = new HashSet<CRMDocumentationOperation>();
            this.CRMDocumentationReport = new HashSet<CRMDocumentationReport>();
            this.CRMDocumentationReport1 = new HashSet<CRMDocumentationReport>();
        }
    
        public int Id { get; set; }
        public System.Guid CollaboratorId { get; set; }
        public string CollaboratorName { get; set; }
        public string CollaboratorDisplayName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<CRMDocumentationOperation> CRMDocumentationOperation { get; set; }
        public virtual ICollection<CRMDocumentationOperation> CRMDocumentationOperation1 { get; set; }
        public virtual ICollection<CRMDocumentationReport> CRMDocumentationReport { get; set; }
        public virtual ICollection<CRMDocumentationReport> CRMDocumentationReport1 { get; set; }
    }
}
