//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCERP.Model.CRMModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CRMFeedback : SearchModel<CRMFeedback>
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public Nullable<int> JobStatus { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public string PhotographPath { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public string CreatedByDisplayName { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<System.Guid> EditedBy { get; set; }
        public bool IsActive { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> FromDate { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ToDate { get; set; }
    }
}
